b64_encode – Lib_VTK_IO
b64_encode Interface
3 statements
Source File
public interface b64_encode
Calls
Module Procedures
private pure subroutine b64_encode_R8(n, code)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_R8_a(n, code)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_R4(n, code)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_R4_a(n, code)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I8(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I8_a(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I4(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I4_a(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I2(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I2_a(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I1(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I1_a(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_string(s, code)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_string_a(s, code)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s(1:)
character(len=:), intent(out), allocatable :: code
Call graph
b64_encode calls b64_encode_i1_a, b64_encode_i1, b64_encode_i2_a, b64_encode_i2, b64_encode_i4_a, b64_encode_i4, b64_encode_i8_a, b64_encode_i8, b64_encode_r4_a, b64_encode_r4, b64_encode_r8_a, b64_encode_r8, b64_encode_string_a, b64_encode_string
b64_encode_i1_a calls encode_bits
b64_encode_i1 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_string_a calls byte_size, encode_bits
b64_encode_string calls byte_size, encode_bits
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p