bcton – Lib_VTK_IO
bcton Interface
3 statements
Source File
public interface bcton
Calls
Contents
Module Procedures
bctor_R8P bctor_R4P bctoi_I8P bctoi_I4P bctoi_I2P bctoi_I1P
Module Procedures
private elemental function bctor_R8P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: bstr
real(kind=R8P), intent(in) :: knd
Return Value real(kind=R8P)
private elemental function bctor_R4P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: bstr
real(kind=R4P), intent(in) :: knd
Return Value real(kind=R4P)
private elemental function bctoi_I8P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: bstr
integer(kind=I8P), intent(in) :: knd
Return Value integer(kind=I8P)
private elemental function bctoi_I4P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: bstr
integer(kind=I4P), intent(in) :: knd
Return Value integer(kind=I4P)
private elemental function bctoi_I2P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: bstr
integer(kind=I2P), intent(in) :: knd
Return Value integer(kind=I2P)
private elemental function bctoi_I1P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: bstr
integer(kind=I1P), intent(in) :: knd
Return Value integer(kind=I1P)
Call graph
bcton calls bctoi_i2p, bctor_r4p, bctoi_i4p, bctor_r8p, bctoi_i8p, bctoi_i1p
bctoi_i2p calls str
bctoi_i4p calls str
bctoi_i8p calls str
bctoi_i1p calls str
str calls strf_i8p, str_a_i8p, str_i8p, str_i1p, strf_i1p, str_a_i1p, strf_r8p, str_a_r8p, strf_i4p, str_i4p, str_a_i4p, str_bol, str_r4p, strf_r4p, str_a_r4p, strf_i2p, str_i2p, str_a_i2p, str_r8p
str_a_i8p calls str_i8p
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_a_i4p calls str_i4p
str_r4p calls compact_real_string
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_r8p calls compact_real_string