digit – Lib_VTK_IO
digit Interface
3 statements
Source File
public interface digit
Calls
Called by
Contents
Module Procedures
digit_I8 digit_I4 digit_I2 digit_I1
Module Procedures
private elemental function digit_I8(n) result(digit)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n
Return Value integer(kind=I4P)
private elemental function digit_I4(n) result(digit)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n
Return Value integer(kind=I4P)
private elemental function digit_I2(n) result(digit)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n
Return Value integer(kind=I4P)
private elemental function digit_I1(n) result(digit)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n
Return Value integer(kind=I4P)
Call graph
digit calls digit_i8, digit_i2, digit_i4, digit_i1
volatile_doctest calls digit