pack_data – Lib_VTK_IO
pack_data Interface
3 statements
Source File
public interface pack_data
Calls
Contents
Module Procedures
pack_data_R8_R4 pack_data_R8_I8 pack_data_R8_I4 pack_data_R8_I2 pack_data_R8_I1 pack_data_R4_R8 pack_data_R4_I8 pack_data_R4_I4 pack_data_R4_I2 pack_data_R4_I1 pack_data_I8_R8 pack_data_I8_R4 pack_data_I8_I4 pack_data_I8_I2 pack_data_I8_I1 pack_data_I4_R8 pack_data_I4_R4 pack_data_I4_I8 pack_data_I4_I2 pack_data_I4_I1 pack_data_I2_R8 pack_data_I2_R4 pack_data_I2_I8 pack_data_I2_I4 pack_data_I2_I1 pack_data_I1_R8 pack_data_I1_R4 pack_data_I1_I8 pack_data_I1_I4 pack_data_I1_I2
Module Procedures
private pure subroutine pack_data_R8_R4(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: a1(1:)
real(kind=R4P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_R8_I8(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: a1(1:)
integer(kind=I8P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_R8_I4(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: a1(1:)
integer(kind=I4P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_R8_I2(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: a1(1:)
integer(kind=I2P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_R8_I1(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: a1(1:)
integer(kind=I1P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_R4_R8(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: a1(1:)
real(kind=R8P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_R4_I8(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: a1(1:)
integer(kind=I8P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_R4_I4(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: a1(1:)
integer(kind=I4P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_R4_I2(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: a1(1:)
integer(kind=I2P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_R4_I1(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: a1(1:)
integer(kind=I1P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I8_R8(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: a1(1:)
real(kind=R8P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I8_R4(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: a1(1:)
real(kind=R4P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I8_I4(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: a1(1:)
integer(kind=I4P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I8_I2(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: a1(1:)
integer(kind=I2P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I8_I1(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: a1(1:)
integer(kind=I1P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I4_R8(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: a1(1:)
real(kind=R8P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I4_R4(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: a1(1:)
real(kind=R4P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I4_I8(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: a1(1:)
integer(kind=I8P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I4_I2(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: a1(1:)
integer(kind=I2P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I4_I1(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: a1(1:)
integer(kind=I1P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I2_R8(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: a1(1:)
real(kind=R8P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I2_R4(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: a1(1:)
real(kind=R4P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I2_I8(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: a1(1:)
integer(kind=I8P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I2_I4(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: a1(1:)
integer(kind=I4P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I2_I1(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: a1(1:)
integer(kind=I1P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I1_R8(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: a1(1:)
real(kind=R8P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I1_R4(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: a1(1:)
real(kind=R4P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I1_I8(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: a1(1:)
integer(kind=I8P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I1_I4(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: a1(1:)
integer(kind=I4P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
private pure subroutine pack_data_I1_I2(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: a1(1:)
integer(kind=I2P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Call graph
pack_data calls pack_data_r4_r8, pack_data_i2_r4, pack_data_i1_i2, pack_data_i8_i2, pack_data_r8_r4, pack_data_r4_i2, pack_data_i4_r4, pack_data_i2_i1, pack_data_r8_i2, pack_data_i8_r4, pack_data_i4_i1, pack_data_i1_i8, pack_data_r4_i8, pack_data_i8_i1, pack_data_i2_i8, pack_data_r8_i8, pack_data_r4_i1, pack_data_i4_i8, pack_data_i1_r8, pack_data_r8_i1, pack_data_i8_i4, pack_data_i2_r8, pack_data_i1_i4, pack_data_r4_i4, pack_data_i4_r8, pack_data_i2_i4, pack_data_r8_i4, pack_data_i8_r8, pack_data_i4_i2, pack_data_i1_r4