scan – Lib_VTK_IO
scan Interface
3 statements
Source File
public interface scan
Calls
Module Procedures
private elemental function sscan_string_string(self, set, back) result(i)
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
type(string), intent(in) :: set
logical, intent(in), optional :: back
Return Value integer
private elemental function sscan_string_character(self, set, back) result(i)
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
character(kind=CK, len=*), intent(in) :: set
logical, intent(in), optional :: back
Return Value integer
private elemental function sscan_character_string(s, set, back) result(i)
Arguments
Type Intent Optional Attributes Name
character(kind=CK, len=*), intent(in) :: s
type(string), intent(in) :: set
logical, intent(in), optional :: back
Return Value integer
Call graph
scan calls sscan_character_string, sscan_string_character, sscan_string_string