verify – Lib_VTK_IO
verify Interface
3 statements
Source File
public interface verify
Calls
Contents
Module Procedures
sverify_string_string sverify_string_character sverify_character_string
Module Procedures
private elemental function sverify_string_string(self, set, back) result(i)
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
type(string), intent(in) :: set
logical, intent(in), optional :: back
Return Value integer
private elemental function sverify_string_character(self, set, back) result(i)
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
character(kind=CK,len=*), intent(in) :: set
logical, intent(in), optional :: back
Return Value integer
private elemental function sverify_character_string(s, set, back) result(i)
Arguments
Type Intent Optional Attributes Name
character(kind=CK,len=*), intent(in) :: s
type(string), intent(in) :: set
logical, intent(in), optional :: back
Return Value integer
Call graph
verify calls sverify_string_string, sverify_string_character, sverify_character_string