xml_tag – Lib_VTK_IO
xml_tag Interface
3 statements
Source File
public interface xml_tag
Calls
Module Procedures
private pure function create_tag_flat(name, attribute, attributes, attributes_stream, sanitize_attributes_value, pos, content, indent, is_content_indented, is_self_closing, id, level, parent_id, attributes_stream_alloc, content_alloc) result(tag)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
character(len=*), intent(in), optional :: attribute(1:)
character(len=*), intent(in), optional :: attributes(1:,1:)
character(len=*), intent(in), optional :: attributes_stream
logical, intent(in), optional :: sanitize_attributes_value
integer(kind=I4P), intent(in), optional :: pos(1:)
character(len=*), intent(in), optional :: content
integer(kind=I4P), intent(in), optional :: indent
logical, intent(in), optional :: is_content_indented
logical, intent(in), optional :: is_self_closing
integer(kind=I4P), intent(in), optional :: id
integer(kind=I4P), intent(in), optional :: level
integer(kind=I4P), intent(in), optional :: parent_id
character(len=:), intent(in), optional, allocatable :: attributes_stream_alloc
character(len=:), intent(in), optional, allocatable :: content_alloc
Return Value type(xml_tag)
private pure function create_tag_nested(name, content, attribute, attributes, attributes_stream, sanitize_attributes_value, pos, indent, is_content_indented, id, level, parent_id, attributes_stream_alloc, content_alloc) result(tag)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
type(xml_tag), intent(in) :: content
character(len=*), intent(in), optional :: attribute(1:)
character(len=*), intent(in), optional :: attributes(1:,1:)
character(len=*), intent(in), optional :: attributes_stream
logical, intent(in), optional :: sanitize_attributes_value
integer(kind=I4P), intent(in), optional :: pos(1:)
integer(kind=I4P), intent(in), optional :: indent
logical, intent(in), optional :: is_content_indented
integer(kind=I4P), intent(in), optional :: id
integer(kind=I4P), intent(in), optional :: level
integer(kind=I4P), intent(in), optional :: parent_id
character(len=:), intent(in), optional, allocatable :: attributes_stream_alloc
character(len=:), intent(in), optional, allocatable :: content_alloc
Return Value type(xml_tag)
Call graph
xml_tag calls create_tag_flat, create_tag_nested
create_tag_flat calls set
create_tag_nested calls set, stringify
set calls add_multiple_attributes, add_single_attribute, add_stream_attributes
stringify calls str, attributes, chars, end_tag, is_allocated, self_closing_tag, start_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
add_multiple_attributes calls add_single_attribute
add_single_attribute calls alloc_attributes
add_stream_attributes calls add_single_attribute, fill, partition, slice
self_closing_tag calls attributes
start_tag calls attributes
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string