volatile_doctest – Lib_VTK_IO
volatile_doctest Program
5 statements
Source File
Uses
penf
Calls
Contents
Source Code
volatile_doctest
Source Code
program volatile_doctest
use penf
 use penf
 print FI4P, digit(100_I8P)
endprogram volatile_doctest
Call graph
volatile_doctest calls digit
digit calls digit_i8, digit_i2, digit_i4, digit_i1