volatile_doctest – Lib_VTK_IO
volatile_doctest Program
6 statements
Source File
Uses
stringifor_string_t
Calls
Variables
Type Attributes Name Initial
type(string) :: astring
Source Code
program volatile_doctest
use stringifor_string_t
 type(string) :: astring
 astring = 'say all Hello WorLD!'
 print '(L1)', astring%colorize(color_fg='red')=='[31msay all Hello WorLD![0m'
endprogram volatile_doctest
Call graph
volatile_doctest calls colorize
colorize_str calls colorize, chars
colorize calls colorize_default
colorize_default calls color_index, style_index, upper