volatile_doctest – Lib_VTK_IO
volatile_doctest Program
6 statements
Source File
Uses
stringifor_string_t
Calls
Variables
Type Attributes Name Initial
type(string) :: astring
Source Code
program volatile_doctest
use stringifor_string_t
 type(string) :: astring
 astring = 'How are you?'
 print '(L1)', astring%encode(codec='base64')//''=='SG93IGFyZSB5b3U/'
endprogram volatile_doctest
Call graph
volatile_doctest calls encode
encode calls b64_encode, upper
b64_encode calls b64_encode_i1, b64_encode_i1_a, b64_encode_i2, b64_encode_i2_a, b64_encode_i4, b64_encode_i4_a, b64_encode_i8, b64_encode_i8_a, b64_encode_r4, b64_encode_r4_a, b64_encode_r8, b64_encode_r8_a, b64_encode_string, b64_encode_string_a
b64_encode_i1 calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_string calls byte_size, encode_bits
b64_encode_string_a calls byte_size, encode_bits
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p