volatile_doctest – Lib_VTK_IO
volatile_doctest Program
8 statements
Source File
Uses
penf
befor64
Calls
Contents
Variables
scalar_I2
Source Code
volatile_doctest
Variables
Type Attributes Name Initial
integer(kind=I2P) :: scalar_I2
Source Code
program volatile_doctest
use befor64
 use befor64
 use penf
 integer(I2P) :: scalar_I2
 call b64_decode(code='Nf8=',n=scalar_I2)
 print "(L1)", scalar_I2==-203_I2P
endprogram volatile_doctest
Call graph
volatile_doctest calls b64_decode
b64_decode calls b64_decode_r4, b64_decode_i1, b64_decode_i4_a, b64_decode_i4, b64_decode_r4_a, b64_decode_i1_a, b64_decode_r8, b64_decode_i8, b64_decode_r8_a, b64_decode_i8_a, b64_decode_i2, b64_decode_i2_a, b64_decode_string, b64_decode_string_a
b64_decode_r4 calls decode_bits
b64_decode_i1 calls decode_bits
b64_decode_i4_a calls decode_bits
b64_decode_i4 calls decode_bits
b64_decode_r4_a calls decode_bits
b64_decode_i1_a calls decode_bits
b64_decode_r8 calls decode_bits
b64_decode_i8 calls decode_bits
b64_decode_r8_a calls decode_bits
b64_decode_i8_a calls decode_bits
b64_decode_i2 calls decode_bits
b64_decode_i2_a calls decode_bits
b64_decode_string calls decode_bits, byte_size
b64_decode_string_a calls decode_bits, byte_size
byte_size calls byte_size_r8p, byte_size_i1p, byte_size_chr, byte_size_i4p, byte_size_i8p, byte_size_i2p, byte_size_r4p