vtk_fortran_write_vtu – Lib_VTK_IO
vtk_fortran_write_vtu Program
54 statements
Source File
Uses
vtk_fortran
penf
Calls
Variables
Type Attributes Name Initial
type(vtk_file) :: a_vtk_file
integer(kind=I4P), parameter :: np = 27_I4P
integer(kind=I4P), parameter :: nc = 11_I4P
real(kind=R4P), dimension(1:np) :: x = [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]
real(kind=R4P), dimension(1:np) :: y = [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
real(kind=R4P), dimension(1:np) :: z = [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6]
integer(kind=I1P), dimension(1:nc) :: cell_type = [12_I1P, 12_I1P, 10_I1P, 10_I1P, 7_I1P, 6_I1P, 9_I1P, 5_I1P, 5_I1P, 3_I1P, 1_I1P]
integer(kind=I4P), dimension(1:nc) :: offset = [8_I4P, 16_I4P, 20_I4P, 24_I4P, 30_I4P, 36_I4P, 40_I4P, 43_I4P, 46_I4P, 48_I4P, 49_I4P]
integer(kind=I4P), dimension(1:49) :: connect
real(kind=R8P), dimension(1:np) :: v
integer(kind=I4P), dimension(1:np) :: v_u
integer(kind=I4P), dimension(1:np) :: v_v
integer(kind=I4P), dimension(1:np) :: v_w
integer(kind=I4P), dimension(1:np) :: v_x
integer(kind=I4P), dimension(1:np) :: v_y
integer(kind=I4P), dimension(1:np) :: v_z
integer(kind=I4P) :: error
logical :: test_passed(1)
Subroutines
subroutine write_data()
Arguments
None
Source Code
program vtk_fortran_write_vtu
!< VTK_Fortran test: write VTU file.
use penf
use vtk_fortran, only : vtk_file
implicit none
type(vtk_file)                :: a_vtk_file                                                   !< A VTK file.
integer(I4P), parameter       :: np = 27_I4P                                                  !< Number of points.
integer(I4P), parameter       :: nc = 11_I4P                                                  !< Number of cells.
real(R4P),    dimension(1:np) :: x = [0,1,2,0,1,2,0,1,2,0,1,2,0,1,2,0,1,2,0,1,2,0,1,2,0,1,2]  !< X coordinates of points.
real(R4P),    dimension(1:np) :: y = [0,0,0,1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]  !< Y coordinates of points.
real(R4P),    dimension(1:np) :: z = [0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6]  !< Z coordinates of points.
integer(I1P), dimension(1:nc) :: cell_type = [12_I1P,12_I1P,10_I1P,10_I1P,&
                                              7_I1P,6_I1P,9_I1P,5_I1P,5_I1P,3_I1P,1_I1P]      !< Cells type.
integer(I4P), dimension(1:nc) :: offset = [8_I4P,16_I4P,20_I4P,24_I4P,30_I4P,&
                                           36_I4P,40_I4P,43_I4P,46_I4P,48_I4P,49_I4P]         !< Cells offset.
integer(I4P), dimension(1:49) :: connect                                                      !< Connectivity.
real(R8P),    dimension(1:np) :: v                                                            !< One component points-variable.
integer(I4P), dimension(1:np) :: v_u                                                          !< X component points-variable.
integer(I4P), dimension(1:np) :: v_v                                                          !< Y component points-variable.
integer(I4P), dimension(1:np) :: v_w                                                          !< Z component points-variable.
integer(I4P), dimension(1:np) :: v_x                                                          !< X component points-variable.
integer(I4P), dimension(1:np) :: v_y                                                          !< Y component points-variable.
integer(I4P), dimension(1:np) :: v_z                                                          !< Z component points-variable.
integer(I4P)                  :: error                                                        !< Status error.
logical                       :: test_passed(1)                                               !< List of passed tests.
connect = [0 ,1 ,4 ,3 ,6 ,7 ,10,9 , &
           1 ,2 ,5 ,4 ,7 ,8 ,11,10, &
           6 ,10,9 ,12,             &
           5 ,11,10,14,             &
           15,16,17,14,13,12,       &
           18,15,19,16,20,17,       &
           22,23,20,19,             &
           21,22,18,                &
           22,19,18,                &
           26,25,                   &
           24]
v = [0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0, &
     18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0]
v_U = [1,1,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
v_V = [0,1,2,0,1,2,0,1,2,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
v_W = [0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
v_X = [1,1,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
v_Y = [0,1,2,0,1,2,0,1,2,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
v_Z = [0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
! ascii
error = a_vtk_file%initialize(format='ascii', filename='XML_UNST_T-ascii.vtu', mesh_topology='UnstructuredGrid')
call write_data
error = a_vtk_file%finalize()
! raw
error = a_vtk_file%initialize(format='raw', filename='XML_UNST_T-raw.vtu', mesh_topology='UnstructuredGrid')
call write_data
error = a_vtk_file%finalize()
! binary
error = a_vtk_file%initialize(format='binary', filename='XML_UNST_T-binary.vtu', mesh_topology='UnstructuredGrid')
call write_data
error = a_vtk_file%finalize()
test_passed = .true. ! nothing to test yet
print "(A,L1)", new_line('a')//'Are all tests passed? ', all(test_passed)
stop
contains
  subroutine write_data
  !< Write data.
  error = a_vtk_file%xml_writer%write_piece(np=np, nc=nc)
  error = a_vtk_file%xml_writer%write_geo(np=np, nc=nc, x=x, y=y, z=z)
  error = a_vtk_file%xml_writer%write_connectivity(nc=nc, connectivity=connect, offset=offset, cell_type=cell_type)
  error = a_vtk_file%xml_writer%write_dataarray(location='node', action='open')
  error = a_vtk_file%xml_writer%write_dataarray(data_name='scalars', x=v)
  error = a_vtk_file%xml_writer%write_dataarray(data_name='tensor', u=v_u, v= v_v, w=v_w, x=v_x, y=v_y, z=v_z)
  error = a_vtk_file%xml_writer%write_dataarray(location='node', action='close')
  error = a_vtk_file%xml_writer%write_piece()
  endsubroutine write_data
endprogram vtk_fortran_write_vtu
Call graph
vtk_fortran_write_vtu calls finalize, initialize, write_data
finalize calls finalize
initialize calls initialize, b64_init, chars, penf_init, upper
write_data calls write_dataarray, write_geo, write_piece, write_connectivity
b64_init calls penf_init
penf_init calls check_endian
write_connectivity calls write_dataarray, write_end_tag, write_start_tag
write_dataarray1_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray_location_tag calls chars, upper, write_end_tag, write_start_tag
write_end_tag calls stringify
write_geo_rect_data3_rank1_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_rect_data3_rank1_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank2_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank2_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank4_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank4_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank1_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank1_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank3_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank3_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data1_rank2_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data1_rank2_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data3_rank1_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data3_rank1_r8p calls write_dataarray, write_end_tag, write_start_tag
write_piece_end_tag calls write_end_tag
write_piece_start_tag calls chars, write_start_tag, str
write_piece_start_tag_unst calls chars, write_start_tag, str
write_start_tag calls stringify
encode_binary_dataarray calls encode_binary_dataarray1_rank1_i1p, encode_binary_dataarray1_rank1_i2p, encode_binary_dataarray1_rank1_i4p, encode_binary_dataarray1_rank1_i8p, encode_binary_dataarray1_rank1_r4p, encode_binary_dataarray1_rank1_r8p, encode_binary_dataarray1_rank2_i1p, encode_binary_dataarray1_rank2_i2p, encode_binary_dataarray1_rank2_i4p, encode_binary_dataarray1_rank2_i8p, encode_binary_dataarray1_rank2_r4p, encode_binary_dataarray1_rank2_r8p, encode_binary_dataarray1_rank3_i1p, encode_binary_dataarray1_rank3_i2p, encode_binary_dataarray1_rank3_i4p, encode_binary_dataarray1_rank3_i8p, encode_binary_dataarray1_rank3_r4p, encode_binary_dataarray1_rank3_r8p, encode_binary_dataarray1_rank4_i1p, encode_binary_dataarray1_rank4_i2p, encode_binary_dataarray1_rank4_i4p, encode_binary_dataarray1_rank4_i8p, encode_binary_dataarray1_rank4_r4p, encode_binary_dataarray1_rank4_r8p, encode_binary_dataarray3_rank1_i1p, encode_binary_dataarray3_rank1_i2p, encode_binary_dataarray3_rank1_i4p, encode_binary_dataarray3_rank1_i8p, encode_binary_dataarray3_rank1_r4p, encode_binary_dataarray3_rank1_r8p, encode_binary_dataarray3_rank3_i1p, encode_binary_dataarray3_rank3_i2p, encode_binary_dataarray3_rank3_i4p, encode_binary_dataarray3_rank3_i8p, encode_binary_dataarray3_rank3_r4p, encode_binary_dataarray3_rank3_r8p, encode_binary_dataarray6_rank1_i1p, encode_binary_dataarray6_rank1_i2p, encode_binary_dataarray6_rank1_i4p, encode_binary_dataarray6_rank1_i8p, encode_binary_dataarray6_rank1_r4p, encode_binary_dataarray6_rank1_r8p, encode_binary_dataarray6_rank3_i1p, encode_binary_dataarray6_rank3_i2p, encode_binary_dataarray6_rank3_i4p, encode_binary_dataarray6_rank3_i8p, encode_binary_dataarray6_rank3_r4p, encode_binary_dataarray6_rank3_r8p
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
stringify calls chars, str, attributes, end_tag, is_allocated, self_closing_tag, start_tag
write_dataarray_tag calls chars, str, write_tag
encode_binary_dataarray1_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_i4p calls b64_encode
encode_binary_dataarray1_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i4p calls b64_encode
encode_binary_dataarray1_rank2_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i4p calls b64_encode
encode_binary_dataarray1_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i4p calls b64_encode
encode_binary_dataarray1_rank4_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_r8p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i4p calls b64_encode
encode_binary_dataarray3_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i4p calls b64_encode
encode_binary_dataarray3_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_r8p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i4p calls b64_encode
encode_binary_dataarray6_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i4p calls b64_encode
encode_binary_dataarray6_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_r8p calls b64_encode, pack_data
self_closing_tag calls attributes
start_tag calls attributes
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
write_tag calls stringify
b64_encode calls b64_encode_i1, b64_encode_i1_a, b64_encode_i2, b64_encode_i2_a, b64_encode_i4, b64_encode_i4_a, b64_encode_i8, b64_encode_i8_a, b64_encode_r4, b64_encode_r4_a, b64_encode_r8, b64_encode_r8_a, b64_encode_string, b64_encode_string_a
pack_data calls pack_data_i1_i2, pack_data_i1_i4, pack_data_i1_i8, pack_data_i1_r4, pack_data_i1_r8, pack_data_i2_i1, pack_data_i2_i4, pack_data_i2_i8, pack_data_i2_r4, pack_data_i2_r8, pack_data_i4_i1, pack_data_i4_i2, pack_data_i4_i8, pack_data_i4_r4, pack_data_i4_r8, pack_data_i8_i1, pack_data_i8_i2, pack_data_i8_i4, pack_data_i8_r4, pack_data_i8_r8, pack_data_r4_i1, pack_data_r4_i2, pack_data_r4_i4, pack_data_r4_i8, pack_data_r4_r8, pack_data_r8_i1, pack_data_r8_i2, pack_data_r8_i4, pack_data_r8_i8, pack_data_r8_r4
b64_encode_i1 calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_string calls byte_size, encode_bits
b64_encode_string_a calls byte_size, encode_bits
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p