vtk_fortran_write_volatile – Lib_VTK_IO
vtk_fortran_write_volatile Program
144 statements
Source File
Uses
vtk_fortran
penf
Calls
Variables
Type Attributes Name Initial
character(len=:), allocatable :: xml_volatile_file_1
character(len=:), allocatable :: xml_volatile_file_2
integer(kind=I4P) :: error
Subroutines
subroutine write_slave(x_offset, y_offset, z_offset, xml_volatile)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: x_offset
real(kind=R8P), intent(in) :: y_offset
real(kind=R8P), intent(in) :: z_offset
character(len=:), intent(out), allocatable :: xml_volatile
subroutine write_check(filename)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
Source Code
program vtk_fortran_write_volatile
!< VTK_Fortran test: write *volatile* file.
!< Test the writing of *volatile* XML file for enabling some parallel environments where only one process
!< (master process) has access to the filestyem, whereas other processes cannot.
use penf
use vtk_fortran, only : vtk_file, write_xml_volatile
implicit none
character(:), allocatable :: xml_volatile_file_1 !< XML volatile file 1.
character(:), allocatable :: xml_volatile_file_2 !< XML volatile file 2.
integer(I4P)              :: error               !< Status error.
! suppose that two slave processes create their own files, but they being not allowed to access to filesystem they creates
! "volatile" files in the form of string containing the XML-coded files
call write_slave(x_offset=0._R8P, y_offset=0._R8P, z_offset=0._R8P, xml_volatile = xml_volatile_file_1)
call write_slave(x_offset=6._R8P, y_offset=0._R8P, z_offset=0._R8P, xml_volatile = xml_volatile_file_2)
! now the master process can collect volatile files from slave processes and save them to filestystem
error = write_xml_volatile(xml_volatile=xml_volatile_file_1, filename="write_volatile_slave_1.vtr")
error = write_xml_volatile(xml_volatile=xml_volatile_file_2, filename="write_volatile_slave_2.vtr")
call write_check(filename="write_volatile_slave_1_check.vtr")
contains
   subroutine write_slave(x_offset, y_offset, z_offset, xml_volatile)
   !< Slave writer: creates *volatile* file, not a real one. This is what a slave process should do, create a volatile file (a
   !< string containing the XML file). Note that it is the same of what a standard process does for creating a real file except for
   !< the flag `is_volatile=.true.` and for the last two methods invoked for retreiving the volatile XML file and to free the
   !< memory.
   real(R8P),    intent(in)               :: x_offset     !< Offset along x axis.
   real(R8P),    intent(in)               :: y_offset     !< Offset along y axis.
   real(R8P),    intent(in)               :: z_offset     !< Offset along z axis.
   character(:), intent(out), allocatable :: xml_volatile !< XML volatile file.
   type(vtk_file)                         :: a_vtk_file   !< A VTK filei: temporary file to create the volatile string.
   ! dimensions of files
   integer(I4P), parameter :: nx1=0_I4P                              !< X lower bound extent.
   integer(I4P), parameter :: nx2=16_I4P                             !< X upper bound extent.
   integer(I4P), parameter :: ny1=0_I4P                              !< Y lower bound extent.
   integer(I4P), parameter :: ny2=16_I4P                             !< Y upper bound extent.
   integer(I4P), parameter :: nz1=0_I4P                              !< Z lower bound extent.
   integer(I4P), parameter :: nz2=16_I4P                             !< Z upper bound extent.
   integer(I4P), parameter :: nn=(nx2-nx1+1)*(ny2-ny1+1)*(nz2-nz1+1) !< Number of elements.
   ! data files
   real(R8P)    :: x(nx1:nx2) !< X coordinates.
   real(R8P)    :: y(ny1:ny2) !< Y coordinates.
   real(R8P)    :: z(nz1:nz2) !< Z coordinates.
   integer(I4P) :: v(1:nn)    !< Variable defined at coordinates.
   ! auxiliaries
   integer(I4P) :: error !< Status error.
   integer(I4P) :: i     !< Counter.
   integer(I4P) :: j     !< Counter.
   integer(I4P) :: k     !< Counter.
   integer(I4P) :: n     !< Counter.
   real(R8P)    :: x1    !< X lower extent.
   real(R8P)    :: x2    !< X upper extent.
   real(R8P)    :: y1    !< Y lower extent.
   real(R8P)    :: y2    !< Y upper extent.
   real(R8P)    :: z1    !< Z lower extent.
   real(R8P)    :: z2    !< Z upper extent.
   x1= -3._R8P   + x_offset
   x2=  3._R8P   + x_offset
   y1= -2._R8P   + y_offset
   y2=  0.25_R8P + y_offset
   z1= -2._R8P   + z_offset
   z2=  0.16_R8P + z_offset
   n = 0
   do k=nz1,nz2
      do j=ny1,ny2
         do i=nx1,nx2
            n = n + 1
            v(n) = i*j*k
         enddo
      enddo
   enddo
   do i=nx1,nx2
      x(i) = x1 + (i - 1) * (x2 - x1)/real(nx2 - nx1, kind=R8P)
   enddo
   do j=ny1,ny2
      y(j) = y1 + (j - 1) * (y2 - y1)/real(ny2 - ny1, kind=R8P)
   enddo
   do k=nz1,nz2
      z(k) = z1 + (k - 1) * (z2 - z1)/real(nz2 - nz1, kind=R8P)
   enddo
   error = a_vtk_file%initialize(format='binary', filename='volatile.vtr', mesh_topology='RectilinearGrid', &
                                 is_volatile=.true., nx1=nx1, nx2=nx2, ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2)
   error = a_vtk_file%xml_writer%write_fielddata(action='open')
   error = a_vtk_file%xml_writer%write_fielddata(x=0._R8P, data_name='TIME')
   error = a_vtk_file%xml_writer%write_fielddata(x=1_I8P, data_name='CYCLE')
   error = a_vtk_file%xml_writer%write_fielddata(action='close')
   error = a_vtk_file%xml_writer%write_piece(nx1=nx1, nx2=nx2, ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2)
   error = a_vtk_file%xml_writer%write_geo(x=x, y=y, z=z)
   error = a_vtk_file%xml_writer%write_dataarray(location='cell', action='open')
   error = a_vtk_file%xml_writer%write_dataarray(data_name='cell_value', x=v)
   error = a_vtk_file%xml_writer%write_dataarray(location='cell', action='close')
   error = a_vtk_file%xml_writer%write_piece()
   error = a_vtk_file%finalize()
   ! new methods: to get the volatile file encoded into a character string and to free the memory after the file string has been
   ! retrieved
   call a_vtk_file%get_xml_volatile(xml_volatile)
   call a_vtk_file%free
   endsubroutine write_slave
   subroutine write_check(filename)
   !< Check writer: creates a real file for checking the volatile writer.
   character(*), intent(in) :: filename   !< XML file name.
   type(vtk_file)           :: a_vtk_file !< A VTK filei: temporary file to create the volatile string.
   ! dimensions of files
   integer(I4P), parameter :: nx1=0_I4P                              !< X lower bound extent.
   integer(I4P), parameter :: nx2=16_I4P                             !< X upper bound extent.
   integer(I4P), parameter :: ny1=0_I4P                              !< Y lower bound extent.
   integer(I4P), parameter :: ny2=16_I4P                             !< Y upper bound extent.
   integer(I4P), parameter :: nz1=0_I4P                              !< Z lower bound extent.
   integer(I4P), parameter :: nz2=16_I4P                             !< Z upper bound extent.
   integer(I4P), parameter :: nn=(nx2-nx1+1)*(ny2-ny1+1)*(nz2-nz1+1) !< Number of elements.
   ! data files
   real(R8P)    :: x(nx1:nx2) !< X coordinates.
   real(R8P)    :: y(ny1:ny2) !< Y coordinates.
   real(R8P)    :: z(nz1:nz2) !< Z coordinates.
   integer(I4P) :: v(1:nn)    !< Variable defined at coordinates.
   ! auxiliaries
   integer(I4P) :: error !< Status error.
   integer(I4P) :: i     !< Counter.
   integer(I4P) :: j     !< Counter.
   integer(I4P) :: k     !< Counter.
   integer(I4P) :: n     !< Counter.
   real(R8P)    :: x1    !< X lower extent.
   real(R8P)    :: x2    !< X upper extent.
   real(R8P)    :: y1    !< Y lower extent.
   real(R8P)    :: y2    !< Y upper extent.
   real(R8P)    :: z1    !< Z lower extent.
   real(R8P)    :: z2    !< Z upper extent.
   x1= -3._R8P
   x2=  3._R8P
   y1= -2._R8P
   y2=  0.25_R8P
   z1= -2._R8P
   z2=  0.16_R8P
   n = 0
   do k=nz1,nz2
      do j=ny1,ny2
         do i=nx1,nx2
            n = n + 1
            v(n) = i*j*k
         enddo
      enddo
   enddo
   do i=nx1,nx2
      x(i) = x1 + (i - 1) * (x2 - x1)/real(nx2 - nx1, kind=R8P)
   enddo
   do j=ny1,ny2
      y(j) = y1 + (j - 1) * (y2 - y1)/real(ny2 - ny1, kind=R8P)
   enddo
   do k=nz1,nz2
      z(k) = z1 + (k - 1) * (z2 - z1)/real(nz2 - nz1, kind=R8P)
   enddo
   error = a_vtk_file%initialize(format='binary', filename=filename, mesh_topology='RectilinearGrid', &
                                 is_volatile=.false., nx1=nx1, nx2=nx2, ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2)
   error = a_vtk_file%xml_writer%write_fielddata(action='open')
   error = a_vtk_file%xml_writer%write_fielddata(x=0._R8P, data_name='TIME')
   error = a_vtk_file%xml_writer%write_fielddata(x=1_I8P, data_name='CYCLE')
   error = a_vtk_file%xml_writer%write_fielddata(action='close')
   error = a_vtk_file%xml_writer%write_piece(nx1=nx1, nx2=nx2, ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2)
   error = a_vtk_file%xml_writer%write_geo(x=x, y=y, z=z)
   error = a_vtk_file%xml_writer%write_dataarray(location='cell', action='open')
   error = a_vtk_file%xml_writer%write_dataarray(data_name='cell_value', x=v)
   error = a_vtk_file%xml_writer%write_dataarray(location='cell', action='close')
   error = a_vtk_file%xml_writer%write_piece()
   error = a_vtk_file%finalize()
   call a_vtk_file%free
   endsubroutine write_check
endprogram vtk_fortran_write_volatile
Call graph
vtk_fortran_write_volatile calls write_check, write_slave, write_xml_volatile
write_check calls write_dataarray, write_fielddata, write_geo, write_piece, finalize, initialize
write_slave calls write_dataarray, write_fielddata, write_geo, write_piece, finalize, get_xml_volatile, initialize
finalize calls finalize
get_xml_volatile calls get_xml_volatile
initialize calls initialize, b64_init, chars, penf_init, upper
b64_init calls penf_init
penf_init calls check_endian
write_dataarray1_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray_location_tag calls chars, upper, write_end_tag, write_start_tag
write_fielddata1_rank0 calls write_dataarray
write_fielddata_tag calls chars, upper, write_end_tag, write_start_tag
write_geo_rect_data3_rank1_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_rect_data3_rank1_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank2_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank2_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank4_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank4_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank1_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank1_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank3_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank3_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data1_rank2_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data1_rank2_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data3_rank1_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data3_rank1_r8p calls write_dataarray, write_end_tag, write_start_tag
write_piece_end_tag calls write_end_tag
write_piece_start_tag calls chars, str, write_start_tag
write_piece_start_tag_unst calls chars, str, write_start_tag
encode_binary_dataarray calls encode_binary_dataarray1_rank1_i1p, encode_binary_dataarray1_rank1_i2p, encode_binary_dataarray1_rank1_i4p, encode_binary_dataarray1_rank1_i8p, encode_binary_dataarray1_rank1_r4p, encode_binary_dataarray1_rank1_r8p, encode_binary_dataarray1_rank2_i1p, encode_binary_dataarray1_rank2_i2p, encode_binary_dataarray1_rank2_i4p, encode_binary_dataarray1_rank2_i8p, encode_binary_dataarray1_rank2_r4p, encode_binary_dataarray1_rank2_r8p, encode_binary_dataarray1_rank3_i1p, encode_binary_dataarray1_rank3_i2p, encode_binary_dataarray1_rank3_i4p, encode_binary_dataarray1_rank3_i8p, encode_binary_dataarray1_rank3_r4p, encode_binary_dataarray1_rank3_r8p, encode_binary_dataarray1_rank4_i1p, encode_binary_dataarray1_rank4_i2p, encode_binary_dataarray1_rank4_i4p, encode_binary_dataarray1_rank4_i8p, encode_binary_dataarray1_rank4_r4p, encode_binary_dataarray1_rank4_r8p, encode_binary_dataarray3_rank1_i1p, encode_binary_dataarray3_rank1_i2p, encode_binary_dataarray3_rank1_i4p, encode_binary_dataarray3_rank1_i8p, encode_binary_dataarray3_rank1_r4p, encode_binary_dataarray3_rank1_r8p, encode_binary_dataarray3_rank3_i1p, encode_binary_dataarray3_rank3_i2p, encode_binary_dataarray3_rank3_i4p, encode_binary_dataarray3_rank3_i8p, encode_binary_dataarray3_rank3_r4p, encode_binary_dataarray3_rank3_r8p, encode_binary_dataarray6_rank1_i1p, encode_binary_dataarray6_rank1_i2p, encode_binary_dataarray6_rank1_i4p, encode_binary_dataarray6_rank1_i8p, encode_binary_dataarray6_rank1_r4p, encode_binary_dataarray6_rank1_r8p, encode_binary_dataarray6_rank3_i1p, encode_binary_dataarray6_rank3_i2p, encode_binary_dataarray6_rank3_i4p, encode_binary_dataarray6_rank3_i8p, encode_binary_dataarray6_rank3_r4p, encode_binary_dataarray6_rank3_r8p
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
write_dataarray_tag calls chars, str, write_tag
write_end_tag calls stringify
write_start_tag calls stringify
encode_binary_dataarray1_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_i4p calls b64_encode
encode_binary_dataarray1_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i4p calls b64_encode
encode_binary_dataarray1_rank2_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i4p calls b64_encode
encode_binary_dataarray1_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i4p calls b64_encode
encode_binary_dataarray1_rank4_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_r8p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i4p calls b64_encode
encode_binary_dataarray3_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i4p calls b64_encode
encode_binary_dataarray3_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_r8p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i4p calls b64_encode
encode_binary_dataarray6_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i4p calls b64_encode
encode_binary_dataarray6_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_r8p calls b64_encode, pack_data
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls chars, str, attributes, end_tag, is_allocated, self_closing_tag, start_tag
write_tag calls stringify
b64_encode calls b64_encode_i1, b64_encode_i1_a, b64_encode_i2, b64_encode_i2_a, b64_encode_i4, b64_encode_i4_a, b64_encode_i8, b64_encode_i8_a, b64_encode_r4, b64_encode_r4_a, b64_encode_r8, b64_encode_r8_a, b64_encode_string, b64_encode_string_a
pack_data calls pack_data_i1_i2, pack_data_i1_i4, pack_data_i1_i8, pack_data_i1_r4, pack_data_i1_r8, pack_data_i2_i1, pack_data_i2_i4, pack_data_i2_i8, pack_data_i2_r4, pack_data_i2_r8, pack_data_i4_i1, pack_data_i4_i2, pack_data_i4_i8, pack_data_i4_r4, pack_data_i4_r8, pack_data_i8_i1, pack_data_i8_i2, pack_data_i8_i4, pack_data_i8_r4, pack_data_i8_r8, pack_data_r4_i1, pack_data_r4_i2, pack_data_r4_i4, pack_data_r4_i8, pack_data_r4_r8, pack_data_r8_i1, pack_data_r8_i2, pack_data_r8_i4, pack_data_r8_i8, pack_data_r8_r4
self_closing_tag calls attributes
start_tag calls attributes
b64_encode_i1 calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_string calls byte_size, encode_bits
b64_encode_string_a calls byte_size, encode_bits
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p