alloc_attributes – Lib_VTK_IO
alloc_attributes Subroutine
10 statements
Source File
private elemental subroutine alloc_attributes(self, Na)
Type Bound
xml_tag
Arguments
Type Intent Optional Attributes Name
class(xml_tag), intent(inout) :: self
integer(kind=I4P), intent(in) :: Na
Called by
Source Code
   elemental subroutine alloc_attributes(self, Na)
   !< Allocate (prepare for filling) dynamic memory of attributes.
   class(xml_tag),    intent(inout) :: self     !< XML tag.
   integer(I4P),      intent(in)    :: Na       !< Number of attributes.
   if (allocated(self%attribute)) then
      call self%attribute%free
      deallocate(self%attribute)
   endif
   allocate(self%attribute(1:2, 1:Na))
   self%attributes_number = Na
   endsubroutine alloc_attributes
Call graph
add_single_attribute calls alloc_attributes
parse_attributes_names calls alloc_attributes
add_multiple_attributes calls add_single_attribute
add_stream_attributes calls add_single_attribute
parse calls parse_attributes_names, parse_from_string
set calls add_single_attribute, add_multiple_attributes, add_stream_attributes
create_tag_flat calls set
create_tag_nested calls set
parse_from_string calls set
search calls parse
foxy_test_add_attributes calls add_attributes
foxy_test_create_tag calls parse, set
xml_tag calls create_tag_flat, create_tag_nested
get_content calls search
content calls get_content
foxy_test_delete_tag calls parse
foxy_test_parse_file_simple calls parse
foxy_test_parse_string_nested_tags calls parse
foxy_test_parse_string_simple calls parse
foxy_test_write_tag calls parse