b64_encode_string_a – Lib_VTK_IO
b64_encode_string_a Subroutine
15 statements
Source File
private pure subroutine b64_encode_string_a(s, code)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s(1:)
character(len=:), intent(out), allocatable :: code
Calls
Called by
Source Code
   pure subroutine b64_encode_string_a(s, code)
   !< Encode array string to base64.
   !<
   !<```fortran
   !< use befor64
   !< use penf
   !< character(len=:), allocatable :: code64
   !< call b64_encode(s=['hello','world'], code=code64)
   !< print "(A)", code64
   !<```
   !=> aGVsbG93b3JsZA== <<<
   character(*),                  intent(in)  :: s(1:)   !< String to be encoded.
   character(len=:), allocatable, intent(out) :: code    !< Encoded scalar.
   integer(I1P),     allocatable              :: nI1P(:) !< One byte integer array containing n.
   integer(I4P)                               :: padd    !< Number of padding characters ('=').
   integer(I4P)                               :: BYCHS   !< Bytes of character string.
   BYCHS = byte_size(s(1))*size(s,dim=1)
   allocate(nI1P(1:((BYCHS+2)/3)*3)) ; nI1P = 0_I1P
   code = repeat(' ',((BYCHS+2)/3)*4)
   nI1P = transfer(s,nI1P)
   padd = mod((BYCHS),3_I4P) ; if (padd>0_I4P) padd = 3_I4P - padd
   call encode_bits(bits=nI1P,padd=padd,code=code)
   endsubroutine b64_encode_string_a
Call graph
b64_encode_string_a calls byte_size, encode_bits
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p
b64_encode calls b64_encode_string_a
b64_encode_up_a calls b64_encode_string_a
b64_encode_up calls b64_encode_up_a, b64_encode_up