b64_encode_I8_a – Lib_VTK_IO
b64_encode_I8_a Subroutine
15 statements
Source File
private pure subroutine b64_encode_I8_a(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
Calls
Called by
Source Code
   pure subroutine b64_encode_I8_a(n, code)
   !< Encode array numbers to base64 (I8P).
   !<
   !<```fortran
   !< use befor64
   !< use penf
   !< character(len=:), allocatable :: code64
   !< call b64_encode(n=[23_I8P,324_I8P,25456656_I8P,2_I8P], code=code64)
   !< print "(A)", code64
   !<```
   !=> FwAAAAAAAABEAQAAAAAAABBwhAEAAAAAAgAAAAAAAAA= <<<
   integer(I8P),                  intent(in)  :: n(1:)   !< Array of numbers to be encoded.
   character(len=:), allocatable, intent(out) :: code    !< Encoded array.
   integer(I1P),     allocatable              :: nI1P(:) !< One byte integer array containing n.
   integer(I4P)                               :: padd    !< Number of padding characters ('=').
   integer(I8P)                               :: ns      !< Size of n.
   ns = size(n,dim=1)
   allocate(nI1P(1:((ns*BYI8P+2)/3)*3)) ; nI1P = 0_I1P
   code = repeat(' ',((ns*BYI8P+2)/3)*4)
   nI1P = transfer(n,nI1P)
   padd = mod((ns*BYI8P),3_I8P) ; if (padd>0_I4P) padd = 3_I4P - padd
   call encode_bits(bits=nI1P,padd=padd,code=code)
   endsubroutine b64_encode_I8_a
Call graph
b64_encode_i8_a calls encode_bits
b64_encode calls b64_encode_i8_a
b64_encode_up_a calls b64_encode_i8_a
b64_encode_up calls b64_encode_up_a, b64_encode_up
encode calls b64_encode
encode_binary_dataarray1_rank1_i1p calls b64_encode
encode_binary_dataarray1_rank1_i2p calls b64_encode
encode_binary_dataarray1_rank1_i4p calls b64_encode
encode_binary_dataarray1_rank1_i8p calls b64_encode
encode_binary_dataarray1_rank1_r4p calls b64_encode
encode_binary_dataarray1_rank1_r8p calls b64_encode
encode_binary_dataarray1_rank2_i1p calls b64_encode
encode_binary_dataarray1_rank2_i2p calls b64_encode
encode_binary_dataarray1_rank2_i4p calls b64_encode
encode_binary_dataarray1_rank2_i8p calls b64_encode
encode_binary_dataarray1_rank2_r4p calls b64_encode
encode_binary_dataarray1_rank2_r8p calls b64_encode
encode_binary_dataarray1_rank3_i1p calls b64_encode
encode_binary_dataarray1_rank3_i2p calls b64_encode
encode_binary_dataarray1_rank3_i4p calls b64_encode
encode_binary_dataarray1_rank3_i8p calls b64_encode
encode_binary_dataarray1_rank3_r4p calls b64_encode
encode_binary_dataarray1_rank3_r8p calls b64_encode
encode_binary_dataarray1_rank4_i1p calls b64_encode
encode_binary_dataarray1_rank4_i2p calls b64_encode
encode_binary_dataarray1_rank4_i4p calls b64_encode
encode_binary_dataarray1_rank4_i8p calls b64_encode
encode_binary_dataarray1_rank4_r4p calls b64_encode
encode_binary_dataarray1_rank4_r8p calls b64_encode
encode_binary_dataarray3_rank1_i1p calls b64_encode
encode_binary_dataarray3_rank1_i2p calls b64_encode
encode_binary_dataarray3_rank1_i4p calls b64_encode
encode_binary_dataarray3_rank1_i8p calls b64_encode
encode_binary_dataarray3_rank1_r4p calls b64_encode
encode_binary_dataarray3_rank1_r8p calls b64_encode
encode_binary_dataarray3_rank3_i1p calls b64_encode
encode_binary_dataarray3_rank3_i2p calls b64_encode
encode_binary_dataarray3_rank3_i4p calls b64_encode
encode_binary_dataarray3_rank3_i8p calls b64_encode
encode_binary_dataarray3_rank3_r4p calls b64_encode
encode_binary_dataarray3_rank3_r8p calls b64_encode
encode_binary_dataarray6_rank1_i1p calls b64_encode
encode_binary_dataarray6_rank1_i2p calls b64_encode
encode_binary_dataarray6_rank1_i4p calls b64_encode
encode_binary_dataarray6_rank1_i8p calls b64_encode
encode_binary_dataarray6_rank1_r4p calls b64_encode
encode_binary_dataarray6_rank1_r8p calls b64_encode
encode_binary_dataarray6_rank3_i1p calls b64_encode
encode_binary_dataarray6_rank3_i2p calls b64_encode
encode_binary_dataarray6_rank3_i4p calls b64_encode
encode_binary_dataarray6_rank3_i8p calls b64_encode
encode_binary_dataarray6_rank3_r4p calls b64_encode
encode_binary_dataarray6_rank3_r8p calls b64_encode
volatile_doctest calls b64_encode, encode
encode_binary_dataarray calls encode_binary_dataarray1_rank1_i1p, encode_binary_dataarray1_rank1_i2p, encode_binary_dataarray1_rank1_i4p, encode_binary_dataarray1_rank1_i8p, encode_binary_dataarray1_rank1_r4p, encode_binary_dataarray1_rank1_r8p, encode_binary_dataarray1_rank2_i1p, encode_binary_dataarray1_rank2_i2p, encode_binary_dataarray1_rank2_i4p, encode_binary_dataarray1_rank2_i8p, encode_binary_dataarray1_rank2_r4p, encode_binary_dataarray1_rank2_r8p, encode_binary_dataarray1_rank3_i1p, encode_binary_dataarray1_rank3_i2p, encode_binary_dataarray1_rank3_i4p, encode_binary_dataarray1_rank3_i8p, encode_binary_dataarray1_rank3_r4p, encode_binary_dataarray1_rank3_r8p, encode_binary_dataarray1_rank4_i1p, encode_binary_dataarray1_rank4_i2p, encode_binary_dataarray1_rank4_i4p, encode_binary_dataarray1_rank4_i8p, encode_binary_dataarray1_rank4_r4p, encode_binary_dataarray1_rank4_r8p, encode_binary_dataarray3_rank1_i1p, encode_binary_dataarray3_rank1_i2p, encode_binary_dataarray3_rank1_i4p, encode_binary_dataarray3_rank1_i8p, encode_binary_dataarray3_rank1_r4p, encode_binary_dataarray3_rank1_r8p, encode_binary_dataarray3_rank3_i1p, encode_binary_dataarray3_rank3_i2p, encode_binary_dataarray3_rank3_i4p, encode_binary_dataarray3_rank3_i8p, encode_binary_dataarray3_rank3_r4p, encode_binary_dataarray3_rank3_r8p, encode_binary_dataarray6_rank1_i1p, encode_binary_dataarray6_rank1_i2p, encode_binary_dataarray6_rank1_i4p, encode_binary_dataarray6_rank1_i8p, encode_binary_dataarray6_rank1_r4p, encode_binary_dataarray6_rank1_r8p, encode_binary_dataarray6_rank3_i1p, encode_binary_dataarray6_rank3_i2p, encode_binary_dataarray6_rank3_i4p, encode_binary_dataarray6_rank3_i8p, encode_binary_dataarray6_rank3_r4p, encode_binary_dataarray6_rank3_r8p
write_dataarray1_rank1_i1p calls encode_binary_dataarray
write_dataarray1_rank1_i2p calls encode_binary_dataarray
write_dataarray1_rank1_i4p calls encode_binary_dataarray
write_dataarray1_rank1_i8p calls encode_binary_dataarray
write_dataarray1_rank1_r4p calls encode_binary_dataarray
write_dataarray1_rank1_r8p calls encode_binary_dataarray
write_dataarray1_rank2_i1p calls encode_binary_dataarray
write_dataarray1_rank2_i2p calls encode_binary_dataarray
write_dataarray1_rank2_i4p calls encode_binary_dataarray
write_dataarray1_rank2_i8p calls encode_binary_dataarray
write_dataarray1_rank2_r4p calls encode_binary_dataarray
write_dataarray1_rank2_r8p calls encode_binary_dataarray
write_dataarray1_rank3_i1p calls encode_binary_dataarray
write_dataarray1_rank3_i2p calls encode_binary_dataarray
write_dataarray1_rank3_i4p calls encode_binary_dataarray
write_dataarray1_rank3_i8p calls encode_binary_dataarray
write_dataarray1_rank3_r4p calls encode_binary_dataarray
write_dataarray1_rank3_r8p calls encode_binary_dataarray
write_dataarray1_rank4_i1p calls encode_binary_dataarray
write_dataarray1_rank4_i2p calls encode_binary_dataarray
write_dataarray1_rank4_i4p calls encode_binary_dataarray
write_dataarray1_rank4_i8p calls encode_binary_dataarray
write_dataarray1_rank4_r4p calls encode_binary_dataarray
write_dataarray1_rank4_r8p calls encode_binary_dataarray
write_dataarray3_rank1_i1p calls encode_binary_dataarray
write_dataarray3_rank1_i2p calls encode_binary_dataarray
write_dataarray3_rank1_i4p calls encode_binary_dataarray
write_dataarray3_rank1_i8p calls encode_binary_dataarray
write_dataarray3_rank1_r4p calls encode_binary_dataarray
write_dataarray3_rank1_r8p calls encode_binary_dataarray
write_dataarray3_rank3_i1p calls encode_binary_dataarray
write_dataarray3_rank3_i2p calls encode_binary_dataarray
write_dataarray3_rank3_i4p calls encode_binary_dataarray
write_dataarray3_rank3_i8p calls encode_binary_dataarray
write_dataarray3_rank3_r4p calls encode_binary_dataarray
write_dataarray3_rank3_r8p calls encode_binary_dataarray
write_dataarray6_rank1_i1p calls encode_binary_dataarray
write_dataarray6_rank1_i2p calls encode_binary_dataarray
write_dataarray6_rank1_i4p calls encode_binary_dataarray
write_dataarray6_rank1_i8p calls encode_binary_dataarray
write_dataarray6_rank1_r4p calls encode_binary_dataarray
write_dataarray6_rank1_r8p calls encode_binary_dataarray
write_dataarray6_rank3_i1p calls encode_binary_dataarray
write_dataarray6_rank3_i2p calls encode_binary_dataarray
write_dataarray6_rank3_i4p calls encode_binary_dataarray
write_dataarray6_rank3_i8p calls encode_binary_dataarray
write_dataarray6_rank3_r4p calls encode_binary_dataarray
write_dataarray6_rank3_r8p calls encode_binary_dataarray
write_dataarray_appended calls encode_binary_dataarray
finalize calls write_dataarray_appended
write_check calls write_dataarray, write_fielddata, write_geo
write_connectivity calls write_dataarray
write_data calls write_dataarray, write_geo, write_connectivity
write_fielddata1_rank0 calls write_dataarray
write_geo_rect_data3_rank1_r4p calls write_dataarray
write_geo_rect_data3_rank1_r8p calls write_dataarray
write_geo_strg_data1_rank2_r4p calls write_dataarray
write_geo_strg_data1_rank2_r8p calls write_dataarray
write_geo_strg_data1_rank4_r4p calls write_dataarray
write_geo_strg_data1_rank4_r8p calls write_dataarray
write_geo_strg_data3_rank1_r4p calls write_dataarray
write_geo_strg_data3_rank1_r8p calls write_dataarray
write_geo_strg_data3_rank3_r4p calls write_dataarray
write_geo_strg_data3_rank3_r8p calls write_dataarray
write_geo_unst_data1_rank2_r4p calls write_dataarray
write_geo_unst_data1_rank2_r8p calls write_dataarray
write_geo_unst_data3_rank1_r4p calls write_dataarray
write_geo_unst_data3_rank1_r8p calls write_dataarray
write_pvts calls write_dataarray
write_slave calls write_dataarray, write_fielddata, write_geo
write_vts calls write_dataarray, write_geo
vtk_fortran_write_vtr calls write_dataarray, write_fielddata, write_geo
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_volatile calls write_check, write_slave
vtk_fortran_write_vtm calls write_data
vtk_fortran_write_vts calls write_data
vtk_fortran_write_vtu calls write_data