b64_encode_up_a – Lib_VTK_IO
b64_encode_up_a Subroutine
20 statements
Source File
private pure subroutine b64_encode_up_a(up, code)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: up(1:)
character(len=:), intent(out), allocatable :: code
Calls
Called by
Source Code
   pure subroutine b64_encode_up_a(up, code)
   !< Encode an unlimited polymorphic array to base64.
   !<
   !<```fortran
   !< use befor64
   !< use penf
   !< character(len=:), allocatable :: code64
   !< call b64_encode_up(up=[0._R4P,-32.12_R4P], code=code64)
   !< print "(A)", code64
   !<```
   !=> AAAAAOF6AMI= <<<
   class(*),                      intent(in)  :: up(1:) !< Unlimited polymorphic variable to be encoded.
   character(len=:), allocatable, intent(out) :: code   !< Encoded array.
   select type(up)
   type is(real(R8P))
      call b64_encode_R8_a(n=up,code=code)
   type is(real(R4P))
      call b64_encode_R4_a(n=up,code=code)
   type is(integer(I8P))
      call b64_encode_I8_a(n=up,code=code)
   type is(integer(I4P))
      call b64_encode_I4_a(n=up,code=code)
   type is(integer(I2P))
      call b64_encode_I2_a(n=up,code=code)
   type is(integer(I1P))
      call b64_encode_I1_a(n=up,code=code)
   type is(character(*))
      call b64_encode_string_a(s=up,code=code)
   endselect
   endsubroutine b64_encode_up_a
Call graph
b64_encode_up_a calls b64_encode_i1_a, b64_encode_i2_a, b64_encode_i4_a, b64_encode_i8_a, b64_encode_r4_a, b64_encode_r8_a, b64_encode_string_a
b64_encode_i1_a calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_string_a calls byte_size, encode_bits
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p
b64_encode_up calls b64_encode_up_a, b64_encode_up