b64_decode_I2_a – Lib_VTK_IO
b64_decode_I2_a Subroutine
9 statements
Source File
private pure subroutine b64_decode_I2_a(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
integer(kind=I2P), intent(out) :: n(1:)
Calls
Called by
Contents
Source Code
b64_decode_I2_a
Source Code
   pure subroutine b64_decode_I2_a(code, n)
   !< Decode a base64 code into an array numbers (I2P).
   !<
   !<```fortran
   !< use befor64
   !< use penf
   !< integer(I2P) :: array_I2(1:2)
   !< call b64_decode(code='Nf/2/w==',n=array_I2)
   !< print "(L1)", str(n=array_I2)==str(n=[-203_I2P,-10_I2P])
   !<```
   !=> T <<<
   character(*), intent(in)  :: code    !< Encoded array.
   integer(I2P), intent(out) :: n(1:)   !< Array of numbers to be decoded.
   integer(I1P), allocatable :: nI1P(:) !< One byte integer array containing n.
   allocate(nI1P(1:size(n,dim=1)*BYI2P)) ; nI1P = 0_I1P
   call decode_bits(code=code,bits=nI1P)
   n = transfer(nI1P,n)
   endsubroutine b64_decode_I2_a
Call graph
b64_decode_i2_a calls decode_bits
b64_decode_up_a calls b64_decode_i2_a
b64_decode calls b64_decode_i2_a
volatile_doctest calls b64_decode
decode calls b64_decode
b64_decode_up calls b64_decode_up_a, b64_decode_up