create_tag_flat – Lib_VTK_IO
create_tag_flat Function
13 statements
Source File
private pure function create_tag_flat(name, attribute, attributes, attributes_stream, sanitize_attributes_value, content, indent, is_content_indented, is_self_closing) result(tag)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
character(len=*), intent(in), optional :: attribute(1:)
character(len=*), intent(in), optional :: attributes(1:,1:)
character(len=*), intent(in), optional :: attributes_stream
logical, intent(in), optional :: sanitize_attributes_value
character(len=*), intent(in), optional :: content
integer(kind=I4P), intent(in), optional :: indent
logical, intent(in), optional :: is_content_indented
logical, intent(in), optional :: is_self_closing
Return Value type(xml_tag)
Calls
Called by
Source Code
  pure function create_tag_flat(name, attribute, attributes, attributes_stream, sanitize_attributes_value, content, indent, &
                                is_content_indented, is_self_closing) result(tag)
  !< Return an instance of xml tag.
  !<
  !< Attributes are passed by array.
  character(*), intent(in)           :: name                      !< Tag name.
  character(*), intent(in), optional :: attribute(1:)             !< Attribute name/value pair [1:2].
  character(*), intent(in), optional :: attributes(1:,1:)         !< Attributes list of name/value pairs [1:2,1:].
  character(*), intent(in), optional :: attributes_stream         !< Attributes list of name/value pairs as single stream.
  logical,      intent(in), optional :: sanitize_attributes_value !< Sanitize attributes value.
  character(*), intent(in), optional :: content                   !< Tag value.
  integer(I4P), intent(in), optional :: indent                    !< Number of indent-white-spaces.
  logical,      intent(in), optional :: is_content_indented       !< Activate content indentation.
  logical,      intent(in), optional :: is_self_closing           !< The tag is self closing.
  type(xml_tag)                      :: tag                       !< XML tag.
  call tag%set(name=name, attribute=attribute, attributes=attributes, attributes_stream=attributes_stream, &
               sanitize_attributes_value=sanitize_attributes_value, content=content,                       &
               indent=indent, is_content_indented=is_content_indented, is_self_closing=is_self_closing)
  endfunction create_tag_flat
Call graph
create_tag_flat calls set
set calls add_multiple_attributes, add_single_attribute, add_stream_attributes
add_multiple_attributes calls add_single_attribute
add_single_attribute calls alloc_attributes
add_stream_attributes calls add_single_attribute, fill, partition, slice
xml_tag calls create_tag_flat