encode_ascii_dataarray1_rank4_R16P – Lib_VTK_IO
encode_ascii_dataarray1_rank4_R16P Function
31 statements
Source File
private function encode_ascii_dataarray1_rank4_R16P(x) result(code)
Arguments
Type Intent Optional Attributes Name
real(kind=R16P), intent(in) :: x(1:,1:,1:,1:)
Return Value character(len=:),allocatable
Calls
Contents
Source Code
encode_ascii_dataarray1_rank4_R16P
Source Code
  function encode_ascii_dataarray1_rank4_R16P(x) result(code)
  !< Encode (Base64) a dataarray with 1 components of rank 4 (R16P).
  real(R16P),      intent(in)   :: x(1:,1:,1:,1:) !< Data variable.
  character(len=:), allocatable :: code           !< Encoded base64 dataarray.
  integer(I4P)                  :: n1             !< Counter.
  integer(I4P)                  :: n2             !< Counter.
  integer(I4P)                  :: n3             !< Counter.
  integer(I4P)                  :: n4             !< Counter.
  integer(I4P)                  :: l              !< Length
  integer(I4P)                  :: sp             !< String pointer
  integer(I4P)                  :: size_n1        !< Dimension 1 size
  integer(I4P)                  :: size_n2        !< Dimension 2 size
  integer(I4P)                  :: size_n3        !< Dimension 3 size
  integer(I4P)                  :: size_n4        !< Dimension 4 size
  size_n1 = size(x, dim=1)
  size_n2 = size(x, dim=2)
  size_n3 = size(x, dim=3)
  size_n3 = size(x, dim=4)
  l = DR16P + 1
  sp = 0
  code = repeat(' ',l*size_n1*size_n2*size_n3*size_n4)
  do n4=1, size(x, dim=4)
    do n3=1, size(x, dim=3)
      do n2=1, size(x, dim=2)
        do n1=1, size(x, dim=1)
          code(sp+1:sp+l) = str(n=x(n1, n2, n3, n4))//' '
          sp = sp + l
        enddo
      enddo
    enddo
  enddo
  endfunction encode_ascii_dataarray1_rank4_R16P
Call graph
encode_ascii_dataarray1_rank4_r16p calls str
str calls strf_i1p, str_a_r4p, str_a_i2p, strf_r8p, strf_i4p, str_i4p, str_a_i8p, str_r4p, strf_r4p, str_i1p, str_a_i1p, strf_i2p, str_i2p, str_a_r8p, str_r8p, str_a_i4p, strf_i8p, str_i8p, str_bol
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_r4p calls compact_real_string
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_r8p calls compact_real_string
str_a_i4p calls str_i4p