encode_ascii_dataarray6_rank1_I1P – Lib_VTK_IO
encode_ascii_dataarray6_rank1_I1P Function
21 statements
Source File
private function encode_ascii_dataarray6_rank1_I1P(u, v, w, x, y, z) result(code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: u(1:)
integer(kind=I1P), intent(in) :: v(1:)
integer(kind=I1P), intent(in) :: w(1:)
integer(kind=I1P), intent(in) :: x(1:)
integer(kind=I1P), intent(in) :: y(1:)
integer(kind=I1P), intent(in) :: z(1:)
Return Value character(len=:),allocatable
Calls
Called by
Contents
Source Code
encode_ascii_dataarray6_rank1_I1P
Source Code
  function encode_ascii_dataarray6_rank1_I1P(u, v, w, x, y, z) result(code)
  !< Encode (Base64) a dataarray with 6 components of rank 1 (I1P).
  integer(I1P),    intent(in)   :: u(1:) !< U component.
  integer(I1P),    intent(in)   :: v(1:) !< V component.
  integer(I1P),    intent(in)   :: w(1:) !< W component.
  integer(I1P),    intent(in)   :: x(1:) !< X component.
  integer(I1P),    intent(in)   :: y(1:) !< Y component.
  integer(I1P),    intent(in)   :: z(1:) !< Z component.
  character(len=:), allocatable :: code  !< Encoded base64 dataarray.
  integer(I4P)                  :: n     !< Counter.
  integer(I4P)                  :: l     !< Length
  integer(I4P)                  :: sp    !< String pointer
  integer(I4P)                  :: size_n!< Dimension 1 size
  size_n = size(x, dim=1)
  l = DI1P*6 + 5
  sp = 0
  code = repeat(' ',l*size_n)
  do n=1, size_n
    code(sp+1:sp+l) = str(n=u(n))//' '//str(n=v(n))//' '//str(n=w(n))// &
                str(n=x(n))//' '//str(n=y(n))//' '//str(n=z(n))
    sp = sp + l
  enddo
  endfunction encode_ascii_dataarray6_rank1_I1P
Call graph
encode_ascii_dataarray6_rank1_i1p calls str
str calls str_i8p, str_a_r8p, str_r8p, str_a_i4p, strf_i2p, str_r4p, str_i1p, strf_i4p, str_a_r4p, strf_r4p, str_i2p, str_a_i2p, strf_i8p, str_bol, strf_r8p, str_i4p, str_a_i8p, strf_i1p, str_a_i1p
str_a_r8p calls str_r8p
str_r8p calls compact_real_string
str_a_i4p calls str_i4p
str_r4p calls compact_real_string
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_a_i1p calls str_i1p
encode_ascii_dataarray calls encode_ascii_dataarray6_rank1_i1p
write_dataarray1_rank1_i2p calls encode_ascii_dataarray
write_dataarray1_rank4_i8p calls encode_ascii_dataarray
write_dataarray3_rank1_i2p calls encode_ascii_dataarray
write_dataarray1_rank3_r8p calls encode_ascii_dataarray
write_dataarray6_rank1_r8p calls encode_ascii_dataarray
write_dataarray6_rank3_i8p calls encode_ascii_dataarray
write_dataarray1_rank2_r4p calls encode_ascii_dataarray
write_dataarray1_rank3_i4p calls encode_ascii_dataarray
write_dataarray1_rank4_i1p calls encode_ascii_dataarray
write_dataarray3_rank3_r4p calls encode_ascii_dataarray
write_dataarray6_rank1_i4p calls encode_ascii_dataarray
write_dataarray6_rank3_i1p calls encode_ascii_dataarray
write_dataarray1_rank1_i8p calls encode_ascii_dataarray
write_dataarray1_rank2_i2p calls encode_ascii_dataarray
write_dataarray1_rank4_r8p calls encode_ascii_dataarray
write_dataarray3_rank1_i8p calls encode_ascii_dataarray
write_dataarray6_rank3_r8p calls encode_ascii_dataarray
write_dataarray3_rank3_i2p calls encode_ascii_dataarray
write_dataarray1_rank1_i1p calls encode_ascii_dataarray
write_dataarray1_rank3_r4p calls encode_ascii_dataarray
write_dataarray1_rank4_i4p calls encode_ascii_dataarray
write_dataarray3_rank1_i1p calls encode_ascii_dataarray
write_dataarray6_rank1_r4p calls encode_ascii_dataarray
write_dataarray6_rank3_i4p calls encode_ascii_dataarray
write_dataarray1_rank1_r8p calls encode_ascii_dataarray
write_dataarray1_rank2_i8p calls encode_ascii_dataarray
write_dataarray1_rank3_i2p calls encode_ascii_dataarray
write_dataarray3_rank1_r8p calls encode_ascii_dataarray
write_dataarray3_rank3_i8p calls encode_ascii_dataarray
write_dataarray6_rank1_i2p calls encode_ascii_dataarray
write_dataarray1_rank1_i4p calls encode_ascii_dataarray
write_dataarray1_rank2_i1p calls encode_ascii_dataarray
write_dataarray1_rank4_r4p calls encode_ascii_dataarray
write_dataarray3_rank1_i4p calls encode_ascii_dataarray
write_dataarray3_rank3_i1p calls encode_ascii_dataarray
write_dataarray6_rank3_r4p calls encode_ascii_dataarray
write_dataarray1_rank2_r8p calls encode_ascii_dataarray
write_dataarray1_rank3_i8p calls encode_ascii_dataarray
write_dataarray1_rank4_i2p calls encode_ascii_dataarray
write_dataarray3_rank3_r8p calls encode_ascii_dataarray
write_dataarray6_rank1_i8p calls encode_ascii_dataarray
write_dataarray6_rank3_i2p calls encode_ascii_dataarray
write_dataarray1_rank1_r4p calls encode_ascii_dataarray
write_dataarray1_rank2_i4p calls encode_ascii_dataarray
write_dataarray1_rank3_i1p calls encode_ascii_dataarray
write_dataarray3_rank1_r4p calls encode_ascii_dataarray
write_dataarray3_rank3_i4p calls encode_ascii_dataarray
write_dataarray6_rank1_i1p calls encode_ascii_dataarray