initialize – Lib_VTK_IO
initialize Function
31 statements
Source File
private function initialize(self, format, filename, mesh_topology, nx1, nx2, ny1, ny2, nz1, nz2, is_volatile, mesh_kind) result(error)
Type Bound
xml_writer_appended
Arguments
Type Intent Optional Attributes Name
class(xml_writer_appended), intent(inout) :: self
character(len=*), intent(in) :: format
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: mesh_topology
integer(kind=I4P), intent(in), optional :: nx1
integer(kind=I4P), intent(in), optional :: nx2
integer(kind=I4P), intent(in), optional :: ny1
integer(kind=I4P), intent(in), optional :: ny2
integer(kind=I4P), intent(in), optional :: nz1
integer(kind=I4P), intent(in), optional :: nz2
logical, intent(in), optional :: is_volatile
character(len=*), intent(in), optional :: mesh_kind
Return Value integer(kind=I4P)
Calls
Source Code
  function initialize(self, format, filename, mesh_topology, nx1, nx2, ny1, ny2, nz1, nz2, &
                      is_volatile, mesh_kind) result(error)
  !< Initialize writer.
  class(xml_writer_appended), intent(inout)        :: self          !< Writer.
  character(*),               intent(in)           :: format        !< File format: ASCII.
  character(*),               intent(in)           :: filename      !< File name.
  character(*),               intent(in)           :: mesh_topology !< Mesh topology.
  integer(I4P),               intent(in), optional :: nx1           !< Initial node of x axis.
  integer(I4P),               intent(in), optional :: nx2           !< Final node of x axis.
  integer(I4P),               intent(in), optional :: ny1           !< Initial node of y axis.
  integer(I4P),               intent(in), optional :: ny2           !< Final node of y axis.
  integer(I4P),               intent(in), optional :: nz1           !< Initial node of z axis.
  integer(I4P),               intent(in), optional :: nz2           !< Final node of z axis.
  character(*),               intent(in), optional :: mesh_kind     !< Kind of mesh data: Float64, Float32, ecc.
  logical,                    intent(in), optional :: is_volatile   !< Flag to check volatile writer.
  integer(I4P)                                     :: error         !< Error status.
  self%topology = trim(adjustl(mesh_topology))
  self%format_ch = 'appended'
  self%encoding = format
  self%encoding = self%encoding%upper()
  select case(self%encoding%chars())
  case('RAW')
    self%encoding = 'raw'
  case('BINARY-APPENDED')
    self%encoding = 'base64'
  endselect
  call self%open_xml_file(filename=filename)
  call self%write_header_tag
  call self%write_topology_tag(nx1=nx1, nx2=nx2, ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2, mesh_kind=mesh_kind)
  self%ioffset = 0
  call self%open_scratch_file
  error = self%error
  endfunction initialize
Call graph
initialize calls chars, open_scratch_file, open_xml_file, upper, write_header_tag, write_topology_tag
write_topology_tag calls chars, str, write_end_tag, write_self_closing_tag, write_start_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
write_end_tag calls stringify
write_self_closing_tag calls stringify
write_start_tag calls stringify
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls chars, str, attributes, end_tag, is_allocated, self_closing_tag, start_tag
self_closing_tag calls attributes
start_tag calls attributes