partition – Lib_VTK_IO
partition Function
21 statements
Source File
private pure function partition(self, sep) result(partitions)
Type Bound
string
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
character(kind=CK, len=*), intent(in), optional :: sep
Return Value type(string), (1:3)
Called by
Source Code
   pure function partition(self, sep) result(partitions)
   !< Split string at separator and return the 3 parts (before, the separator and after).
   !<
   !<```fortran
   !< type(string) :: astring
   !< type(string) :: strings(3)
   !< logical      :: test_passed(3)
   !< astring = 'Hello WorLD!'
   !< strings = astring%partition(sep='lo Wo')
   !< test_passed(1) = (strings(1)//''=='Hel'.and.strings(2)//''=='lo Wo'.and.strings(3)//''=='rLD!')
   !< strings = astring%partition(sep='Hello')
   !< test_passed(2) = (strings(1)//''==''.and.strings(2)//''=='Hello'.and.strings(3)//''==' WorLD!')
   !< astring = 'Hello WorLD!'
   !< strings = astring%partition()
   !< test_passed(3) = (strings(1)//''=='Hello'.and.strings(2)//''==' '.and.strings(3)//''=='WorLD!')
   !< print '(L1)', all(test_passed)
   !<```
   !=> T <<<
   class(string),             intent(in)           :: self            !< The string.
   character(kind=CK, len=*), intent(in), optional :: sep             !< Separator.
   type(string)                                    :: partitions(1:3) !< Partions: before the separator, the separator itsels and
                                                                      !< after the separator.
   character(kind=CK, len=:), allocatable          :: sep_            !< Separator, default value.
   integer                                         :: c               !< Character counter.
   if (allocated(self%raw)) then
      sep_ = SPACE ; if (present(sep)) sep_ = sep
      partitions(1) = self
      partitions(2) = sep_
      partitions(3) = ''
      if (len(sep_)>=len(self%raw)) return
      c = index(self%raw, sep_)
      if (c>0) then
         partitions(1)%raw = self%raw(1:c-1)
         partitions(2)%raw = self%raw(c:c+len(sep_)-1)
         partitions(3)%raw = self%raw(c+len(sep_):)
      endif
   endif
   endfunction partition
Call graph
add_stream_attributes calls partition
split calls partition
volatile_doctest calls partition, split, write_file, startcase, split_chunked, snakecase, camelcase, glob
camelcase calls split
glob_string calls split
set calls add_stream_attributes
snakecase calls split
split_chunked calls split
startcase calls split
write_lines calls split
write_parallel_block_files_string calls split
stringifor_test_csv_naive_parser calls split
stringifor_test_parse_large_csv calls split, split_chunked
glob calls glob_string, glob_character
create_tag_flat calls set
create_tag_nested calls set
parse_from_string calls set
write_file calls write_lines
foxy_test_add_attributes calls add_attributes
foxy_test_create_tag calls set
xml_tag calls create_tag_flat, create_tag_nested
glob_character calls glob
parse calls parse_from_string
parse_scratch_files calls write_parallel_block_files, write_block
write_block_array calls write_parallel_block_files
write_block_string calls write_parallel_block_files
finalize calls parse_scratch_files
foxy_test_delete_tag calls parse
foxy_test_parse_file_simple calls parse
foxy_test_parse_string_nested_tags calls parse
foxy_test_parse_string_simple calls parse
foxy_test_write_tag calls parse
initialize calls finalize
vtk_fortran_write_vtm calls write_block