penf_init – Lib_VTK_IO
penf_init Subroutine
4 statements
Source File
public subroutine penf_init()
Arguments
None
Calls
Called by
Source Code
   subroutine penf_init()
   !< Initialize PENF's variables that are not initialized into the definition specification.
   !<
   !<```fortran
   !< use penf
   !< call penf_init
   !< print FI1P, BYR4P
   !<```
   !=> 4 <<<
   call check_endian
   is_initialized = .true.
   endsubroutine penf_init
Call graph
penf_init calls check_endian
b64_init calls penf_init
initialize calls penf_init, b64_init
penf_print calls penf_init
volatile_doctest calls penf_init, penf_print, b64_init
write_check calls initialize
write_pvts calls initialize
write_slave calls initialize
write_vts calls initialize
vtk_fortran_write_vtm calls initialize
vtk_fortran_write_vtr calls initialize
vtk_fortran_write_vts calls initialize
vtk_fortran_write_vtu calls initialize
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_volatile calls write_check, write_slave