str_ascii_default – Lib_VTK_IO
str_ascii_default Function
5 statements
Source File
private pure function str_ascii_default(input) result(output)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input
Return Value character(kind=ASCII,len=:),allocatable
Called by
Contents
Source Code
str_ascii_default
Source Code
   pure function str_ascii_default(input) result(output)
   !< Convert string of default kind to ASCII string.
   !<
   !<```fortran
   !< use penf
   !< character(len=:, kind=ASCII), allocatable :: string
   !< string = str_ascii('I was DEFAULT kind, but now I am ASCII')
   !< print "(A)", string
   !<```
   !=> I was DEFAULT kind, but now I am ASCII <<<
   character(len=*), intent(in)              :: input  !< Input string of default kind.
   character(len=:, kind=ASCII), allocatable :: output !< Output string of ASCII kind.
   output = input
   endfunction str_ascii_default
Call graph
str_ascii calls str_ascii_default
volatile_doctest calls str_ascii