stringify_recursive – Lib_VTK_IO
stringify_recursive Subroutine
17 statements
Source File
private pure recursive subroutine stringify_recursive(self, tag, is_done, tag_string)
Type Bound
xml_file
Arguments
Type Intent Optional Attributes Name
class(xml_file), intent(in) :: self
type(xml_tag), intent(in) :: tag
logical, intent(inout) :: is_done(:)
character(len=:), intent(inout), allocatable :: tag_string
Calls
Called by
Source Code
   recursive pure subroutine stringify_recursive(self, tag, is_done, tag_string)
   !< Convert recursively tags with children into a string.
   class(xml_file),               intent(in)    :: self       !< XML file.
   type(xml_tag),                 intent(in)    :: tag        !< XML tag with children.
   logical,                       intent(inout) :: is_done(:) !< List of stringified tags.
   character(len=:), allocatable, intent(inout) :: tag_string !< Output string containing the current tag.
   integer(I4P)                                 :: t          !< Counter.
   if (tag%children_number>0) then
      tag_string = tag_string//new_line('a')//tag%stringify(is_indented=.true., only_start=.true.)
      do t=1, tag%children_number
         call self%stringify_recursive(tag=self%tag(tag%child_id(t)), is_done=is_done, tag_string=tag_string)
         is_done(tag%child_id(t)) = .true.
      enddo
      tag_string = tag_string//new_line('a')//tag%stringify(is_indented=.true., only_end=.true.)
   else
      tag_string = tag_string//new_line('a')//tag%stringify(is_indented=.true.)
   endif
   endsubroutine stringify_recursive
Call graph
stringify_recursive calls stringify_recursive, stringify
stringify calls str, attributes, chars, end_tag, is_allocated, self_closing_tag, start_tag, stringify_recursive
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
self_closing_tag calls attributes
start_tag calls attributes
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
foxy_test_add_tag calls stringify
foxy_test_delete_tag calls stringify
foxy_test_parse_file_simple calls stringify
foxy_test_parse_string_nested_tags calls stringify
foxy_test_parse_string_simple calls stringify
foxy_test_write_tag calls stringify