style_index – Lib_VTK_IO
style_index Function
12 statements
Source File
private elemental function style_index(style)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: style
Return Value integer(kind=int32)
Called by
Contents
Source Code
style_index
Source Code
   elemental function style_index(style)
   !< Return the array-index corresponding to the queried style.
   character(len=*), intent(in) :: style       !< Style definition.
   integer(int32)               :: style_index !< Index into the styles array.
   integer(int32)               :: s           !< Counter.
   style_index = 0
   do s=1, size(STYLES, dim=2)
      if (trim(STYLES(1, s))==trim(adjustl(style))) then
         style_index = s
         exit
      endif
   enddo
   endfunction style_index
Call graph
colorize_ascii calls style_index
colorize_default calls style_index
colorize_ucs4 calls style_index
colorize calls colorize_default
colorize_str calls colorize
styles_samples calls colorize
face_test_colors calls colorize
face_test_styles calls colorize
colors_samples calls colorize
face_test_basic calls styles_samples, colors_samples