write_pvts – Lib_VTK_IO
write_pvts Subroutine
13 statements
Source File
subroutine write_pvts(filename, parts_filename)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: parts_filename(:)
Calls
Called by
Source Code
   subroutine write_pvts(filename, parts_filename)
   !< Write PVTS.
   character(*), intent(in) :: filename          !< Output file name.
   character(*), intent(in) :: parts_filename(:) !< Parts file name.
   type(pvtk_file)          :: a_pvtk_file       !< A parallel (partioned) VTK file.
   integer(I4P)             :: error             !< Status error.
   error = a_pvtk_file%initialize(filename=filename, mesh_topology='PStructuredGrid', mesh_kind="Float64", &
                                  nx1=nx1, nx2=nx2, ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2)
   error = a_pvtk_file%xml_writer%write_dataarray(location='node', action='open')
   error = a_pvtk_file%xml_writer%write_parallel_dataarray(data_name='int32_scalar', &
                                                           data_type='Int32', &
                                                           number_of_components=1)
   error = a_pvtk_file%xml_writer%write_dataarray(location='node', action='close')
   error = a_pvtk_file%xml_writer%write_parallel_geo(source=parts_filename(1), &
                                                     nx1=nx1, nx2=nx2_p(1), ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2)
   error = a_pvtk_file%xml_writer%write_parallel_geo(source=parts_filename(2), &
                                                     nx1=nx2_p(1), nx2=nx2_p(2), ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2)
   error = a_pvtk_file%finalize()
   endsubroutine write_pvts
Call graph
write_pvts calls write_dataarray, finalize, initialize, write_parallel_dataarray, write_parallel_geo
finalize calls finalize
initialize calls initialize, b64_init, penf_init
write_parallel_dataarray calls str, chars, write_self_closing_tag
write_parallel_geo calls str, chars, write_self_closing_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
b64_init calls penf_init
penf_init calls check_endian
write_dataarray1_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray_location_tag calls chars, upper, write_end_tag, write_start_tag
write_self_closing_tag calls stringify
encode_binary_dataarray calls encode_binary_dataarray1_rank1_i1p, encode_binary_dataarray1_rank1_i2p, encode_binary_dataarray1_rank1_i4p, encode_binary_dataarray1_rank1_i8p, encode_binary_dataarray1_rank1_r4p, encode_binary_dataarray1_rank1_r8p, encode_binary_dataarray1_rank2_i1p, encode_binary_dataarray1_rank2_i2p, encode_binary_dataarray1_rank2_i4p, encode_binary_dataarray1_rank2_i8p, encode_binary_dataarray1_rank2_r4p, encode_binary_dataarray1_rank2_r8p, encode_binary_dataarray1_rank3_i1p, encode_binary_dataarray1_rank3_i2p, encode_binary_dataarray1_rank3_i4p, encode_binary_dataarray1_rank3_i8p, encode_binary_dataarray1_rank3_r4p, encode_binary_dataarray1_rank3_r8p, encode_binary_dataarray1_rank4_i1p, encode_binary_dataarray1_rank4_i2p, encode_binary_dataarray1_rank4_i4p, encode_binary_dataarray1_rank4_i8p, encode_binary_dataarray1_rank4_r4p, encode_binary_dataarray1_rank4_r8p, encode_binary_dataarray3_rank1_i1p, encode_binary_dataarray3_rank1_i2p, encode_binary_dataarray3_rank1_i4p, encode_binary_dataarray3_rank1_i8p, encode_binary_dataarray3_rank1_r4p, encode_binary_dataarray3_rank1_r8p, encode_binary_dataarray3_rank3_i1p, encode_binary_dataarray3_rank3_i2p, encode_binary_dataarray3_rank3_i4p, encode_binary_dataarray3_rank3_i8p, encode_binary_dataarray3_rank3_r4p, encode_binary_dataarray3_rank3_r8p, encode_binary_dataarray6_rank1_i1p, encode_binary_dataarray6_rank1_i2p, encode_binary_dataarray6_rank1_i4p, encode_binary_dataarray6_rank1_i8p, encode_binary_dataarray6_rank1_r4p, encode_binary_dataarray6_rank1_r8p, encode_binary_dataarray6_rank3_i1p, encode_binary_dataarray6_rank3_i2p, encode_binary_dataarray6_rank3_i4p, encode_binary_dataarray6_rank3_i8p, encode_binary_dataarray6_rank3_r4p, encode_binary_dataarray6_rank3_r8p
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls str, chars, attributes, end_tag, is_allocated, self_closing_tag, start_tag
write_dataarray_tag calls str, chars, write_tag
write_end_tag calls stringify
write_start_tag calls stringify
encode_binary_dataarray1_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_i4p calls b64_encode
encode_binary_dataarray1_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i4p calls b64_encode
encode_binary_dataarray1_rank2_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i4p calls b64_encode
encode_binary_dataarray1_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i4p calls b64_encode
encode_binary_dataarray1_rank4_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_r8p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i4p calls b64_encode
encode_binary_dataarray3_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i4p calls b64_encode
encode_binary_dataarray3_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_r8p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i4p calls b64_encode
encode_binary_dataarray6_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i4p calls b64_encode
encode_binary_dataarray6_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_r8p calls b64_encode, pack_data
self_closing_tag calls attributes
start_tag calls attributes
write_tag calls stringify
b64_encode calls b64_encode_i1, b64_encode_i1_a, b64_encode_i2, b64_encode_i2_a, b64_encode_i4, b64_encode_i4_a, b64_encode_i8, b64_encode_i8_a, b64_encode_r4, b64_encode_r4_a, b64_encode_r8, b64_encode_r8_a, b64_encode_string, b64_encode_string_a
pack_data calls pack_data_i1_i2, pack_data_i1_i4, pack_data_i1_i8, pack_data_i1_r4, pack_data_i1_r8, pack_data_i2_i1, pack_data_i2_i4, pack_data_i2_i8, pack_data_i2_r4, pack_data_i2_r8, pack_data_i4_i1, pack_data_i4_i2, pack_data_i4_i8, pack_data_i4_r4, pack_data_i4_r8, pack_data_i8_i1, pack_data_i8_i2, pack_data_i8_i4, pack_data_i8_r4, pack_data_i8_r8, pack_data_r4_i1, pack_data_r4_i2, pack_data_r4_i4, pack_data_r4_i8, pack_data_r4_r8, pack_data_r8_i1, pack_data_r8_i2, pack_data_r8_i4, pack_data_r8_i8, pack_data_r8_r4
b64_encode_i1 calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_string calls byte_size, encode_bits
b64_encode_string_a calls byte_size, encode_bits
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p
vtk_fortran_write_pvts calls write_pvts