write_dataarray1_rank3_R4P – Lib_VTK_IO
write_dataarray1_rank3_R4P Function
19 statements
Source File
private function write_dataarray1_rank3_R4P(self, data_name, x, one_component, is_tuples) result(error)
Arguments
Type Intent Optional Attributes Name
class(xml_writer_ascii_local), intent(inout) :: self
character, intent(in) :: data_name
real(kind=R4P), intent(in) :: x(1:,1:,1:)
logical, intent(in), optional :: one_component
logical, intent(in), optional :: is_tuples
Return Value integer(kind=I4P)
Calls
Contents
Source Code
write_dataarray1_rank3_R4P
Source Code
  function write_dataarray1_rank3_R4P(self, data_name, x, one_component, is_tuples) result(error)
  !< Write `<DataArray... NumberOfComponents="n"...>...</DataArray>` tag (R4P).
  class(xml_writer_ascii_local), intent(inout)        :: self          !< Writer.
  character(*),                  intent(in)           :: data_name     !< Data name.
  real(R4P),                     intent(in)           :: x(1:,1:,1:)   !< Data variable.
  logical,                       intent(in), optional :: one_component !< Force one component.
  logical,                       intent(in), optional :: is_tuples     !< Use "NumberOfTuples" instead of "NumberOfComponents".
  integer(I4P)                                        :: error         !< Error status.
  character(len=:), allocatable                       :: data_type     !< Data type.
  integer(I4P)                                        :: n_components  !< Number of components.
  character(len=:), allocatable                       :: code          !< Data variable encoded, ascii or Base64 codec.
  data_type = 'Float32'
  n_components = size(x, dim=1)
  if (present(one_component)) then
    if (one_component) n_components = 1
  endif
  code = encode_ascii_dataarray(x=x)
  call self%write_dataarray_tag(data_type=data_type, number_of_components=n_components, data_name=data_name, data_content=code, &
                                is_tuples=is_tuples)
  error = self%error
  endfunction write_dataarray1_rank3_R4P
Call graph
write_dataarray1_rank3_r4p calls encode_ascii_dataarray
encode_ascii_dataarray calls encode_ascii_dataarray1_rank1_i8p, encode_ascii_dataarray1_rank3_i2p, encode_ascii_dataarray6_rank1_r8p, encode_ascii_dataarray1_rank4_i1p, encode_ascii_dataarray1_rank2_i4p, encode_ascii_dataarray6_rank3_i1p, encode_ascii_dataarray1_rank1_i1p, encode_ascii_dataarray1_rank4_r8p, encode_ascii_dataarray3_rank1_r4p, encode_ascii_dataarray3_rank3_i8p, encode_ascii_dataarray6_rank1_i4p, encode_ascii_dataarray1_rank1_r8p, encode_ascii_dataarray1_rank2_r4p, encode_ascii_dataarray1_rank3_i8p, encode_ascii_dataarray1_rank4_i4p, encode_ascii_dataarray3_rank1_i2p, encode_ascii_dataarray6_rank3_i4p, encode_ascii_dataarray3_rank3_i1p, encode_ascii_dataarray1_rank1_i4p, encode_ascii_dataarray1_rank2_i2p, encode_ascii_dataarray1_rank3_i1p, encode_ascii_dataarray3_rank3_r8p, encode_ascii_dataarray6_rank1_r4p, encode_ascii_dataarray1_rank3_r8p, encode_ascii_dataarray1_rank4_r4p, encode_ascii_dataarray3_rank1_i8p, encode_ascii_dataarray3_rank3_i4p, encode_ascii_dataarray6_rank1_i2p, encode_ascii_dataarray6_rank3_r4p, encode_ascii_dataarray1_rank1_r4p, encode_ascii_dataarray1_rank2_i8p, encode_ascii_dataarray1_rank3_i4p, encode_ascii_dataarray1_rank4_i2p, encode_ascii_dataarray3_rank1_i1p, encode_ascii_dataarray6_rank3_r8p, encode_ascii_dataarray6_rank3_i2p, encode_ascii_dataarray1_rank1_i2p, encode_ascii_dataarray1_rank2_i1p, encode_ascii_dataarray3_rank1_r8p, encode_ascii_dataarray3_rank3_r4p, encode_ascii_dataarray6_rank1_i8p, encode_ascii_dataarray1_rank2_r8p, encode_ascii_dataarray1_rank3_r4p, encode_ascii_dataarray1_rank4_i8p, encode_ascii_dataarray3_rank1_i4p, encode_ascii_dataarray3_rank3_i2p, encode_ascii_dataarray6_rank1_i1p, encode_ascii_dataarray6_rank3_i8p
encode_ascii_dataarray1_rank1_i8p calls str
encode_ascii_dataarray1_rank3_i2p calls str
encode_ascii_dataarray6_rank1_r8p calls str
encode_ascii_dataarray1_rank4_i1p calls str
encode_ascii_dataarray1_rank2_i4p calls str
encode_ascii_dataarray6_rank3_i1p calls str
encode_ascii_dataarray1_rank1_i1p calls str
encode_ascii_dataarray1_rank4_r8p calls str
encode_ascii_dataarray3_rank1_r4p calls str
encode_ascii_dataarray3_rank3_i8p calls str
encode_ascii_dataarray6_rank1_i4p calls str
encode_ascii_dataarray1_rank1_r8p calls str
encode_ascii_dataarray1_rank2_r4p calls str
encode_ascii_dataarray1_rank3_i8p calls str
encode_ascii_dataarray1_rank4_i4p calls str
encode_ascii_dataarray3_rank1_i2p calls str
encode_ascii_dataarray6_rank3_i4p calls str
encode_ascii_dataarray3_rank3_i1p calls str
encode_ascii_dataarray1_rank1_i4p calls str
encode_ascii_dataarray1_rank2_i2p calls str
encode_ascii_dataarray1_rank3_i1p calls str
encode_ascii_dataarray3_rank3_r8p calls str
encode_ascii_dataarray6_rank1_r4p calls str
encode_ascii_dataarray1_rank3_r8p calls str
encode_ascii_dataarray1_rank4_r4p calls str
encode_ascii_dataarray3_rank1_i8p calls str
encode_ascii_dataarray3_rank3_i4p calls str
encode_ascii_dataarray6_rank1_i2p calls str
encode_ascii_dataarray6_rank3_r4p calls str
encode_ascii_dataarray1_rank1_r4p calls str
encode_ascii_dataarray1_rank2_i8p calls str
encode_ascii_dataarray1_rank3_i4p calls str
encode_ascii_dataarray1_rank4_i2p calls str
encode_ascii_dataarray3_rank1_i1p calls str
encode_ascii_dataarray6_rank3_r8p calls str
encode_ascii_dataarray6_rank3_i2p calls str
encode_ascii_dataarray1_rank1_i2p calls str
encode_ascii_dataarray1_rank2_i1p calls str
encode_ascii_dataarray3_rank1_r8p calls str
encode_ascii_dataarray3_rank3_r4p calls str
encode_ascii_dataarray6_rank1_i8p calls str
encode_ascii_dataarray1_rank2_r8p calls str
encode_ascii_dataarray1_rank3_r4p calls str
encode_ascii_dataarray1_rank4_i8p calls str
encode_ascii_dataarray3_rank1_i4p calls str
encode_ascii_dataarray3_rank3_i2p calls str
encode_ascii_dataarray6_rank1_i1p calls str
encode_ascii_dataarray6_rank3_i8p calls str
str calls strf_i1p, str_a_r4p, str_a_i2p, strf_r8p, strf_i4p, str_i4p, str_a_i8p, str_r4p, strf_r4p, str_i1p, str_a_i1p, strf_i2p, str_i2p, str_a_r8p, str_r8p, str_a_i4p, strf_i8p, str_i8p, str_bol
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_r4p calls compact_real_string
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_r8p calls compact_real_string
str_a_i4p calls str_i4p