write_on_scratch_dataarray6_rank2_I8P – Lib_VTK_IO
write_on_scratch_dataarray6_rank2_I8P Function
13 statements
Source File
private function write_on_scratch_dataarray6_rank2_I8P(self, u, v, w, x, y, z) result(n_byte)
Type Bound
xml_writer_appended
Arguments
Type Intent Optional Attributes Name
class(xml_writer_appended), intent(inout) :: self
integer(kind=I8P), intent(in) :: u(1:,1:)
integer(kind=I8P), intent(in) :: v(1:,1:)
integer(kind=I8P), intent(in) :: w(1:,1:)
integer(kind=I8P), intent(in) :: x(1:,1:)
integer(kind=I8P), intent(in) :: y(1:,1:)
integer(kind=I8P), intent(in) :: z(1:,1:)
Return Value integer(kind=I4P)
Calls
Called by
Source Code
  function write_on_scratch_dataarray6_rank2_I8P(self, u, v, w, x, y, z) result(n_byte)
  !< Write a dataarray with 6 components of rank 2 (I8P).
  class(xml_writer_appended), intent(inout) :: self     !< Writer.
  integer(I8P),               intent(in)    :: u(1:,1:) !< U component.
  integer(I8P),               intent(in)    :: v(1:,1:) !< V component.
  integer(I8P),               intent(in)    :: w(1:,1:) !< W component.
  integer(I8P),               intent(in)    :: x(1:,1:) !< X component.
  integer(I8P),               intent(in)    :: y(1:,1:) !< Y component.
  integer(I8P),               intent(in)    :: z(1:,1:) !< Z component.
  integer(I4P)                              :: n_byte   !< Number of bytes
  integer(I4P)                              :: n1       !< Counter.
  integer(I4P)                              :: n2       !< Counter.
  n_byte = self%write_on_scratch_dataarray(x=[((u(n1,n2), v(n1,n2), w(n1,n2), &
                                                x(n1,n2), y(n1,n2), z(n1,n2), n1=1,size(x, dim=1)),n2=1,size(x, dim=2))])
  endfunction write_on_scratch_dataarray6_rank2_I8P
Call graph
write_on_scratch_dataarray6_rank2_i8p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank1_i1p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank1_i2p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank1_i4p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank1_i8p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank1_r4p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank1_r8p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank2_i1p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank2_i2p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank2_i4p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank2_i8p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank2_r4p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank2_r8p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank3_i1p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank3_i2p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank3_i4p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank3_i8p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank3_r4p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank3_r8p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank1_i1p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank1_i2p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank1_i4p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank1_i8p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank1_r4p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank1_r8p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank2_i1p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank2_i2p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank2_i4p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank2_r4p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank2_r8p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank3_i1p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank3_i2p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank3_i4p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank3_i8p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank3_r4p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank3_r8p calls write_on_scratch_dataarray
write_dataarray1_rank1_i1p calls write_on_scratch_dataarray
write_dataarray1_rank1_i2p calls write_on_scratch_dataarray
write_dataarray1_rank1_i4p calls write_on_scratch_dataarray
write_dataarray1_rank1_i8p calls write_on_scratch_dataarray
write_dataarray1_rank1_r4p calls write_on_scratch_dataarray
write_dataarray1_rank1_r8p calls write_on_scratch_dataarray
write_dataarray1_rank2_i1p calls write_on_scratch_dataarray
write_dataarray1_rank2_i2p calls write_on_scratch_dataarray
write_dataarray1_rank2_i4p calls write_on_scratch_dataarray
write_dataarray1_rank2_i8p calls write_on_scratch_dataarray
write_dataarray1_rank2_r4p calls write_on_scratch_dataarray
write_dataarray1_rank2_r8p calls write_on_scratch_dataarray
write_dataarray1_rank3_i1p calls write_on_scratch_dataarray
write_dataarray1_rank3_i2p calls write_on_scratch_dataarray
write_dataarray1_rank3_i4p calls write_on_scratch_dataarray
write_dataarray1_rank3_i8p calls write_on_scratch_dataarray
write_dataarray1_rank3_r4p calls write_on_scratch_dataarray
write_dataarray1_rank3_r8p calls write_on_scratch_dataarray
write_dataarray1_rank4_i1p calls write_on_scratch_dataarray
write_dataarray1_rank4_i2p calls write_on_scratch_dataarray
write_dataarray1_rank4_i4p calls write_on_scratch_dataarray
write_dataarray1_rank4_i8p calls write_on_scratch_dataarray
write_dataarray1_rank4_r4p calls write_on_scratch_dataarray
write_dataarray1_rank4_r8p calls write_on_scratch_dataarray
write_dataarray3_rank1_i1p calls write_on_scratch_dataarray
write_dataarray3_rank1_i2p calls write_on_scratch_dataarray
write_dataarray3_rank1_i4p calls write_on_scratch_dataarray
write_dataarray3_rank1_i8p calls write_on_scratch_dataarray
write_dataarray3_rank1_r4p calls write_on_scratch_dataarray
write_dataarray3_rank1_r8p calls write_on_scratch_dataarray
write_dataarray3_rank3_i1p calls write_on_scratch_dataarray
write_dataarray3_rank3_i2p calls write_on_scratch_dataarray
write_dataarray3_rank3_i4p calls write_on_scratch_dataarray
write_dataarray3_rank3_i8p calls write_on_scratch_dataarray
write_dataarray3_rank3_r4p calls write_on_scratch_dataarray
write_dataarray3_rank3_r8p calls write_on_scratch_dataarray
write_dataarray6_rank1_i1p calls write_on_scratch_dataarray
write_dataarray6_rank1_i2p calls write_on_scratch_dataarray
write_dataarray6_rank1_i4p calls write_on_scratch_dataarray
write_dataarray6_rank1_i8p calls write_on_scratch_dataarray
write_dataarray6_rank1_r4p calls write_on_scratch_dataarray
write_dataarray6_rank1_r8p calls write_on_scratch_dataarray
write_dataarray6_rank3_i1p calls write_on_scratch_dataarray
write_dataarray6_rank3_i2p calls write_on_scratch_dataarray
write_dataarray6_rank3_i4p calls write_on_scratch_dataarray
write_dataarray6_rank3_i8p calls write_on_scratch_dataarray
write_dataarray6_rank3_r4p calls write_on_scratch_dataarray
write_dataarray6_rank3_r8p calls write_on_scratch_dataarray