write_tag – Lib_VTK_IO
write_tag Subroutine
12 statements
Source File
private subroutine write_tag(self, name, attributes, content)
Type Bound
xml_writer_abstract
Arguments
Type Intent Optional Attributes Name
class(xml_writer_abstract), intent(inout) :: self
character(len=*), intent(in) :: name
character(len=*), intent(in), optional :: attributes
character(len=*), intent(in), optional :: content
Calls
Called by
Source Code
   subroutine write_tag(self, name, attributes, content)
   !< Write `<tag_name...>...</tag_name>` tag.
   class(xml_writer_abstract), intent(inout)        :: self       !< Writer.
   character(*),               intent(in)           :: name       !< Tag name.
   character(*),               intent(in), optional :: attributes !< Tag attributes.
   character(*),               intent(in), optional :: content    !< Tag content.
   self%tag = xml_tag(name=name, attributes_stream=attributes, sanitize_attributes_value=.true., content=content, &
                      indent=self%indent)
   if (.not.self%is_volatile) then
      call self%tag%write(unit=self%xml, iostat=self%error, is_indented=.true., is_content_indented=.true., end_record=end_rec)
   else
      self%xml_volatile = self%xml_volatile//self%tag%stringify(is_indented=.true., is_content_indented=.true.)//end_rec
   endif
   endsubroutine write_tag
Call graph
write_tag calls stringify
stringify calls chars, end_tag, is_allocated, self_closing_tag, start_tag
self_closing_tag calls attributes
start_tag calls attributes
write_dataarray_tag calls write_tag
write_dataarray1_rank1_i1p calls write_dataarray_tag
write_dataarray1_rank1_i2p calls write_dataarray_tag
write_dataarray1_rank1_i4p calls write_dataarray_tag
write_dataarray1_rank1_i8p calls write_dataarray_tag
write_dataarray1_rank1_r4p calls write_dataarray_tag
write_dataarray1_rank1_r8p calls write_dataarray_tag
write_dataarray1_rank2_i1p calls write_dataarray_tag
write_dataarray1_rank2_i2p calls write_dataarray_tag
write_dataarray1_rank2_i4p calls write_dataarray_tag
write_dataarray1_rank2_i8p calls write_dataarray_tag
write_dataarray1_rank2_r4p calls write_dataarray_tag
write_dataarray1_rank2_r8p calls write_dataarray_tag
write_dataarray1_rank3_i1p calls write_dataarray_tag
write_dataarray1_rank3_i2p calls write_dataarray_tag
write_dataarray1_rank3_i4p calls write_dataarray_tag
write_dataarray1_rank3_i8p calls write_dataarray_tag
write_dataarray1_rank3_r4p calls write_dataarray_tag
write_dataarray1_rank3_r8p calls write_dataarray_tag
write_dataarray1_rank4_i1p calls write_dataarray_tag
write_dataarray1_rank4_i2p calls write_dataarray_tag
write_dataarray1_rank4_i4p calls write_dataarray_tag
write_dataarray1_rank4_i8p calls write_dataarray_tag
write_dataarray1_rank4_r4p calls write_dataarray_tag
write_dataarray1_rank4_r8p calls write_dataarray_tag
write_dataarray3_rank1_i1p calls write_dataarray_tag
write_dataarray3_rank1_i2p calls write_dataarray_tag
write_dataarray3_rank1_i4p calls write_dataarray_tag
write_dataarray3_rank1_i8p calls write_dataarray_tag
write_dataarray3_rank1_r4p calls write_dataarray_tag
write_dataarray3_rank1_r8p calls write_dataarray_tag
write_dataarray3_rank3_i1p calls write_dataarray_tag
write_dataarray3_rank3_i2p calls write_dataarray_tag
write_dataarray3_rank3_i4p calls write_dataarray_tag
write_dataarray3_rank3_i8p calls write_dataarray_tag
write_dataarray3_rank3_r4p calls write_dataarray_tag
write_dataarray3_rank3_r8p calls write_dataarray_tag
write_dataarray6_rank1_i1p calls write_dataarray_tag
write_dataarray6_rank1_i2p calls write_dataarray_tag
write_dataarray6_rank1_i4p calls write_dataarray_tag
write_dataarray6_rank1_i8p calls write_dataarray_tag
write_dataarray6_rank1_r4p calls write_dataarray_tag
write_dataarray6_rank1_r8p calls write_dataarray_tag
write_dataarray6_rank3_i1p calls write_dataarray_tag
write_dataarray6_rank3_i2p calls write_dataarray_tag
write_dataarray6_rank3_i4p calls write_dataarray_tag
write_dataarray6_rank3_i8p calls write_dataarray_tag
write_dataarray6_rank3_r4p calls write_dataarray_tag
write_dataarray6_rank3_r8p calls write_dataarray_tag
write_check calls write_dataarray, write_fielddata, write_geo
write_connectivity calls write_dataarray
write_data calls write_dataarray, write_connectivity, write_geo
write_fielddata1_rank0 calls write_dataarray
write_geo_rect_data3_rank1_r4p calls write_dataarray
write_geo_rect_data3_rank1_r8p calls write_dataarray
write_geo_strg_data1_rank2_r4p calls write_dataarray
write_geo_strg_data1_rank2_r8p calls write_dataarray
write_geo_strg_data1_rank4_r4p calls write_dataarray
write_geo_strg_data1_rank4_r8p calls write_dataarray
write_geo_strg_data3_rank1_r4p calls write_dataarray
write_geo_strg_data3_rank1_r8p calls write_dataarray
write_geo_strg_data3_rank3_r4p calls write_dataarray
write_geo_strg_data3_rank3_r8p calls write_dataarray
write_geo_unst_data1_rank2_r4p calls write_dataarray
write_geo_unst_data1_rank2_r8p calls write_dataarray
write_geo_unst_data3_rank1_r4p calls write_dataarray
write_geo_unst_data3_rank1_r8p calls write_dataarray
write_pvts calls write_dataarray
write_slave calls write_dataarray, write_fielddata, write_geo
write_vts calls write_dataarray, write_geo
vtk_fortran_write_vtr calls write_dataarray, write_fielddata, write_geo
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_volatile calls write_check, write_slave
vtk_fortran_write_vtm calls write_data
vtk_fortran_write_vts calls write_data
vtk_fortran_write_vtu calls write_data