write_self_closing_tag – Lib_VTK_IO
write_self_closing_tag Subroutine
11 statements
Source File
private subroutine write_self_closing_tag(self, name, attributes)
Type Bound
xml_writer_abstract
Arguments
Type Intent Optional Attributes Name
class(xml_writer_abstract), intent(inout) :: self
character(len=*), intent(in) :: name
character(len=*), intent(in), optional :: attributes
Calls
Called by
Source Code
   subroutine write_self_closing_tag(self, name, attributes)
   !< Write `<tag_name.../>` self closing tag.
   class(xml_writer_abstract), intent(inout)        :: self       !< Writer.
   character(*),               intent(in)           :: name       !< Tag name.
   character(*),               intent(in), optional :: attributes !< Tag attributes.
   self%tag = xml_tag(name=name, attributes_stream=attributes, sanitize_attributes_value=.true., indent=self%indent, &
                      is_self_closing=.true.)
   if (.not.self%is_volatile) then
      call self%tag%write(unit=self%xml, iostat=self%error, is_indented=.true., end_record=end_rec)
   else
      self%xml_volatile = self%xml_volatile//self%tag%stringify(is_indented=.true.)//end_rec
   endif
   endsubroutine write_self_closing_tag
Call graph
write_self_closing_tag calls stringify
stringify calls chars, end_tag, is_allocated, self_closing_tag, start_tag
self_closing_tag calls attributes
start_tag calls attributes
write_dataarray_tag_appended calls write_self_closing_tag
write_parallel_block_file calls write_self_closing_tag
write_parallel_block_files_array calls write_self_closing_tag
write_parallel_block_files_string calls write_self_closing_tag
write_parallel_dataarray calls write_self_closing_tag
write_parallel_geo calls write_self_closing_tag
write_topology_tag calls write_self_closing_tag
initialize calls write_topology_tag, finalize
write_dataarray1_rank1_i1p calls write_dataarray_tag_appended
write_dataarray1_rank1_i2p calls write_dataarray_tag_appended
write_dataarray1_rank1_i4p calls write_dataarray_tag_appended
write_dataarray1_rank1_i8p calls write_dataarray_tag_appended
write_dataarray1_rank1_r4p calls write_dataarray_tag_appended
write_dataarray1_rank1_r8p calls write_dataarray_tag_appended
write_dataarray1_rank2_i1p calls write_dataarray_tag_appended
write_dataarray1_rank2_i2p calls write_dataarray_tag_appended
write_dataarray1_rank2_i4p calls write_dataarray_tag_appended
write_dataarray1_rank2_i8p calls write_dataarray_tag_appended
write_dataarray1_rank2_r4p calls write_dataarray_tag_appended
write_dataarray1_rank2_r8p calls write_dataarray_tag_appended
write_dataarray1_rank3_i1p calls write_dataarray_tag_appended
write_dataarray1_rank3_i2p calls write_dataarray_tag_appended
write_dataarray1_rank3_i4p calls write_dataarray_tag_appended
write_dataarray1_rank3_i8p calls write_dataarray_tag_appended
write_dataarray1_rank3_r4p calls write_dataarray_tag_appended
write_dataarray1_rank3_r8p calls write_dataarray_tag_appended
write_dataarray1_rank4_i1p calls write_dataarray_tag_appended
write_dataarray1_rank4_i2p calls write_dataarray_tag_appended
write_dataarray1_rank4_i4p calls write_dataarray_tag_appended
write_dataarray1_rank4_i8p calls write_dataarray_tag_appended
write_dataarray1_rank4_r4p calls write_dataarray_tag_appended
write_dataarray1_rank4_r8p calls write_dataarray_tag_appended
write_dataarray3_rank1_i1p calls write_dataarray_tag_appended
write_dataarray3_rank1_i2p calls write_dataarray_tag_appended
write_dataarray3_rank1_i4p calls write_dataarray_tag_appended
write_dataarray3_rank1_i8p calls write_dataarray_tag_appended
write_dataarray3_rank1_r4p calls write_dataarray_tag_appended
write_dataarray3_rank1_r8p calls write_dataarray_tag_appended
write_dataarray3_rank3_i1p calls write_dataarray_tag_appended
write_dataarray3_rank3_i2p calls write_dataarray_tag_appended
write_dataarray3_rank3_i4p calls write_dataarray_tag_appended
write_dataarray3_rank3_i8p calls write_dataarray_tag_appended
write_dataarray3_rank3_r4p calls write_dataarray_tag_appended
write_dataarray3_rank3_r8p calls write_dataarray_tag_appended
write_dataarray6_rank1_i1p calls write_dataarray_tag_appended
write_dataarray6_rank1_i2p calls write_dataarray_tag_appended
write_dataarray6_rank1_i4p calls write_dataarray_tag_appended
write_dataarray6_rank1_i8p calls write_dataarray_tag_appended
write_dataarray6_rank1_r4p calls write_dataarray_tag_appended
write_dataarray6_rank1_r8p calls write_dataarray_tag_appended
write_dataarray6_rank3_i1p calls write_dataarray_tag_appended
write_dataarray6_rank3_i2p calls write_dataarray_tag_appended
write_dataarray6_rank3_i4p calls write_dataarray_tag_appended
write_dataarray6_rank3_i8p calls write_dataarray_tag_appended
write_dataarray6_rank3_r4p calls write_dataarray_tag_appended
write_dataarray6_rank3_r8p calls write_dataarray_tag_appended
write_pvts calls write_parallel_dataarray, write_parallel_geo
parse_scratch_files calls write_parallel_block_files, write_block
write_block_array calls write_parallel_block_files
write_block_string calls write_parallel_block_files
vtk_fortran_write_pvts calls write_pvts
finalize calls parse_scratch_files
vtk_fortran_write_vtm calls write_block