write_on_scratch_dataarray1_rank2 – Lib_VTK_IO
write_on_scratch_dataarray1_rank2 Function
33 statements
Source File
private function write_on_scratch_dataarray1_rank2(self, x) result(n_byte)
Type Bound
xml_writer_appended
Arguments
Type Intent Optional Attributes Name
class(xml_writer_appended), intent(inout) :: self
class(*), intent(in) :: x(1:,1:)
Return Value integer(kind=I4P)
Called by
Source Code
  function write_on_scratch_dataarray1_rank2(self, x) result(n_byte)
  !< Write a dataarray with 1 components of rank 2.
  class(xml_writer_appended), intent(inout) :: self     !< Writer.
  class(*),                   intent(in)    :: x(1:,1:) !< Data variable.
  integer(I4P)                              :: n_byte   !< Number of bytes
  integer(I4P)                              :: nn       !< Number of elements.
  nn = size(x, dim=1)*size(x, dim=2)
  select type(x)
  type is(real(R8P))
    n_byte = nn*BYR8P
    write(unit=self%scratch, iostat=self%error)n_byte, 'R8', nn
    write(unit=self%scratch, iostat=self%error)x
  type is(real(R4P))
    n_byte = nn*BYR4P
    write(unit=self%scratch, iostat=self%error)n_byte, 'R4', nn
    write(unit=self%scratch, iostat=self%error)x
  type is(integer(I8P))
    n_byte = nn*BYI8P
    write(unit=self%scratch, iostat=self%error)n_byte, 'I8', nn
    write(unit=self%scratch, iostat=self%error)x
  type is(integer(I4P))
    n_byte = nn*BYI4P
    write(unit=self%scratch, iostat=self%error)n_byte, 'I4', nn
    write(unit=self%scratch, iostat=self%error)x
  type is(integer(I2P))
    n_byte = nn*BYI2P
    write(unit=self%scratch, iostat=self%error)n_byte, 'I2', nn
    write(unit=self%scratch, iostat=self%error)x
  type is(integer(I1P))
    n_byte = nn*BYI1P
    write(unit=self%scratch, iostat=self%error)n_byte, 'I1', nn
    write(unit=self%scratch, iostat=self%error)x
  endselect
  endfunction write_on_scratch_dataarray1_rank2
Call graph
write_dataarray1_rank1_i1p calls write_on_scratch_dataarray
write_dataarray1_rank1_i2p calls write_on_scratch_dataarray
write_dataarray1_rank1_i4p calls write_on_scratch_dataarray
write_dataarray1_rank1_i8p calls write_on_scratch_dataarray
write_dataarray1_rank1_r4p calls write_on_scratch_dataarray
write_dataarray1_rank1_r8p calls write_on_scratch_dataarray
write_dataarray1_rank2_i1p calls write_on_scratch_dataarray
write_dataarray1_rank2_i2p calls write_on_scratch_dataarray
write_dataarray1_rank2_i4p calls write_on_scratch_dataarray
write_dataarray1_rank2_i8p calls write_on_scratch_dataarray
write_dataarray1_rank2_r4p calls write_on_scratch_dataarray
write_dataarray1_rank2_r8p calls write_on_scratch_dataarray
write_dataarray1_rank3_i1p calls write_on_scratch_dataarray
write_dataarray1_rank3_i2p calls write_on_scratch_dataarray
write_dataarray1_rank3_i4p calls write_on_scratch_dataarray
write_dataarray1_rank3_i8p calls write_on_scratch_dataarray
write_dataarray1_rank3_r4p calls write_on_scratch_dataarray
write_dataarray1_rank3_r8p calls write_on_scratch_dataarray
write_dataarray1_rank4_i1p calls write_on_scratch_dataarray
write_dataarray1_rank4_i2p calls write_on_scratch_dataarray
write_dataarray1_rank4_i4p calls write_on_scratch_dataarray
write_dataarray1_rank4_i8p calls write_on_scratch_dataarray
write_dataarray1_rank4_r4p calls write_on_scratch_dataarray
write_dataarray1_rank4_r8p calls write_on_scratch_dataarray
write_dataarray3_rank1_i1p calls write_on_scratch_dataarray
write_dataarray3_rank1_i2p calls write_on_scratch_dataarray
write_dataarray3_rank1_i4p calls write_on_scratch_dataarray
write_dataarray3_rank1_i8p calls write_on_scratch_dataarray
write_dataarray3_rank1_r4p calls write_on_scratch_dataarray
write_dataarray3_rank1_r8p calls write_on_scratch_dataarray
write_dataarray3_rank3_i1p calls write_on_scratch_dataarray
write_dataarray3_rank3_i2p calls write_on_scratch_dataarray
write_dataarray3_rank3_i4p calls write_on_scratch_dataarray
write_dataarray3_rank3_i8p calls write_on_scratch_dataarray
write_dataarray3_rank3_r4p calls write_on_scratch_dataarray
write_dataarray3_rank3_r8p calls write_on_scratch_dataarray
write_dataarray6_rank1_i1p calls write_on_scratch_dataarray
write_dataarray6_rank1_i2p calls write_on_scratch_dataarray
write_dataarray6_rank1_i4p calls write_on_scratch_dataarray
write_dataarray6_rank1_i8p calls write_on_scratch_dataarray
write_dataarray6_rank1_r4p calls write_on_scratch_dataarray
write_dataarray6_rank1_r8p calls write_on_scratch_dataarray
write_dataarray6_rank3_i1p calls write_on_scratch_dataarray
write_dataarray6_rank3_i2p calls write_on_scratch_dataarray
write_dataarray6_rank3_i4p calls write_on_scratch_dataarray
write_dataarray6_rank3_i8p calls write_on_scratch_dataarray
write_dataarray6_rank3_r4p calls write_on_scratch_dataarray
write_dataarray6_rank3_r8p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank1_i1p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank1_i2p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank1_i4p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank1_i8p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank1_r4p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank1_r8p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank2_i1p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank2_i2p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank2_i4p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank2_i8p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank2_r4p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank2_r8p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank3_i1p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank3_i2p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank3_i4p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank3_i8p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank3_r4p calls write_on_scratch_dataarray
write_on_scratch_dataarray3_rank3_r8p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank1_i1p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank1_i2p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank1_i4p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank1_i8p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank1_r4p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank1_r8p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank2_i1p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank2_i2p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank2_i4p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank2_i8p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank2_r4p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank2_r8p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank3_i1p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank3_i2p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank3_i4p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank3_i8p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank3_r4p calls write_on_scratch_dataarray
write_on_scratch_dataarray6_rank3_r8p calls write_on_scratch_dataarray