import { withMermaid } from 'vitepress-plugin-mermaid'
import { existsSync, readFileSync } from 'node:fs'

// the API pages (formal) and the coverage analysis are generated by the Docs workflow into git-ignored files
// (`fobis rule --ex makedoc` and `--ex makecoverage-analysis` locally): without them the site still builds, with an
// empty API sidebar, no coverage page and the links to them left dead
const apiSidebarFile = new URL('../api/_sidebar.json', import.meta.url)
const apiGenerated = existsSync(apiSidebarFile)
const apiSidebar = apiGenerated ? JSON.parse(readFileSync(apiSidebarFile, 'utf-8')) : []
const coverageGenerated = existsSync(new URL('../guide/coverage-analysis.md', import.meta.url))
const coverage = coverageGenerated ? [{ text: 'Coverage Analysis', link: '/guide/coverage-analysis' }] : []
const deadLinks = [...(apiGenerated ? [] : [/^\/api\//]), ...(coverageGenerated ? [] : [/coverage-analysis/])]

// one sidebar for every page but the API, in reading order: the "previous" and "next" links at the bottom of a page
// follow it, so the documentation reads from the first page to the last
const docs = [
  {
    text: 'Start here',
    items: [
      { text: 'Introduction', link: '/guide/' },
      { text: 'Installation', link: '/guide/installation' },
    ],
  },
  {
    text: 'Tutorial',
    items: [
      { text: 'Overview',                link: '/manual/' },
      { text: '1. A first file',         link: '/manual/tutorial/01-first-file' },
      { text: '2. Formats',              link: '/manual/tutorial/02-formats' },
      { text: '3. More data',            link: '/manual/tutorial/03-more-data' },
      { text: '4. A time series',        link: '/manual/tutorial/04-time-series' },
      { text: '5. An unstructured mesh', link: '/manual/tutorial/05-unstructured' },
      { text: '6. Going parallel',       link: '/manual/tutorial/06-parallel' },
      { text: '7. An assembly',          link: '/manual/tutorial/07-assembly' },
      { text: '8. Restart',              link: '/manual/tutorial/08-restart' },
    ],
  },
  {
    text: 'Recipes',
    items: [
      { text: 'Cookbook', link: '/manual/cookbook' },
    ],
  },
  {
    text: 'Reference',
    items: [
      { text: 'Features',                     link: '/guide/features' },
      { text: 'Topologies',                   link: '/guide/topologies' },
      { text: 'Data arrays',                  link: '/guide/data' },
      { text: 'Formats and large data',       link: '/guide/formats' },
      { text: 'Parallel and composite files', link: '/guide/parallel' },
      { text: 'Reading files',                link: '/guide/reading' },
      { text: 'Procedures summary',           link: '/guide/api-reference' },
    ],
  },
  {
    text: 'Project',
    items: [
      { text: 'Contributing',      link: '/guide/contributing' },
      ...coverage,
      { text: 'Changelog',         link: '/guide/changelog' },
    ],
  },
]

export default withMermaid({
  title: 'VTKFortran Documentation',
  base: '/VTKFortran/',
  ignoreDeadLinks: deadLinks.length > 0 ? deadLinks : false,
  markdown: {
    math: true,
    languages: ['fortran-free-form', 'fortran-fixed-form'],
    languageAlias: {
      'fortran': 'fortran-free-form',
      'f90': 'fortran-free-form',
      'f95': 'fortran-free-form',
      'f03': 'fortran-free-form',
      'f08': 'fortran-free-form',
      'f77': 'fortran-fixed-form',
    },
  },
  themeConfig: {
    nav: [
      { text: 'Start here', link: '/guide/', activeMatch: '^/guide/(index|installation)' },
      { text: 'Tutorial', link: '/manual/tutorial/01-first-file', activeMatch: '^/manual/(index|tutorial/)' },
      { text: 'Cookbook', link: '/manual/cookbook', activeMatch: '^/manual/cookbook' },
      {
        text: 'Reference',
        link: '/guide/features',
        activeMatch: '^/guide/(features|topologies|data|formats|parallel|reading|api-reference)',
      },
      { text: 'API', link: '/api/' },
      {
        text: 'Project',
        items: [
          { text: 'Contributing',      link: '/guide/contributing' },
          ...coverage,
          { text: 'Changelog',         link: '/guide/changelog' },
        ],
      },
      { text: 'GitHub', link: 'https://github.com/szaghi/VTKFortran' },
    ],
    sidebar: {
      '/guide/': docs,
      '/manual/': docs,
      '/api/': [
        {
          text: 'API Reference',
          items: [
            { text: 'Overview', link: '/api/' },
          ],
        },
        ...apiSidebar,
      ],
    },
    search: {
      provider: 'local',
    },
  },
  mermaid: {},
  vite: {
    build: {
      target: 'es2022',
    },
    optimizeDeps: {
      include: ['mermaid'],
    },
  },
})
