b64_encode – Lib_VTK_IO
b64_encode Interface
3 statements
Source File
public interface b64_encode
Calls
Called by
Module Procedures
private pure subroutine b64_encode_R8(n, code)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_R8_a(n, code)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_R4(n, code)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_R4_a(n, code)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I8(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I8_a(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I4(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I4_a(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I2(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I2_a(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I1(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_I1_a(n, code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n(1:)
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_string(s, code)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s
character(len=:), intent(out), allocatable :: code
private pure subroutine b64_encode_string_a(s, code)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s(1:)
character(len=:), intent(out), allocatable :: code
Call graph
b64_encode calls b64_encode_i1, b64_encode_i1_a, b64_encode_i2, b64_encode_i2_a, b64_encode_i4, b64_encode_i4_a, b64_encode_i8, b64_encode_i8_a, b64_encode_r4, b64_encode_r4_a, b64_encode_r8, b64_encode_r8_a, b64_encode_string, b64_encode_string_a
b64_encode_i1 calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_string calls byte_size, encode_bits
b64_encode_string_a calls byte_size, encode_bits
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p
encode calls b64_encode
encode_binary_dataarray1_rank1_i1p calls b64_encode
encode_binary_dataarray1_rank1_i2p calls b64_encode
encode_binary_dataarray1_rank1_i4p calls b64_encode
encode_binary_dataarray1_rank1_i8p calls b64_encode
encode_binary_dataarray1_rank1_r4p calls b64_encode
encode_binary_dataarray1_rank1_r8p calls b64_encode
encode_binary_dataarray1_rank2_i1p calls b64_encode
encode_binary_dataarray1_rank2_i2p calls b64_encode
encode_binary_dataarray1_rank2_i4p calls b64_encode
encode_binary_dataarray1_rank2_i8p calls b64_encode
encode_binary_dataarray1_rank2_r4p calls b64_encode
encode_binary_dataarray1_rank2_r8p calls b64_encode
encode_binary_dataarray1_rank3_i1p calls b64_encode
encode_binary_dataarray1_rank3_i2p calls b64_encode
encode_binary_dataarray1_rank3_i4p calls b64_encode
encode_binary_dataarray1_rank3_i8p calls b64_encode
encode_binary_dataarray1_rank3_r4p calls b64_encode
encode_binary_dataarray1_rank3_r8p calls b64_encode
encode_binary_dataarray1_rank4_i1p calls b64_encode
encode_binary_dataarray1_rank4_i2p calls b64_encode
encode_binary_dataarray1_rank4_i4p calls b64_encode
encode_binary_dataarray1_rank4_i8p calls b64_encode
encode_binary_dataarray1_rank4_r4p calls b64_encode
encode_binary_dataarray1_rank4_r8p calls b64_encode
encode_binary_dataarray3_rank1_i1p calls b64_encode
encode_binary_dataarray3_rank1_i2p calls b64_encode
encode_binary_dataarray3_rank1_i4p calls b64_encode
encode_binary_dataarray3_rank1_i8p calls b64_encode
encode_binary_dataarray3_rank1_r4p calls b64_encode
encode_binary_dataarray3_rank1_r8p calls b64_encode
encode_binary_dataarray3_rank3_i1p calls b64_encode
encode_binary_dataarray3_rank3_i2p calls b64_encode
encode_binary_dataarray3_rank3_i4p calls b64_encode
encode_binary_dataarray3_rank3_i8p calls b64_encode
encode_binary_dataarray3_rank3_r4p calls b64_encode
encode_binary_dataarray3_rank3_r8p calls b64_encode
encode_binary_dataarray6_rank1_i1p calls b64_encode
encode_binary_dataarray6_rank1_i2p calls b64_encode
encode_binary_dataarray6_rank1_i4p calls b64_encode
encode_binary_dataarray6_rank1_i8p calls b64_encode
encode_binary_dataarray6_rank1_r4p calls b64_encode
encode_binary_dataarray6_rank1_r8p calls b64_encode
encode_binary_dataarray6_rank3_i1p calls b64_encode
encode_binary_dataarray6_rank3_i2p calls b64_encode
encode_binary_dataarray6_rank3_i4p calls b64_encode
encode_binary_dataarray6_rank3_i8p calls b64_encode
encode_binary_dataarray6_rank3_r4p calls b64_encode
encode_binary_dataarray6_rank3_r8p calls b64_encode
volatile_doctest calls b64_encode, encode
encode_binary_dataarray calls encode_binary_dataarray1_rank1_i1p, encode_binary_dataarray1_rank1_i2p, encode_binary_dataarray1_rank1_i4p, encode_binary_dataarray1_rank1_i8p, encode_binary_dataarray1_rank1_r4p, encode_binary_dataarray1_rank1_r8p, encode_binary_dataarray1_rank2_i1p, encode_binary_dataarray1_rank2_i2p, encode_binary_dataarray1_rank2_i4p, encode_binary_dataarray1_rank2_i8p, encode_binary_dataarray1_rank2_r4p, encode_binary_dataarray1_rank2_r8p, encode_binary_dataarray1_rank3_i1p, encode_binary_dataarray1_rank3_i2p, encode_binary_dataarray1_rank3_i4p, encode_binary_dataarray1_rank3_i8p, encode_binary_dataarray1_rank3_r4p, encode_binary_dataarray1_rank3_r8p, encode_binary_dataarray1_rank4_i1p, encode_binary_dataarray1_rank4_i2p, encode_binary_dataarray1_rank4_i4p, encode_binary_dataarray1_rank4_i8p, encode_binary_dataarray1_rank4_r4p, encode_binary_dataarray1_rank4_r8p, encode_binary_dataarray3_rank1_i1p, encode_binary_dataarray3_rank1_i2p, encode_binary_dataarray3_rank1_i4p, encode_binary_dataarray3_rank1_i8p, encode_binary_dataarray3_rank1_r4p, encode_binary_dataarray3_rank1_r8p, encode_binary_dataarray3_rank3_i1p, encode_binary_dataarray3_rank3_i2p, encode_binary_dataarray3_rank3_i4p, encode_binary_dataarray3_rank3_i8p, encode_binary_dataarray3_rank3_r4p, encode_binary_dataarray3_rank3_r8p, encode_binary_dataarray6_rank1_i1p, encode_binary_dataarray6_rank1_i2p, encode_binary_dataarray6_rank1_i4p, encode_binary_dataarray6_rank1_i8p, encode_binary_dataarray6_rank1_r4p, encode_binary_dataarray6_rank1_r8p, encode_binary_dataarray6_rank3_i1p, encode_binary_dataarray6_rank3_i2p, encode_binary_dataarray6_rank3_i4p, encode_binary_dataarray6_rank3_i8p, encode_binary_dataarray6_rank3_r4p, encode_binary_dataarray6_rank3_r8p
write_dataarray1_rank1_i1p calls encode_binary_dataarray
write_dataarray1_rank1_i2p calls encode_binary_dataarray
write_dataarray1_rank1_i4p calls encode_binary_dataarray
write_dataarray1_rank1_i8p calls encode_binary_dataarray
write_dataarray1_rank1_r4p calls encode_binary_dataarray
write_dataarray1_rank1_r8p calls encode_binary_dataarray
write_dataarray1_rank2_i1p calls encode_binary_dataarray
write_dataarray1_rank2_i2p calls encode_binary_dataarray
write_dataarray1_rank2_i4p calls encode_binary_dataarray
write_dataarray1_rank2_i8p calls encode_binary_dataarray
write_dataarray1_rank2_r4p calls encode_binary_dataarray
write_dataarray1_rank2_r8p calls encode_binary_dataarray
write_dataarray1_rank3_i1p calls encode_binary_dataarray
write_dataarray1_rank3_i2p calls encode_binary_dataarray
write_dataarray1_rank3_i4p calls encode_binary_dataarray
write_dataarray1_rank3_i8p calls encode_binary_dataarray
write_dataarray1_rank3_r4p calls encode_binary_dataarray
write_dataarray1_rank3_r8p calls encode_binary_dataarray
write_dataarray1_rank4_i1p calls encode_binary_dataarray
write_dataarray1_rank4_i2p calls encode_binary_dataarray
write_dataarray1_rank4_i4p calls encode_binary_dataarray
write_dataarray1_rank4_i8p calls encode_binary_dataarray
write_dataarray1_rank4_r4p calls encode_binary_dataarray
write_dataarray1_rank4_r8p calls encode_binary_dataarray
write_dataarray3_rank1_i1p calls encode_binary_dataarray
write_dataarray3_rank1_i2p calls encode_binary_dataarray
write_dataarray3_rank1_i4p calls encode_binary_dataarray
write_dataarray3_rank1_i8p calls encode_binary_dataarray
write_dataarray3_rank1_r4p calls encode_binary_dataarray
write_dataarray3_rank1_r8p calls encode_binary_dataarray
write_dataarray3_rank3_i1p calls encode_binary_dataarray
write_dataarray3_rank3_i2p calls encode_binary_dataarray
write_dataarray3_rank3_i4p calls encode_binary_dataarray
write_dataarray3_rank3_i8p calls encode_binary_dataarray
write_dataarray3_rank3_r4p calls encode_binary_dataarray
write_dataarray3_rank3_r8p calls encode_binary_dataarray
write_dataarray6_rank1_i1p calls encode_binary_dataarray
write_dataarray6_rank1_i2p calls encode_binary_dataarray
write_dataarray6_rank1_i4p calls encode_binary_dataarray
write_dataarray6_rank1_i8p calls encode_binary_dataarray
write_dataarray6_rank1_r4p calls encode_binary_dataarray
write_dataarray6_rank1_r8p calls encode_binary_dataarray
write_dataarray6_rank3_i1p calls encode_binary_dataarray
write_dataarray6_rank3_i2p calls encode_binary_dataarray
write_dataarray6_rank3_i4p calls encode_binary_dataarray
write_dataarray6_rank3_i8p calls encode_binary_dataarray
write_dataarray6_rank3_r4p calls encode_binary_dataarray
write_dataarray6_rank3_r8p calls encode_binary_dataarray
write_dataarray_appended calls encode_binary_dataarray
finalize calls write_dataarray_appended
write_check calls write_dataarray, write_fielddata, write_geo
write_connectivity calls write_dataarray
write_data calls write_dataarray, write_connectivity, write_geo
write_fielddata1_rank0 calls write_dataarray
write_geo_rect_data3_rank1_r4p calls write_dataarray
write_geo_rect_data3_rank1_r8p calls write_dataarray
write_geo_strg_data1_rank2_r4p calls write_dataarray
write_geo_strg_data1_rank2_r8p calls write_dataarray
write_geo_strg_data1_rank4_r4p calls write_dataarray
write_geo_strg_data1_rank4_r8p calls write_dataarray
write_geo_strg_data3_rank1_r4p calls write_dataarray
write_geo_strg_data3_rank1_r8p calls write_dataarray
write_geo_strg_data3_rank3_r4p calls write_dataarray
write_geo_strg_data3_rank3_r8p calls write_dataarray
write_geo_unst_data1_rank2_r4p calls write_dataarray
write_geo_unst_data1_rank2_r8p calls write_dataarray
write_geo_unst_data3_rank1_r4p calls write_dataarray
write_geo_unst_data3_rank1_r8p calls write_dataarray
write_pvts calls write_dataarray
write_slave calls write_dataarray, write_fielddata, write_geo
write_vts calls write_dataarray, write_geo
vtk_fortran_write_vtr calls write_dataarray, write_fielddata, write_geo
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_volatile calls write_check, write_slave
vtk_fortran_write_vtm calls write_data
vtk_fortran_write_vts calls write_data
vtk_fortran_write_vtu calls write_data