b64_decode – Lib_VTK_IO
b64_decode Interface
3 statements
Source File
public interface b64_decode
Calls
Contents
Module Procedures
b64_decode_R8 b64_decode_R8_a b64_decode_R4 b64_decode_R4_a b64_decode_I8 b64_decode_I8_a b64_decode_I4 b64_decode_I4_a b64_decode_I2 b64_decode_I2_a b64_decode_I1 b64_decode_I1_a b64_decode_string b64_decode_string_a
Module Procedures
private elemental subroutine b64_decode_R8(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
real(kind=R8P), intent(out) :: n
private pure subroutine b64_decode_R8_a(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
real(kind=R8P), intent(out) :: n(1:)
private elemental subroutine b64_decode_R4(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
real(kind=R4P), intent(out) :: n
private pure subroutine b64_decode_R4_a(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
real(kind=R4P), intent(out) :: n(1:)
private elemental subroutine b64_decode_I8(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
integer(kind=I8P), intent(out) :: n
private pure subroutine b64_decode_I8_a(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
integer(kind=I8P), intent(out) :: n(1:)
private elemental subroutine b64_decode_I4(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
integer(kind=I4P), intent(out) :: n
private pure subroutine b64_decode_I4_a(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
integer(kind=I4P), intent(out) :: n(1:)
private elemental subroutine b64_decode_I2(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
integer(kind=I2P), intent(out) :: n
private pure subroutine b64_decode_I2_a(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
integer(kind=I2P), intent(out) :: n(1:)
private elemental subroutine b64_decode_I1(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
integer(kind=I1P), intent(out) :: n
private pure subroutine b64_decode_I1_a(code, n)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
integer(kind=I1P), intent(out) :: n(1:)
private elemental subroutine b64_decode_string(code, s)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
character, intent(out) :: s
private pure subroutine b64_decode_string_a(code, s)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: code
character, intent(out) :: s(1:)
Call graph
b64_decode calls b64_decode_r4_a, b64_decode_i4, b64_decode_i1, b64_decode_i4_a, b64_decode_r4, b64_decode_i1_a, b64_decode_r8, b64_decode_r8_a, b64_decode_i8, b64_decode_i8_a, b64_decode_i2, b64_decode_i2_a, b64_decode_string, b64_decode_string_a
b64_decode_r4_a calls decode_bits
b64_decode_i4 calls decode_bits
b64_decode_i1 calls decode_bits
b64_decode_i4_a calls decode_bits
b64_decode_r4 calls decode_bits
b64_decode_i1_a calls decode_bits
b64_decode_r8 calls decode_bits
b64_decode_r8_a calls decode_bits
b64_decode_i8 calls decode_bits
b64_decode_i8_a calls decode_bits
b64_decode_i2 calls decode_bits
b64_decode_i2_a calls decode_bits
b64_decode_string calls decode_bits, byte_size
b64_decode_string_a calls decode_bits, byte_size
byte_size calls byte_size_i8p, byte_size_i2p, byte_size_r4p, byte_size_i4p, byte_size_i1p, byte_size_r8p, byte_size_chr