byte_size – Lib_VTK_IO
byte_size Interface
3 statements
Source File
public interface byte_size
Calls
Called by
Module Procedures
private elemental function byte_size_I8P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: i
Return Value integer(kind=I1P)
private elemental function byte_size_I4P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: i
Return Value integer(kind=I1P)
private elemental function byte_size_I2P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: i
Return Value integer(kind=I1P)
private elemental function byte_size_I1P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: i
Return Value integer(kind=I1P)
private elemental function byte_size_R8P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: i
Return Value integer(kind=I1P)
private elemental function byte_size_R4P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: i
Return Value integer(kind=I1P)
private elemental function byte_size_chr(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: i
Return Value integer(kind=I4P)
Call graph
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p
b64_decode_string calls byte_size
b64_decode_string_a calls byte_size
b64_encode_string calls byte_size
b64_encode_string_a calls byte_size
volatile_doctest calls byte_size, b64_encode, b64_decode, encode, decode
b64_decode calls b64_decode_string, b64_decode_string_a
b64_encode calls b64_encode_string, b64_encode_string_a
b64_decode_up calls b64_decode_string, b64_decode_up_a, b64_decode_up
b64_decode_up_a calls b64_decode_string_a
b64_encode_up calls b64_encode_string, b64_encode_up_a, b64_encode_up
b64_encode_up_a calls b64_encode_string_a
decode calls b64_decode
encode calls b64_encode
encode_binary_dataarray1_rank1_i1p calls b64_encode
encode_binary_dataarray1_rank1_i2p calls b64_encode
encode_binary_dataarray1_rank1_i4p calls b64_encode
encode_binary_dataarray1_rank1_i8p calls b64_encode
encode_binary_dataarray1_rank1_r4p calls b64_encode
encode_binary_dataarray1_rank1_r8p calls b64_encode
encode_binary_dataarray1_rank2_i1p calls b64_encode
encode_binary_dataarray1_rank2_i2p calls b64_encode
encode_binary_dataarray1_rank2_i4p calls b64_encode
encode_binary_dataarray1_rank2_i8p calls b64_encode
encode_binary_dataarray1_rank2_r4p calls b64_encode
encode_binary_dataarray1_rank2_r8p calls b64_encode
encode_binary_dataarray1_rank3_i1p calls b64_encode
encode_binary_dataarray1_rank3_i2p calls b64_encode
encode_binary_dataarray1_rank3_i4p calls b64_encode
encode_binary_dataarray1_rank3_i8p calls b64_encode
encode_binary_dataarray1_rank3_r4p calls b64_encode
encode_binary_dataarray1_rank3_r8p calls b64_encode
encode_binary_dataarray1_rank4_i1p calls b64_encode
encode_binary_dataarray1_rank4_i2p calls b64_encode
encode_binary_dataarray1_rank4_i4p calls b64_encode
encode_binary_dataarray1_rank4_i8p calls b64_encode
encode_binary_dataarray1_rank4_r4p calls b64_encode
encode_binary_dataarray1_rank4_r8p calls b64_encode
encode_binary_dataarray3_rank1_i1p calls b64_encode
encode_binary_dataarray3_rank1_i2p calls b64_encode
encode_binary_dataarray3_rank1_i4p calls b64_encode
encode_binary_dataarray3_rank1_i8p calls b64_encode
encode_binary_dataarray3_rank1_r4p calls b64_encode
encode_binary_dataarray3_rank1_r8p calls b64_encode
encode_binary_dataarray3_rank3_i1p calls b64_encode
encode_binary_dataarray3_rank3_i2p calls b64_encode
encode_binary_dataarray3_rank3_i4p calls b64_encode
encode_binary_dataarray3_rank3_i8p calls b64_encode
encode_binary_dataarray3_rank3_r4p calls b64_encode
encode_binary_dataarray3_rank3_r8p calls b64_encode
encode_binary_dataarray6_rank1_i1p calls b64_encode
encode_binary_dataarray6_rank1_i2p calls b64_encode
encode_binary_dataarray6_rank1_i4p calls b64_encode
encode_binary_dataarray6_rank1_i8p calls b64_encode
encode_binary_dataarray6_rank1_r4p calls b64_encode
encode_binary_dataarray6_rank1_r8p calls b64_encode
encode_binary_dataarray6_rank3_i1p calls b64_encode
encode_binary_dataarray6_rank3_i2p calls b64_encode
encode_binary_dataarray6_rank3_i4p calls b64_encode
encode_binary_dataarray6_rank3_i8p calls b64_encode
encode_binary_dataarray6_rank3_r4p calls b64_encode
encode_binary_dataarray6_rank3_r8p calls b64_encode
encode_binary_dataarray calls encode_binary_dataarray1_rank1_i1p, encode_binary_dataarray1_rank1_i2p, encode_binary_dataarray1_rank1_i4p, encode_binary_dataarray1_rank1_i8p, encode_binary_dataarray1_rank1_r4p, encode_binary_dataarray1_rank1_r8p, encode_binary_dataarray1_rank2_i1p, encode_binary_dataarray1_rank2_i2p, encode_binary_dataarray1_rank2_i4p, encode_binary_dataarray1_rank2_i8p, encode_binary_dataarray1_rank2_r4p, encode_binary_dataarray1_rank2_r8p, encode_binary_dataarray1_rank3_i1p, encode_binary_dataarray1_rank3_i2p, encode_binary_dataarray1_rank3_i4p, encode_binary_dataarray1_rank3_i8p, encode_binary_dataarray1_rank3_r4p, encode_binary_dataarray1_rank3_r8p, encode_binary_dataarray1_rank4_i1p, encode_binary_dataarray1_rank4_i2p, encode_binary_dataarray1_rank4_i4p, encode_binary_dataarray1_rank4_i8p, encode_binary_dataarray1_rank4_r4p, encode_binary_dataarray1_rank4_r8p, encode_binary_dataarray3_rank1_i1p, encode_binary_dataarray3_rank1_i2p, encode_binary_dataarray3_rank1_i4p, encode_binary_dataarray3_rank1_i8p, encode_binary_dataarray3_rank1_r4p, encode_binary_dataarray3_rank1_r8p, encode_binary_dataarray3_rank3_i1p, encode_binary_dataarray3_rank3_i2p, encode_binary_dataarray3_rank3_i4p, encode_binary_dataarray3_rank3_i8p, encode_binary_dataarray3_rank3_r4p, encode_binary_dataarray3_rank3_r8p, encode_binary_dataarray6_rank1_i1p, encode_binary_dataarray6_rank1_i2p, encode_binary_dataarray6_rank1_i4p, encode_binary_dataarray6_rank1_i8p, encode_binary_dataarray6_rank1_r4p, encode_binary_dataarray6_rank1_r8p, encode_binary_dataarray6_rank3_i1p, encode_binary_dataarray6_rank3_i2p, encode_binary_dataarray6_rank3_i4p, encode_binary_dataarray6_rank3_i8p, encode_binary_dataarray6_rank3_r4p, encode_binary_dataarray6_rank3_r8p
write_dataarray1_rank1_i1p calls encode_binary_dataarray
write_dataarray1_rank1_i2p calls encode_binary_dataarray
write_dataarray1_rank1_i4p calls encode_binary_dataarray
write_dataarray1_rank1_i8p calls encode_binary_dataarray
write_dataarray1_rank1_r4p calls encode_binary_dataarray
write_dataarray1_rank1_r8p calls encode_binary_dataarray
write_dataarray1_rank2_i1p calls encode_binary_dataarray
write_dataarray1_rank2_i2p calls encode_binary_dataarray
write_dataarray1_rank2_i4p calls encode_binary_dataarray
write_dataarray1_rank2_i8p calls encode_binary_dataarray
write_dataarray1_rank2_r4p calls encode_binary_dataarray
write_dataarray1_rank2_r8p calls encode_binary_dataarray
write_dataarray1_rank3_i1p calls encode_binary_dataarray
write_dataarray1_rank3_i2p calls encode_binary_dataarray
write_dataarray1_rank3_i4p calls encode_binary_dataarray
write_dataarray1_rank3_i8p calls encode_binary_dataarray
write_dataarray1_rank3_r4p calls encode_binary_dataarray
write_dataarray1_rank3_r8p calls encode_binary_dataarray
write_dataarray1_rank4_i1p calls encode_binary_dataarray
write_dataarray1_rank4_i2p calls encode_binary_dataarray
write_dataarray1_rank4_i4p calls encode_binary_dataarray
write_dataarray1_rank4_i8p calls encode_binary_dataarray
write_dataarray1_rank4_r4p calls encode_binary_dataarray
write_dataarray1_rank4_r8p calls encode_binary_dataarray
write_dataarray3_rank1_i1p calls encode_binary_dataarray
write_dataarray3_rank1_i2p calls encode_binary_dataarray
write_dataarray3_rank1_i4p calls encode_binary_dataarray
write_dataarray3_rank1_i8p calls encode_binary_dataarray
write_dataarray3_rank1_r4p calls encode_binary_dataarray
write_dataarray3_rank1_r8p calls encode_binary_dataarray
write_dataarray3_rank3_i1p calls encode_binary_dataarray
write_dataarray3_rank3_i2p calls encode_binary_dataarray
write_dataarray3_rank3_i4p calls encode_binary_dataarray
write_dataarray3_rank3_i8p calls encode_binary_dataarray
write_dataarray3_rank3_r4p calls encode_binary_dataarray
write_dataarray3_rank3_r8p calls encode_binary_dataarray
write_dataarray6_rank1_i1p calls encode_binary_dataarray
write_dataarray6_rank1_i2p calls encode_binary_dataarray
write_dataarray6_rank1_i4p calls encode_binary_dataarray
write_dataarray6_rank1_i8p calls encode_binary_dataarray
write_dataarray6_rank1_r4p calls encode_binary_dataarray
write_dataarray6_rank1_r8p calls encode_binary_dataarray
write_dataarray6_rank3_i1p calls encode_binary_dataarray
write_dataarray6_rank3_i2p calls encode_binary_dataarray
write_dataarray6_rank3_i4p calls encode_binary_dataarray
write_dataarray6_rank3_i8p calls encode_binary_dataarray
write_dataarray6_rank3_r4p calls encode_binary_dataarray
write_dataarray6_rank3_r8p calls encode_binary_dataarray
write_dataarray_appended calls encode_binary_dataarray
finalize calls write_dataarray_appended
write_check calls write_dataarray, write_fielddata, write_geo
write_connectivity calls write_dataarray
write_data calls write_dataarray, write_geo, write_connectivity
write_fielddata1_rank0 calls write_dataarray
write_geo_rect_data3_rank1_r4p calls write_dataarray
write_geo_rect_data3_rank1_r8p calls write_dataarray
write_geo_strg_data1_rank2_r4p calls write_dataarray
write_geo_strg_data1_rank2_r8p calls write_dataarray
write_geo_strg_data1_rank4_r4p calls write_dataarray
write_geo_strg_data1_rank4_r8p calls write_dataarray
write_geo_strg_data3_rank1_r4p calls write_dataarray
write_geo_strg_data3_rank1_r8p calls write_dataarray
write_geo_strg_data3_rank3_r4p calls write_dataarray
write_geo_strg_data3_rank3_r8p calls write_dataarray
write_geo_unst_data1_rank2_r4p calls write_dataarray
write_geo_unst_data1_rank2_r8p calls write_dataarray
write_geo_unst_data3_rank1_r4p calls write_dataarray
write_geo_unst_data3_rank1_r8p calls write_dataarray
write_pvts calls write_dataarray
write_slave calls write_dataarray, write_fielddata, write_geo
write_vts calls write_dataarray, write_geo
vtk_fortran_write_vtr calls write_dataarray, write_fielddata, write_geo
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_volatile calls write_check, write_slave
vtk_fortran_write_vtm calls write_data
vtk_fortran_write_vts calls write_data
vtk_fortran_write_vtu calls write_data