byte_size – Lib_VTK_IO
byte_size Interface
3 statements
Source File
public interface byte_size
Calls
Module Procedures
private elemental function byte_size_I8P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: i
Return Value integer(kind=I1P)
private elemental function byte_size_I4P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: i
Return Value integer(kind=I1P)
private elemental function byte_size_I2P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: i
Return Value integer(kind=I1P)
private elemental function byte_size_I1P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: i
Return Value integer(kind=I1P)
private elemental function byte_size_R8P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: i
Return Value integer(kind=I1P)
private elemental function byte_size_R4P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: i
Return Value integer(kind=I1P)
private elemental function byte_size_chr(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: i
Return Value integer(kind=I4P)
Call graph
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p