cton – Lib_VTK_IO
cton Interface
3 statements
Source File
public interface cton
Calls
Module Procedures
private function ctor_R8P(str, knd, pref, error) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
real(kind=R8P), intent(in) :: knd
character(len=*), intent(in), optional :: pref
integer(kind=I4P), intent(out), optional :: error
Return Value real(kind=R8P)
private function ctor_R4P(str, knd, pref, error) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
real(kind=R4P), intent(in) :: knd
character(len=*), intent(in), optional :: pref
integer(kind=I4P), intent(out), optional :: error
Return Value real(kind=R4P)
private function ctoi_I8P(str, knd, pref, error) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer(kind=I8P), intent(in) :: knd
character(len=*), intent(in), optional :: pref
integer(kind=I4P), intent(out), optional :: error
Return Value integer(kind=I8P)
private function ctoi_I4P(str, knd, pref, error) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer(kind=I4P), intent(in) :: knd
character(len=*), intent(in), optional :: pref
integer(kind=I4P), intent(out), optional :: error
Return Value integer(kind=I4P)
private function ctoi_I2P(str, knd, pref, error) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer(kind=I2P), intent(in) :: knd
character(len=*), intent(in), optional :: pref
integer(kind=I4P), intent(out), optional :: error
Return Value integer(kind=I2P)
private function ctoi_I1P(str, knd, pref, error) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer(kind=I1P), intent(in) :: knd
character(len=*), intent(in), optional :: pref
integer(kind=I4P), intent(out), optional :: error
Return Value integer(kind=I1P)
Call graph
cton calls ctoi_i1p, ctoi_i2p, ctoi_i4p, ctoi_i8p, ctor_r4p, ctor_r8p