glob – Lib_VTK_IO
glob Interface
3 statements
Source File
public interface glob
Calls
Called by
Module Procedures
private subroutine glob_character(self, pattern, list)
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
character(len=*), intent(in) :: pattern
character(len=:), intent(out), allocatable :: list(:)
private subroutine glob_string(self, pattern, list)
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
character(len=*), intent(in) :: pattern
type(string), intent(out), allocatable :: list(:)
Call graph
glob calls glob_character, glob_string
glob_character calls glob, chars
glob_string calls read_file, split, tempname
read_file calls chars, read_lines, upper
split calls partition, unique
read_lines calls read_line
unique calls replace
read_line calls chars, upper
replace calls replace_one_occurrence
volatile_doctest calls glob