strjoin – Lib_VTK_IO
strjoin Interface
3 statements
Source File
public interface strjoin
Calls
Contents
Module Procedures
strjoin_strings strjoin_characters strjoin_strings_array strjoin_characters_array
Module Procedures
private pure function strjoin_strings(array, sep) result(join)
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: array(1:)
character(kind=CK,len=*), intent(in), optional :: sep
Return Value type(string)
private pure function strjoin_characters(array, sep, is_trim) result(join)
Arguments
Type Intent Optional Attributes Name
character(kind=CK,len=*), intent(in) :: array(1:)
character(kind=CK,len=*), intent(in), optional :: sep
logical, intent(in), optional :: is_trim
Return Value type(string)
private pure function strjoin_strings_array(array, sep, is_col) result(join)
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: array(1:,1:)
character(kind=CK,len=*), intent(in), optional :: sep
logical, intent(in), optional :: is_col
Return Value type(string),allocatable, (:)
private pure function strjoin_characters_array(array, sep, is_trim, is_col) result(join)
Arguments
Type Intent Optional Attributes Name
character(kind=CK,len=*), intent(in) :: array(1:,1:)
character(kind=CK,len=*), intent(in), optional :: sep
logical, intent(in), optional :: is_trim
logical, intent(in), optional :: is_col
Return Value type(string),allocatable, (:)
Call graph
strjoin calls strjoin_strings, strjoin_characters_array, strjoin_characters, strjoin_strings_array
strjoin_characters_array calls strjoin_characters
strjoin_strings_array calls strjoin_strings