strz – Lib_VTK_IO
strz Interface
3 statements
Source File
public interface strz
Calls
Module Procedures
private elemental function strz_I8P(n, nz_pad) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n
integer(kind=I4P), intent(in), optional :: nz_pad
Return Value character(len=DI8P)
private elemental function strz_I4P(n, nz_pad) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n
integer(kind=I4P), intent(in), optional :: nz_pad
Return Value character(len=DI4P)
private elemental function strz_I2P(n, nz_pad) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n
integer(kind=I4P), intent(in), optional :: nz_pad
Return Value character(len=DI2P)
private elemental function strz_I1P(n, nz_pad) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n
integer(kind=I4P), intent(in), optional :: nz_pad
Return Value character(len=DI1P)
Call graph
strz calls strz_i1p, strz_i2p, strz_i4p, strz_i8p