str – Lib_VTK_IO
str Interface
3 statements
Source File
public interface str
Calls
Called by
Module Procedures
private elemental function strf_R8P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
real(kind=R8P), intent(in) :: n
Return Value character(len=DR8P)
private elemental function str_R8P(n, no_sign, compact) result(str)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n
logical, intent(in), optional :: no_sign
logical, intent(in), optional :: compact
Return Value character(len=DR8P)
private elemental function strf_R4P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
real(kind=R4P), intent(in) :: n
Return Value character(len=DR4P)
private elemental function str_R4P(n, no_sign, compact) result(str)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n
logical, intent(in), optional :: no_sign
logical, intent(in), optional :: compact
Return Value character(len=DR4P)
private elemental function strf_I8P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
integer(kind=I8P), intent(in) :: n
Return Value character(len=DI8P)
private elemental function str_I8P(n, no_sign) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n
logical, intent(in), optional :: no_sign
Return Value character(len=DI8P)
private elemental function strf_I4P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
integer(kind=I4P), intent(in) :: n
Return Value character(len=DI4P)
private elemental function str_I4P(n, no_sign) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n
logical, intent(in), optional :: no_sign
Return Value character(len=DI4P)
private elemental function strf_I2P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
integer(kind=I2P), intent(in) :: n
Return Value character(len=DI2P)
private elemental function str_I2P(n, no_sign) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n
logical, intent(in), optional :: no_sign
Return Value character(len=DI2P)
private elemental function strf_I1P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
integer(kind=I1P), intent(in) :: n
Return Value character(len=DI1P)
private elemental function str_I1P(n, no_sign) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n
logical, intent(in), optional :: no_sign
Return Value character(len=DI1P)
private elemental function str_bol(n) result(str)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: n
Return Value character(len=1)
private pure function str_a_R8P(n, no_sign, separator, delimiters, compact) result(str)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n(:)
logical, intent(in), optional :: no_sign
character(len=1), intent(in), optional :: separator
character(len=*), intent(in), optional :: delimiters(1:2)
logical, intent(in), optional :: compact
Return Value character(len=:), allocatable
private pure function str_a_R4P(n, no_sign, separator, delimiters, compact) result(str)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n(:)
logical, intent(in), optional :: no_sign
character(len=1), intent(in), optional :: separator
character(len=*), intent(in), optional :: delimiters(1:2)
logical, intent(in), optional :: compact
Return Value character(len=:), allocatable
private pure function str_a_I8P(n, no_sign, separator, delimiters) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n(:)
logical, intent(in), optional :: no_sign
character(len=1), intent(in), optional :: separator
character(len=*), intent(in), optional :: delimiters(1:2)
Return Value character(len=:), allocatable
private pure function str_a_I4P(n, no_sign, separator, delimiters) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n(:)
logical, intent(in), optional :: no_sign
character(len=1), intent(in), optional :: separator
character(len=*), intent(in), optional :: delimiters(1:2)
Return Value character(len=:), allocatable
private pure function str_a_I2P(n, no_sign, separator, delimiters) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n(:)
logical, intent(in), optional :: no_sign
character(len=1), intent(in), optional :: separator
character(len=*), intent(in), optional :: delimiters(1:2)
Return Value character(len=:), allocatable
private pure function str_a_I1P(n, no_sign, separator, delimiters) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n(:)
logical, intent(in), optional :: no_sign
character(len=1), intent(in), optional :: separator
character(len=*), intent(in), optional :: delimiters(1:2)
Return Value character(len=:), allocatable
Call graph
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
bctoi_i1p calls str
bctoi_i2p calls str
bctoi_i4p calls str
bctoi_i8p calls str
bcton calls bctoi_i1p, bctoi_i2p, bctoi_i4p, bctoi_i8p