foxy_test_parse_string_nested_tags – Lib_VTK_IO
foxy_test_parse_string_nested_tags Program
29 statements
Source File
Uses
foxy
Calls
Variables
Type Attributes Name Initial
character(len=:), allocatable :: source
character(len=:), allocatable :: parsed
type(xml_file) :: xfile
logical :: test_passed(1)
integer :: f
Source Code
program foxy_test_parse_string_nested_tags
!< FoXy test.
use foxy, only: xml_file
implicit none
character(len=:), allocatable :: source         !< String containing the source XML data.
character(len=:), allocatable :: parsed         !< String containing the parsed XML data.
type(xml_file)                :: xfile          !< XML file handler.
logical                       :: test_passed(1) !< List of passed tests.
integer f
test_passed = .false.
print "(A)", 'Input XML data:'
source = '<tag1 level="1">lorem ipsum...</tag1>'//new_line('a')//&
         '<tag2 level="1" type="self_closing"/>'//new_line('a')//&
         '<tag3 level="1">bye</tag3>'//new_line('a')//&
         '<tag4 level="1">bye bye Mrs. Robinson</tag4>'//new_line('a')//&
         '<tag4 level="1" type="repeat">here we are, again</tag4>'//new_line('a')//&
         '<tag4 level="1" type="repeat_bis">and again</tag4>'//new_line('a')//&
         '<tag4 level="1" type="repeat_tris">forever</tag4>'//new_line('a')//&
         '<tag5>'//new_line('a')//&
         '  <tag6 level="2">content of tag6</tag6>'//new_line('a')//&
         '  <tag7 level="2">'//new_line('a')//&
         '    <tag7 level="3" type="nested">content of tag7 nested</tag7>'//new_line('a')//&
         '    <tag8 level="3">content of tag8</tag8>'//new_line('a')//&
         '    <tag7 level="3" type="nested repeat">content of tag7 nested repeat</tag7>'//new_line('a')//&
         '    <tag9 level="3">'//new_line('a')//&
         '      <tag10 level="4">content of tag10</tag10>'//new_line('a')//&
         '    </tag9>'//new_line('a')//&
         '    <tag7 level="3" type="nested">'//new_line('a')//&
         '      <tag7 level="4" type="nested double">content of tag7 nested double</tag7>'//new_line('a')//&
         '    </tag7>'//new_line('a')//&
         '  </tag7>'//new_line('a')//&
         '</tag5>'//new_line('a')//&
         '<tag11 level="1" type="self_closing"/>'
print "(A)", source
print "(A)", 'Parsing file'
call xfile%parse(string=source)
print "(A)", 'Parsed data'
parsed = xfile%stringify()
print "(A)", parsed
test_passed(1) = trim(adjustl(source))==trim(adjustl(parsed))
print "(A,L1)", 'Is parsed data correct? ', test_passed(1)
print "(A)", 'Parsed data linearized'
print "(A)", xfile%stringify(linearize=.true.)
open(newunit=f, file='source.xml')
write(f,'(A)') source
close(f)
open(newunit=f, file='parsed.xml')
write(f,'(A)') parsed
close(f)
print "(A,L1)", new_line('a')//'Are all tests passed? ', all(test_passed)
endprogram foxy_test_parse_string_nested_tags
Call graph
foxy_test_parse_string_nested_tags calls parse, stringify
parse calls load_file_as_stream, parse_from_string
stringify calls stringify_recursive, stringify, str, attributes, chars, end_tag, is_allocated, self_closing_tag, start_tag
parse_from_string calls add_child, add_tag, get_tag_content, parse_tag_name, set
stringify_recursive calls stringify_recursive, stringify
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
add_child calls add_child_id
get_tag_content calls find_matching_end_tag
self_closing_tag calls attributes
set calls add_multiple_attributes, add_single_attribute, add_stream_attributes
start_tag calls attributes
add_multiple_attributes calls add_single_attribute
add_single_attribute calls alloc_attributes
add_stream_attributes calls add_single_attribute, fill, partition, slice
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string