foxy_test_add_attributes – Lib_VTK_IO
foxy_test_add_attributes Program
34 statements
Source File
Uses
foxy
Calls
Variables
Type Attributes Name Initial
character(len=:), allocatable :: source
character(len=:), allocatable :: parsed
type(xml_tag) :: a_tag
logical :: test_passed(3)
Source Code
program foxy_test_add_attributes
!< FoXy test.
use foxy, only: xml_file, xml_tag
implicit none
character(len=:), allocatable :: source         !< String containing the source XML data.
character(len=:), allocatable :: parsed         !< String containing the parsed XML data.
type(xml_tag)                 :: a_tag          !< XML tag handler.
logical                       :: test_passed(3) !< List of passed tests.
test_passed = .false.
print "(A)", 'source'
source = '<first x="1" y="c" z="2">lorem ipsum...</first>'
print "(A)", source
print "(A)", 'created'
a_tag = xml_tag(name='first', content='lorem ipsum...', attributes=reshape([['x', '1'], ['y', 'c'], ['z', '2']], [2,3]))
parsed = a_tag%stringify()
test_passed(1) = trim(adjustl(source))==trim(adjustl(parsed))
print "(A,L1)", parsed//' Is correct? ', test_passed(1)
call a_tag%add_attributes(attributes_stream='y="3" a="one" b = "two" cc="tree"')
print "(A)", 'source'
source = '<first x="1" y="3" z="2" a="one" b="two" cc="tree">lorem ipsum...</first>'
print "(A)", source
print "(A)", 'created'
parsed = a_tag%stringify()
test_passed(2) = trim(adjustl(source))==trim(adjustl(parsed))
print "(A,L1)", parsed//' Is correct? ', test_passed(2)
call a_tag%add_attributes(attributes_stream='')
print "(A)", 'source'
source = '<first x="1" y="3" z="2" a="one" b="two" cc="tree">lorem ipsum...</first>'
print "(A)", source
print "(A)", 'created'
parsed = a_tag%stringify()
test_passed(3) = trim(adjustl(source))==trim(adjustl(parsed))
print "(A,L1)", parsed//' Is correct? ', test_passed(3)
print "(A,L1)", new_line('a')//'Are all tests passed? ', all(test_passed)
endprogram foxy_test_add_attributes
Call graph
foxy_test_add_attributes calls add_attributes, stringify
stringify calls str, attributes, chars, end_tag, is_allocated, self_closing_tag, start_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
add_multiple_attributes calls add_single_attribute
add_single_attribute calls alloc_attributes
add_stream_attributes calls add_single_attribute, fill, partition, slice
self_closing_tag calls attributes
start_tag calls attributes
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string