volatile_doctest – Lib_VTK_IO
volatile_doctest Program
8 statements
Source File
Uses
penf
befor64
Calls
Contents
Variables
array_I8
Source Code
volatile_doctest
Variables
Type Attributes Name Initial
integer(kind=I8P) :: array_I8(1:4)
Source Code
program volatile_doctest
use befor64
 use befor64
 use penf
 integer(I8P) :: array_I8(1:4)
 call b64_decode(code='FwAAAAAAAABEAQAAAAAAABBwhAEAAAAAAgAAAAAAAAA=',n=array_I8)
 print "(L1)", str(n=array_I8)==str(n=[23_I8P,324_I8P,25456656_I8P,2_I8P])
endprogram volatile_doctest
Call graph
volatile_doctest calls b64_decode, str
b64_decode calls b64_decode_i8, b64_decode_string_a, b64_decode_i1, b64_decode_r8, b64_decode_r8_a, b64_decode_i2_a, b64_decode_i4, b64_decode_i8_a, b64_decode_string, b64_decode_r4, b64_decode_r4_a, b64_decode_i1_a, b64_decode_i2, b64_decode_i4_a
str calls strf_r8p, str_a_r8p, strf_i4p, str_i4p, str_a_i4p, str_bol, strf_r4p, str_r4p, str_a_r4p, strf_i2p, str_i2p, str_a_i2p, str_r8p, strf_i8p, str_i8p, str_a_i8p, strf_i1p, str_i1p, str_a_i1p
b64_decode_i8 calls decode_bits
b64_decode_string_a calls decode_bits, byte_size
str_a_r8p calls str_r8p
b64_decode_i1 calls decode_bits
str_a_i4p calls str_i4p
b64_decode_r8 calls decode_bits
b64_decode_r8_a calls decode_bits
b64_decode_i2_a calls decode_bits
b64_decode_i4 calls decode_bits
str_r4p calls compact_real_string
str_a_r4p calls str_r4p
b64_decode_i8_a calls decode_bits
b64_decode_string calls decode_bits, byte_size
str_a_i2p calls str_i2p
b64_decode_r4 calls decode_bits
b64_decode_r4_a calls decode_bits
b64_decode_i1_a calls decode_bits
str_r8p calls compact_real_string
b64_decode_i2 calls decode_bits
str_a_i8p calls str_i8p
b64_decode_i4_a calls decode_bits
str_a_i1p calls str_i1p
byte_size calls byte_size_i8p, byte_size_i2p, byte_size_r4p, byte_size_i4p, byte_size_i1p, byte_size_r8p, byte_size_chr