volatile_doctest – Lib_VTK_IO
volatile_doctest Program
11 statements
Source File
Uses
penf
stringifor_string_t
Calls
Variables
Type Attributes Name Initial
type(string) :: astring
integer(kind=I8P) :: integer_
logical :: test_passed(1)
Source Code
program volatile_doctest
use stringifor_string_t
 use penf
 type(string) :: astring
 integer(I8P) :: integer_
 logical :: test_passed(1)
 astring = '127'
 integer_ = astring%to_number(kind=1_I8P)
 test_passed(1) = integer_==127_I8P
 print '(L1)', all(test_passed)
endprogram volatile_doctest
Call graph
volatile_doctest calls to_number
to_integer_i1p calls is_integer
to_integer_i2p calls is_integer
to_integer_i4p calls is_integer
to_integer_i8p calls is_integer
to_real_r4p calls is_real
to_real_r8p calls is_real