volatile_doctest – Lib_VTK_IO
volatile_doctest Program
8 statements
Source File
Uses
penf_allocatable_memory
penf
Calls
Variables
Type Attributes Name Initial
real(kind=R16P), allocatable :: a(:)
integer(kind=I4P) :: ulb(2) = [1, 1]
Source Code
program volatile_doctest
use penf_allocatable_memory
 use penf
 real(R16P), allocatable :: a(:)
 integer(I4P)            :: ulb(2)=[1,1]
 call allocate_variable(a, ulb)
 print*, allocated(a)
endprogram volatile_doctest
Call graph
volatile_doctest calls allocate_variable
allocate_variable calls alloc_var_i1p_1d, alloc_var_i1p_2d, alloc_var_i1p_3d, alloc_var_i1p_4d, alloc_var_i1p_5d, alloc_var_i1p_6d, alloc_var_i1p_7d, alloc_var_i2p_1d, alloc_var_i2p_2d, alloc_var_i2p_3d, alloc_var_i2p_4d, alloc_var_i2p_5d, alloc_var_i2p_6d, alloc_var_i2p_7d, alloc_var_i4p_1d, alloc_var_i4p_2d, alloc_var_i4p_3d, alloc_var_i4p_4d, alloc_var_i4p_5d, alloc_var_i4p_6d, alloc_var_i4p_7d, alloc_var_i8p_1d, alloc_var_i8p_2d, alloc_var_i8p_3d, alloc_var_i8p_4d, alloc_var_i8p_5d, alloc_var_i8p_6d, alloc_var_i8p_7d, alloc_var_r4p_1d, alloc_var_r4p_2d, alloc_var_r4p_3d, alloc_var_r4p_4d, alloc_var_r4p_5d, alloc_var_r4p_6d, alloc_var_r4p_7d, alloc_var_r8p_1d, alloc_var_r8p_2d, alloc_var_r8p_3d, alloc_var_r8p_4d, alloc_var_r8p_5d, alloc_var_r8p_6d, alloc_var_r8p_7d
alloc_var_i1p_1d calls str, get_memory_info
alloc_var_i1p_2d calls str, get_memory_info
alloc_var_i1p_3d calls str, get_memory_info
alloc_var_i1p_4d calls str, get_memory_info
alloc_var_i1p_5d calls str, get_memory_info
alloc_var_i1p_6d calls str, get_memory_info
alloc_var_i1p_7d calls str, get_memory_info
alloc_var_i2p_1d calls str, get_memory_info
alloc_var_i2p_2d calls str, get_memory_info
alloc_var_i2p_3d calls str, get_memory_info
alloc_var_i2p_4d calls str, get_memory_info
alloc_var_i2p_5d calls str, get_memory_info
alloc_var_i2p_6d calls str, get_memory_info
alloc_var_i2p_7d calls str, get_memory_info
alloc_var_i4p_1d calls str, get_memory_info
alloc_var_i4p_2d calls str, get_memory_info
alloc_var_i4p_3d calls str, get_memory_info
alloc_var_i4p_4d calls str, get_memory_info
alloc_var_i4p_5d calls str, get_memory_info
alloc_var_i4p_6d calls str, get_memory_info
alloc_var_i4p_7d calls str, get_memory_info
alloc_var_i8p_1d calls str, get_memory_info
alloc_var_i8p_2d calls str, get_memory_info
alloc_var_i8p_3d calls str, get_memory_info
alloc_var_i8p_4d calls str, get_memory_info
alloc_var_i8p_5d calls str, get_memory_info
alloc_var_i8p_6d calls str, get_memory_info
alloc_var_i8p_7d calls str, get_memory_info
alloc_var_r4p_1d calls str, get_memory_info
alloc_var_r4p_2d calls str, get_memory_info
alloc_var_r4p_3d calls str, get_memory_info
alloc_var_r4p_4d calls str, get_memory_info
alloc_var_r4p_5d calls str, get_memory_info
alloc_var_r4p_6d calls str, get_memory_info
alloc_var_r4p_7d calls str, get_memory_info
alloc_var_r8p_1d calls str, get_memory_info
alloc_var_r8p_2d calls str, get_memory_info
alloc_var_r8p_3d calls str, get_memory_info
alloc_var_r8p_4d calls str, get_memory_info
alloc_var_r8p_5d calls str, get_memory_info
alloc_var_r8p_6d calls str, get_memory_info
alloc_var_r8p_7d calls str, get_memory_info
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
get_memory_info calls cton
cton calls ctoi_i1p, ctoi_i2p, ctoi_i4p, ctoi_i8p, ctor_r4p, ctor_r8p
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string