volatile_doctest – Lib_VTK_IO
volatile_doctest Program
8 statements
Source File
Uses
penf_allocatable_memory
penf
Calls
Variables
Type Attributes Name Initial
integer(kind=I1P), allocatable :: a(:,:)
integer(kind=I1P), allocatable :: b(:,:)
Source Code
program volatile_doctest
use penf_allocatable_memory
 use penf
 integer(I1P), allocatable :: a(:,:), b(:,:)
 allocate(b(1:1,1:2))
 call assign_allocatable(a, b)
 print*, allocated(a)
endprogram volatile_doctest
Call graph
volatile_doctest calls assign_allocatable
assign_allocatable calls assign_allocatable_i1p_1d, assign_allocatable_i1p_2d, assign_allocatable_i1p_3d, assign_allocatable_i1p_4d, assign_allocatable_i1p_5d, assign_allocatable_i1p_6d, assign_allocatable_i1p_7d, assign_allocatable_i2p_1d, assign_allocatable_i2p_2d, assign_allocatable_i2p_3d, assign_allocatable_i2p_4d, assign_allocatable_i2p_5d, assign_allocatable_i2p_6d, assign_allocatable_i2p_7d, assign_allocatable_i4p_1d, assign_allocatable_i4p_2d, assign_allocatable_i4p_3d, assign_allocatable_i4p_4d, assign_allocatable_i4p_5d, assign_allocatable_i4p_6d, assign_allocatable_i4p_7d, assign_allocatable_i8p_1d, assign_allocatable_i8p_2d, assign_allocatable_i8p_3d, assign_allocatable_i8p_4d, assign_allocatable_i8p_5d, assign_allocatable_i8p_6d, assign_allocatable_i8p_7d, assign_allocatable_r4p_1d, assign_allocatable_r4p_2d, assign_allocatable_r4p_3d, assign_allocatable_r4p_4d, assign_allocatable_r4p_5d, assign_allocatable_r4p_6d, assign_allocatable_r4p_7d, assign_allocatable_r8p_1d, assign_allocatable_r8p_2d, assign_allocatable_r8p_3d, assign_allocatable_r8p_4d, assign_allocatable_r8p_5d, assign_allocatable_r8p_6d, assign_allocatable_r8p_7d
assign_allocatable_i1p_1d calls allocate_variable
assign_allocatable_i1p_2d calls allocate_variable
assign_allocatable_i1p_3d calls allocate_variable
assign_allocatable_i1p_4d calls allocate_variable
assign_allocatable_i1p_5d calls allocate_variable
assign_allocatable_i1p_6d calls allocate_variable
assign_allocatable_i1p_7d calls allocate_variable
assign_allocatable_i2p_1d calls allocate_variable
assign_allocatable_i2p_2d calls allocate_variable
assign_allocatable_i2p_3d calls allocate_variable
assign_allocatable_i2p_4d calls allocate_variable
assign_allocatable_i2p_5d calls allocate_variable
assign_allocatable_i2p_6d calls allocate_variable
assign_allocatable_i2p_7d calls allocate_variable
assign_allocatable_i4p_1d calls allocate_variable
assign_allocatable_i4p_2d calls allocate_variable
assign_allocatable_i4p_3d calls allocate_variable
assign_allocatable_i4p_4d calls allocate_variable
assign_allocatable_i4p_5d calls allocate_variable
assign_allocatable_i4p_6d calls allocate_variable
assign_allocatable_i4p_7d calls allocate_variable
assign_allocatable_i8p_1d calls allocate_variable
assign_allocatable_i8p_2d calls allocate_variable
assign_allocatable_i8p_3d calls allocate_variable
assign_allocatable_i8p_4d calls allocate_variable
assign_allocatable_i8p_5d calls allocate_variable
assign_allocatable_i8p_6d calls allocate_variable
assign_allocatable_i8p_7d calls allocate_variable
assign_allocatable_r4p_1d calls allocate_variable
assign_allocatable_r4p_2d calls allocate_variable
assign_allocatable_r4p_3d calls allocate_variable
assign_allocatable_r4p_4d calls allocate_variable
assign_allocatable_r4p_5d calls allocate_variable
assign_allocatable_r4p_6d calls allocate_variable
assign_allocatable_r4p_7d calls allocate_variable
assign_allocatable_r8p_1d calls allocate_variable
assign_allocatable_r8p_2d calls allocate_variable
assign_allocatable_r8p_3d calls allocate_variable
assign_allocatable_r8p_4d calls allocate_variable
assign_allocatable_r8p_5d calls allocate_variable
assign_allocatable_r8p_6d calls allocate_variable
assign_allocatable_r8p_7d calls allocate_variable
allocate_variable calls alloc_var_i1p_1d, alloc_var_i1p_2d, alloc_var_i1p_3d, alloc_var_i1p_4d, alloc_var_i1p_5d, alloc_var_i1p_6d, alloc_var_i1p_7d, alloc_var_i2p_1d, alloc_var_i2p_2d, alloc_var_i2p_3d, alloc_var_i2p_4d, alloc_var_i2p_5d, alloc_var_i2p_6d, alloc_var_i2p_7d, alloc_var_i4p_1d, alloc_var_i4p_2d, alloc_var_i4p_3d, alloc_var_i4p_4d, alloc_var_i4p_5d, alloc_var_i4p_6d, alloc_var_i4p_7d, alloc_var_i8p_1d, alloc_var_i8p_2d, alloc_var_i8p_3d, alloc_var_i8p_4d, alloc_var_i8p_5d, alloc_var_i8p_6d, alloc_var_i8p_7d, alloc_var_r4p_1d, alloc_var_r4p_2d, alloc_var_r4p_3d, alloc_var_r4p_4d, alloc_var_r4p_5d, alloc_var_r4p_6d, alloc_var_r4p_7d, alloc_var_r8p_1d, alloc_var_r8p_2d, alloc_var_r8p_3d, alloc_var_r8p_4d, alloc_var_r8p_5d, alloc_var_r8p_6d, alloc_var_r8p_7d
alloc_var_i1p_1d calls str, get_memory_info
alloc_var_i1p_2d calls str, get_memory_info
alloc_var_i1p_3d calls str, get_memory_info
alloc_var_i1p_4d calls str, get_memory_info
alloc_var_i1p_5d calls str, get_memory_info
alloc_var_i1p_6d calls str, get_memory_info
alloc_var_i1p_7d calls str, get_memory_info
alloc_var_i2p_1d calls str, get_memory_info
alloc_var_i2p_2d calls str, get_memory_info
alloc_var_i2p_3d calls str, get_memory_info
alloc_var_i2p_4d calls str, get_memory_info
alloc_var_i2p_5d calls str, get_memory_info
alloc_var_i2p_6d calls str, get_memory_info
alloc_var_i2p_7d calls str, get_memory_info
alloc_var_i4p_1d calls str, get_memory_info
alloc_var_i4p_2d calls str, get_memory_info
alloc_var_i4p_3d calls str, get_memory_info
alloc_var_i4p_4d calls str, get_memory_info
alloc_var_i4p_5d calls str, get_memory_info
alloc_var_i4p_6d calls str, get_memory_info
alloc_var_i4p_7d calls str, get_memory_info
alloc_var_i8p_1d calls str, get_memory_info
alloc_var_i8p_2d calls str, get_memory_info
alloc_var_i8p_3d calls str, get_memory_info
alloc_var_i8p_4d calls str, get_memory_info
alloc_var_i8p_5d calls str, get_memory_info
alloc_var_i8p_6d calls str, get_memory_info
alloc_var_i8p_7d calls str, get_memory_info
alloc_var_r4p_1d calls str, get_memory_info
alloc_var_r4p_2d calls str, get_memory_info
alloc_var_r4p_3d calls str, get_memory_info
alloc_var_r4p_4d calls str, get_memory_info
alloc_var_r4p_5d calls str, get_memory_info
alloc_var_r4p_6d calls str, get_memory_info
alloc_var_r4p_7d calls str, get_memory_info
alloc_var_r8p_1d calls str, get_memory_info
alloc_var_r8p_2d calls str, get_memory_info
alloc_var_r8p_3d calls str, get_memory_info
alloc_var_r8p_4d calls str, get_memory_info
alloc_var_r8p_5d calls str, get_memory_info
alloc_var_r8p_6d calls str, get_memory_info
alloc_var_r8p_7d calls str, get_memory_info
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
get_memory_info calls cton
cton calls ctoi_i1p, ctoi_i2p, ctoi_i4p, ctoi_i8p, ctor_r4p, ctor_r8p
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string