volatile_doctest – Lib_VTK_IO
volatile_doctest Program
5 statements
Source File
Uses
penf_stringify
penf
Calls
Contents
Source Code
volatile_doctest
Source Code
program volatile_doctest
use penf_stringify
 use penf
 print "(A)", bstr(n=1._R4P)
endprogram volatile_doctest
Call graph
volatile_doctest calls bstr
bstr calls bstr_r4p, bstr_i1p, bstr_i4p, bstr_i2p, bstr_r8p, bstr_i8p