volatile_doctest – Lib_VTK_IO
volatile_doctest Program
12 statements
Source File
Uses:
befor64_pack_data_m
befor64
penf
Calls
Variables
a1 a2 pack
Source Code
volatile_doctest
Variables
Type Attributes Name Initial
integer(kind=I4P) :: a1(1)
integer(kind=I2P) :: a2(1)
integer(kind=I1P), allocatable :: pack(:)
Source Code
program volatile_doctest
use befor64_pack_data_m
 use befor64
 use penf
 integer(I4P)              :: a1(1)
 integer(I2P)              :: a2(1)
 integer(I1P), allocatable :: pack(:)
 a1(1) = 0
 a2(1) = 1
 call pack_data(a1=a1, a2=a2, packed=pack)
 print *, pack(5)
endprogram volatile_doctest
All Programs
add_attributes add_tag create_tag delete_attributes delete_content delete_tag indent_tag parse_file_simple parse_string_simple stringifor_test_csv_naive_parser stringifor_test_parse_large_csv use_module_basic volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest write_tag write_vtm write_vtr write_vts write_vtu
Call graph
volatile_doctest calls pack_data
pack_data calls pack_data_i4_i2, pack_data_i1_r4, pack_data_i2_i1, pack_data_r8_i8, pack_data_i8_i2, pack_data_i8_i4, pack_data_i1_r8, pack_data_r8_r4, pack_data_i1_i4, pack_data_r4_i2, pack_data_r8_i2, pack_data_i8_r4, pack_data_r4_i1, pack_data_i2_i4, pack_data_r8_i1, pack_data_r8_i4, pack_data_i4_r4, pack_data_i8_r8, pack_data_i8_i1, pack_data_i2_i8, pack_data_i1_i2, pack_data_r4_i8, pack_data_i4_i8, pack_data_i1_i8, pack_data_i2_r4, pack_data_r4_i4, pack_data_i2_r8, pack_data_r4_r8, pack_data_i4_i1, pack_data_i4_r8