volatile_doctest – Lib_VTK_IO
volatile_doctest Program
7 statements
Source File
Uses
penf_stringify
penf
Calls
Variables
Type Attributes Name Initial
character(len=128) :: b
Source Code
program volatile_doctest
use penf_stringify
 use penf
 character(128) :: b
 b = bstr(n=1._R16P)
 print "(A)", b(17:)
endprogram volatile_doctest
Call graph
volatile_doctest calls bstr
bstr calls bstr_i1p, bstr_i2p, bstr_i4p, bstr_i8p, bstr_r4p, bstr_r8p