volatile_doctest – Lib_VTK_IO
volatile_doctest Program
5 statements
Source File
Uses:
penf_stringify
penf
Calls
Source Code
volatile_doctest
Source Code
program volatile_doctest
use penf_stringify
 use penf
 print FR8P, bcton('0000000000000000000000000000000000000000000000001111000000111111', knd=1._R8P)
endprogram volatile_doctest
All Programs
add_attributes add_tag create_tag delete_attributes delete_content delete_tag indent_tag parse_file_simple parse_string_simple stringifor_test_csv_naive_parser stringifor_test_parse_large_csv use_module_basic volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest write_tag write_vtm write_vtr write_vts write_vtu
Call graph
volatile_doctest calls bcton
bcton calls bctor_r4p, bctoi_i4p, bctoi_i8p, bctor_r8p, bctor_r16p, bctoi_i2p, bctoi_i1p
bctoi_i4p calls str
bctoi_i8p calls str
bctoi_i2p calls str
bctoi_i1p calls str
str calls str_a_i4p, str_a_i8p, str_i2p, strf_i4p, strf_i1p, str_a_i1p, str_r4p, strf_r4p, str_r16p, str_i4p, str_a_r16p, strf_r16p, strf_r8p, str_i1p, str_a_i2p, str_a_r8p, str_bol, strf_i8p, str_i8p, str_a_r4p, strf_i2p, str_r8p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_i1p calls str_i1p
str_r4p calls compact_real_string
str_r16p calls compact_real_string
str_a_r16p calls str_r16p
str_a_i2p calls str_i2p
str_a_r8p calls str_r8p
str_a_r4p calls str_r4p
str_r8p calls compact_real_string