vtk_fortran_write_pvts – Lib_VTK_IO
vtk_fortran_write_pvts Program
56 statements
Source File
Uses
vtk_fortran
penf
Calls
Variables
Type Attributes Name Initial
integer(kind=I4P), parameter :: nx1 = 0_I4P
integer(kind=I4P), parameter :: nx2 = 9_I4P
integer(kind=I4P), parameter :: ny1 = 0_I4P
integer(kind=I4P), parameter :: ny2 = 5_I4P
integer(kind=I4P), parameter :: nz1 = 0_I4P
integer(kind=I4P), parameter :: nz2 = 5_I4P
integer(kind=I4P), parameter :: nx1_p(1:2) = [nx1, 4_I4P]
integer(kind=I4P), parameter :: nx2_p(1:2) = [4_I4P, nx2]
integer(kind=I4P), parameter :: nn = (nx2-nx1+1)*(ny2-ny1+1)*(nz2-nz1+1)
integer(kind=I4P), parameter :: nn_p(1:2) = [(nx2_p(1)-nx1+1)*(ny2-ny1+1)*(nz2-nz1+1), (nx2_p(2)-nx2_p(1)+1)*(ny2-ny1+1)*(nz2-nz1+1)]
real(kind=R8P), dimension(nx1:nx2,ny1:ny2,nz1:nz2) :: x
real(kind=R8P), dimension(nx1:nx2,ny1:ny2,nz1:nz2) :: y
real(kind=R8P), dimension(nx1:nx2,ny1:ny2,nz1:nz2) :: z
integer(kind=I4P), dimension(nx1:nx2,ny1:ny2,nz1:nz2) :: v
integer(kind=I4P) :: i
integer(kind=I4P) :: j
integer(kind=I4P) :: k
Subroutines
subroutine write_vts(part, filename)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: part
character(len=*), intent(in) :: filename
subroutine write_pvts(filename, parts_filename)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: parts_filename(:)
Source Code
program vtk_fortran_write_pvts
!< VTK_Fortran test for Parallel (partioned) Structured Grid.
use penf
use vtk_fortran, only : vtk_file, pvtk_file
implicit none
!< The mesh is a simple prism partitioned into two pieces along x direction at ordinate i=nx2_p(1).
!<```
!< y ^
!<   |               ny2 +-----------------+--------------+
!<   |                   |                 |              |
!<   |                   |                 |              |
!<   |                   |                 |              |
!<   |                   |                 |              |
!<   o-------->      ny1 +-----------------+--------------+
!<            x         nx1               i=nx2_p(1)     nx2
!<```
integer(I4P), parameter :: nx1=0_I4P, nx2=9_I4P, ny1=0_I4P, ny2=5_I4P, nz1=0_I4P, nz2=5_I4P !< Whole extents.
integer(I4P), parameter :: nx1_p(1:2)=[nx1, 4_I4P]                                          !< Lower x extents.
integer(I4P), parameter :: nx2_p(1:2)=[4_I4P, nx2]                                          !< Upper x extents.
integer(I4P), parameter :: nn       = (nx2     -nx1     +1)*(ny2-ny1+1)*(nz2-nz1+1)         !< Whole number of points.
integer(I4P), parameter :: nn_p(1:2)=[(nx2_p(1)-nx1     +1)*(ny2-ny1+1)*(nz2-nz1+1),&
                                      (nx2_p(2)-nx2_p(1)+1)*(ny2-ny1+1)*(nz2-nz1+1)]        !< Partinoned number of points.
real(R8P),    dimension(nx1:nx2,ny1:ny2,nz1:nz2) :: x, y, z !< Mesh coordinates.
integer(I4P), dimension(nx1:nx2,ny1:ny2,nz1:nz2) :: v       !< Noces-centered value.
integer(I4P)                                     :: i       !< Counter.
integer(I4P)                                     :: j       !< Counter.
integer(I4P)                                     :: k       !< Counter.
! inizialize data
do k=nz1, nz2
   do j=ny1, ny2
      do i=nx1, nx2
         x(i, j, k) = i*1._R8P
         y(i, j, k) = j*1._R8P
         z(i, j, k) = k*1._R8P
         v(i, j, k) = i*j*k
      enddo
   enddo
enddo
call write_vts(part=1, filename='vtkfortran_write_pvts_01.vts')
call write_vts(part=2, filename='vtkfortran_write_pvts_02.vts')
call write_pvts(filename='vtkfortran_write_pvts.pvts', parts_filename=['vtkfortran_write_pvts_01.vts', &
                                                                       'vtkfortran_write_pvts_02.vts'])
contains
   subroutine write_vts(part, filename)
   !< Write VTS parts.
   integer(I4P), intent(in) :: part         !< Part to be saved [1,2].
   character(*), intent(in) :: filename     !< Output file name.
   type(vtk_file)           :: a_vtk_file   !< A VTK file.
   integer(I4P)             :: error        !< Status error.
   error = a_vtk_file%initialize(format='binary', filename=filename, mesh_topology='StructuredGrid', &
                                 nx1=nx1_p(part), nx2=nx2_p(part), ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2)
   error = a_vtk_file%xml_writer%write_piece(nx1=nx1_p(part), nx2=nx2_p(part), ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2)
   error = a_vtk_file%xml_writer%write_geo(n=nn_p(part), x=x(nx1_p(part):nx2_p(part),:,:), &
                                                         y=y(nx1_p(part):nx2_p(part),:,:), &
                                                         z=z(nx1_p(part):nx2_p(part),:,:))
   error = a_vtk_file%xml_writer%write_dataarray(location='node', action='open')
   error = a_vtk_file%xml_writer%write_dataarray(data_name='int32_scalar', x=v(nx1_p(part):nx2_p(part),:,:), &
                                                 one_component=.true.)
   error = a_vtk_file%xml_writer%write_dataarray(location='node', action='close')
   error = a_vtk_file%xml_writer%write_piece()
   error = a_vtk_file%finalize()
   endsubroutine write_vts
   subroutine write_pvts(filename, parts_filename)
   !< Write PVTS.
   character(*), intent(in) :: filename          !< Output file name.
   character(*), intent(in) :: parts_filename(:) !< Parts file name.
   type(pvtk_file)          :: a_pvtk_file       !< A parallel (partioned) VTK file.
   integer(I4P)             :: error             !< Status error.
   error = a_pvtk_file%initialize(filename=filename, mesh_topology='PStructuredGrid', mesh_kind="Float64", &
                                  nx1=nx1, nx2=nx2, ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2)
   error = a_pvtk_file%xml_writer%write_dataarray(location='node', action='open')
   error = a_pvtk_file%xml_writer%write_parallel_dataarray(data_name='int32_scalar', &
                                                           data_type='Int32', &
                                                           number_of_components=1)
   error = a_pvtk_file%xml_writer%write_dataarray(location='node', action='close')
   error = a_pvtk_file%xml_writer%write_parallel_geo(source=parts_filename(1), &
                                                     nx1=nx1, nx2=nx2_p(1), ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2)
   error = a_pvtk_file%xml_writer%write_parallel_geo(source=parts_filename(2), &
                                                     nx1=nx2_p(1), nx2=nx2_p(2), ny1=ny1, ny2=ny2, nz1=nz1, nz2=nz2)
   error = a_pvtk_file%finalize()
   endsubroutine write_pvts
endprogram vtk_fortran_write_pvts
Call graph
vtk_fortran_write_pvts calls write_pvts, write_vts
write_pvts calls write_dataarray, finalize, initialize, write_parallel_dataarray, write_parallel_geo
write_vts calls write_dataarray, write_geo, write_piece, finalize, initialize
finalize calls finalize
initialize calls initialize, b64_init, penf_init, chars, upper
write_parallel_dataarray calls str, chars, write_self_closing_tag
write_parallel_geo calls str, chars, write_self_closing_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
b64_init calls penf_init
penf_init calls check_endian
write_dataarray1_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray_location_tag calls chars, upper, write_end_tag, write_start_tag
write_geo_rect_data3_rank1_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_rect_data3_rank1_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank2_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank2_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank4_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank4_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank1_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank1_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank3_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank3_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data1_rank2_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data1_rank2_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data3_rank1_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data3_rank1_r8p calls write_dataarray, write_end_tag, write_start_tag
write_piece_end_tag calls write_end_tag
write_piece_start_tag calls str, chars, write_start_tag
write_piece_start_tag_unst calls str, chars, write_start_tag
write_self_closing_tag calls stringify
encode_binary_dataarray calls encode_binary_dataarray1_rank1_i1p, encode_binary_dataarray1_rank1_i2p, encode_binary_dataarray1_rank1_i4p, encode_binary_dataarray1_rank1_i8p, encode_binary_dataarray1_rank1_r4p, encode_binary_dataarray1_rank1_r8p, encode_binary_dataarray1_rank2_i1p, encode_binary_dataarray1_rank2_i2p, encode_binary_dataarray1_rank2_i4p, encode_binary_dataarray1_rank2_i8p, encode_binary_dataarray1_rank2_r4p, encode_binary_dataarray1_rank2_r8p, encode_binary_dataarray1_rank3_i1p, encode_binary_dataarray1_rank3_i2p, encode_binary_dataarray1_rank3_i4p, encode_binary_dataarray1_rank3_i8p, encode_binary_dataarray1_rank3_r4p, encode_binary_dataarray1_rank3_r8p, encode_binary_dataarray1_rank4_i1p, encode_binary_dataarray1_rank4_i2p, encode_binary_dataarray1_rank4_i4p, encode_binary_dataarray1_rank4_i8p, encode_binary_dataarray1_rank4_r4p, encode_binary_dataarray1_rank4_r8p, encode_binary_dataarray3_rank1_i1p, encode_binary_dataarray3_rank1_i2p, encode_binary_dataarray3_rank1_i4p, encode_binary_dataarray3_rank1_i8p, encode_binary_dataarray3_rank1_r4p, encode_binary_dataarray3_rank1_r8p, encode_binary_dataarray3_rank3_i1p, encode_binary_dataarray3_rank3_i2p, encode_binary_dataarray3_rank3_i4p, encode_binary_dataarray3_rank3_i8p, encode_binary_dataarray3_rank3_r4p, encode_binary_dataarray3_rank3_r8p, encode_binary_dataarray6_rank1_i1p, encode_binary_dataarray6_rank1_i2p, encode_binary_dataarray6_rank1_i4p, encode_binary_dataarray6_rank1_i8p, encode_binary_dataarray6_rank1_r4p, encode_binary_dataarray6_rank1_r8p, encode_binary_dataarray6_rank3_i1p, encode_binary_dataarray6_rank3_i2p, encode_binary_dataarray6_rank3_i4p, encode_binary_dataarray6_rank3_i8p, encode_binary_dataarray6_rank3_r4p, encode_binary_dataarray6_rank3_r8p
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls str, chars, attributes, end_tag, is_allocated, self_closing_tag, start_tag
write_dataarray_tag calls str, chars, write_tag
write_end_tag calls stringify
write_start_tag calls stringify
encode_binary_dataarray1_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_i4p calls b64_encode
encode_binary_dataarray1_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i4p calls b64_encode
encode_binary_dataarray1_rank2_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i4p calls b64_encode
encode_binary_dataarray1_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i4p calls b64_encode
encode_binary_dataarray1_rank4_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_r8p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i4p calls b64_encode
encode_binary_dataarray3_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i4p calls b64_encode
encode_binary_dataarray3_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_r8p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i4p calls b64_encode
encode_binary_dataarray6_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i4p calls b64_encode
encode_binary_dataarray6_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_r8p calls b64_encode, pack_data
self_closing_tag calls attributes
start_tag calls attributes
write_tag calls stringify
b64_encode calls b64_encode_i1, b64_encode_i1_a, b64_encode_i2, b64_encode_i2_a, b64_encode_i4, b64_encode_i4_a, b64_encode_i8, b64_encode_i8_a, b64_encode_r4, b64_encode_r4_a, b64_encode_r8, b64_encode_r8_a, b64_encode_string, b64_encode_string_a
pack_data calls pack_data_i1_i2, pack_data_i1_i4, pack_data_i1_i8, pack_data_i1_r4, pack_data_i1_r8, pack_data_i2_i1, pack_data_i2_i4, pack_data_i2_i8, pack_data_i2_r4, pack_data_i2_r8, pack_data_i4_i1, pack_data_i4_i2, pack_data_i4_i8, pack_data_i4_r4, pack_data_i4_r8, pack_data_i8_i1, pack_data_i8_i2, pack_data_i8_i4, pack_data_i8_r4, pack_data_i8_r8, pack_data_r4_i1, pack_data_r4_i2, pack_data_r4_i4, pack_data_r4_i8, pack_data_r4_r8, pack_data_r8_i1, pack_data_r8_i2, pack_data_r8_i4, pack_data_r8_i8, pack_data_r8_r4
b64_encode_i1 calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_string calls byte_size, encode_bits
b64_encode_string_a calls byte_size, encode_bits
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p