add_multiple_attributes – Lib_VTK_IO
add_multiple_attributes Subroutine
9 statements
Source File
private pure subroutine add_multiple_attributes(self, attributes, sanitize_values)
Type Bound
xml_tag
Arguments
Type Intent Optional Attributes Name
class(xml_tag), intent(inout) :: self
character(len=*), intent(in) :: attributes(1:,1:)
logical, intent(in), optional :: sanitize_values
Calls
Called by
Source Code
  pure subroutine add_multiple_attributes(self, attributes, sanitize_values)
  !< Add list of attributes name/value pairs.
  class(xml_tag), intent(inout)        :: self              !< XML tag.
  character(*),   intent(in)           :: attributes(1:,1:) !< Attribute name/value pair list [1:2,1:].
  logical,        intent(in), optional :: sanitize_values   !< Sanitize attribute values.
  integer(I4P)                         :: a                 !< Counter.
  do a=1, size(attributes, dim=2)
    ! not efficient: many reallocation, but safe
    call self%add_single_attribute(attribute=attributes(1:,a), sanitize_value=sanitize_values)
  enddo
  endsubroutine add_multiple_attributes
Call graph
add_multiple_attributes calls add_single_attribute
add_single_attribute calls alloc_attributes
set calls add_multiple_attributes
create_tag_flat calls set
create_tag_nested calls set
add_attributes calls add_attributes
create_tag calls set
xml_tag calls create_tag_flat, create_tag_nested