b64_decode_string – Lib_VTK_IO
b64_decode_string Subroutine
9 statements
Source File
private elemental subroutine b64_decode_string(code, s)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
character(len=*), intent(out) :: s
Calls
Called by
Source Code
   elemental subroutine b64_decode_string(code, s)
   !< Decode a base64 code into a scalar string.
   !<
   !<```fortran
   !< use befor64
   !< use penf
   !< character(:), allocatable :: code64
   !< code64 = repeat(' ',5)
   !< call b64_decode(code='aGVsbG8=',s=code64)
   !< print "(L1)", code64=='hello'
   !<```
   !=> T <<<
   character(*), intent(in)  :: code    !< Encoded scalar.
   character(*), intent(out) :: s       !< String to be decoded.
   integer(I1P), allocatable :: nI1P(:) !< One byte integer array containing n.
   allocate(nI1P(1:byte_size(s))) ; nI1P = 0_I1P
   call decode_bits(code=code,bits=nI1P)
   s = transfer(nI1P,s)
   endsubroutine b64_decode_string
Call graph
b64_decode_string calls byte_size, decode_bits
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p
b64_decode calls b64_decode_string
b64_decode_up calls b64_decode_string