b64_init – Lib_VTK_IO
b64_init Subroutine
4 statements
Source File
public subroutine b64_init()
Arguments
None
Calls
Called by
Source Code
   subroutine b64_init()
   !< Initialize the BeFoR64 library.
   !<
   !< @note This procedure **must** be called before encoding/decoding anything!
   !<
   !<```fortran
   !< use befor64
   !< call b64_init
   !< print "(L1)", is_b64_initialized
   !<```
   !=> T <<<
   if (.not.is_initialized) call penf_init
   is_b64_initialized = .true.
   endsubroutine b64_init
Call graph
b64_init calls penf_init
penf_init calls check_endian
initialize calls b64_init
volatile_doctest calls b64_init
write_check calls initialize
write_pvts calls initialize
write_slave calls initialize
write_vts calls initialize
vtk_fortran_write_vtm calls initialize
vtk_fortran_write_vtr calls initialize
vtk_fortran_write_vts calls initialize
vtk_fortran_write_vtu calls initialize
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_volatile calls write_check, write_slave