b64_decode_R4 – Lib_VTK_IO
b64_decode_R4 Subroutine
9 statements
Source File
private elemental subroutine b64_decode_R4(code, n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
real(kind=R4P), intent(out) :: n
Calls
Called by
Source Code
   elemental subroutine b64_decode_R4(code, n)
   !< Decode a base64 code into a scalar number (R4P).
   !<
   !<```fortran
   !< use befor64
   !< use penf
   !< real(R4P) :: scalar_R4
   !< call b64_decode(code='AAAAAA==',n=scalar_R4)
   !< print "(L1)", scalar_R4==0._R4P
   !<```
   !=> T <<<
   character(*), intent(in)  :: code    !< Encoded scalar.
   real(R4P),    intent(out) :: n       !< Number to be decoded.
   integer(I1P), allocatable :: nI1P(:) !< One byte integer array containing n.
   allocate(nI1P(1:BYR4P)) ; nI1P = 0_I1P
   call decode_bits(code=code,bits=nI1P)
   n = transfer(nI1P,n)
   endsubroutine b64_decode_R4
Call graph
b64_decode_r4 calls decode_bits
b64_decode calls b64_decode_r4
b64_decode_up calls b64_decode_r4
decode calls b64_decode
volatile_doctest calls b64_decode, decode