chars – Lib_VTK_IO
chars Function
9 statements
Source File
private pure function chars(self) result(raw)
Type Bound
string
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
Return Value character(kind=CK, len=:), allocatable
Called by
Source Code
   pure function chars(self) result(raw)
   !< Return the raw characters data.
   !<
   !<```fortran
   !< type(string) :: astring
   !< astring = 'say all Hello WorLD!'
   !< print '(L1)', astring%chars()=='say all Hello WorLD!'
   !<```
   !=> T <<<
   class(string), intent(in)              :: self !< The string.
   character(kind=CK, len=:), allocatable :: raw  !< Raw characters data.
   if (allocated(self%raw)) then
     raw = self%raw
   else
     raw = ''
   endif
   endfunction chars
Call graph
colorize_str calls chars
glob_character calls chars, glob
read_file calls chars, read_lines
read_line calls chars
write_file calls chars, write_lines
write_line calls chars
glob calls glob_character, glob_string
glob_string calls read_file
read_lines calls read_line
write_lines calls write_line