check_endian – Lib_VTK_IO
check_endian Subroutine
14 statements
Source File
public subroutine check_endian()
Note
The result is stored into the endian global variable.
Arguments
None
Called by
Source Code
   subroutine check_endian()
   !< Check the type of bit ordering (big or little endian) of the running architecture.
   !<
   !> @note The result is stored into the *endian* global variable.
   !<
   !<```fortran
   !< use penf
   !< call check_endian
   !< print *, endian
   !<```
   !=> 1 <<<
   if (is_little_endian()) then
      endian = endianL
   else
      endian = endianB
   endif
   contains
      pure function is_little_endian() result(is_little)
      !< Check if the type of the bit ordering of the running architecture is little endian.
      logical      :: is_little !< Logical output: true is the running architecture uses little endian ordering, false otherwise.
      integer(I1P) :: int1(1:4) !< One byte integer array for casting 4 bytes integer.
      int1 = transfer(1_I4P, int1)
      is_little = (int1(1)==1_I1P)
      endfunction is_little_endian
   endsubroutine check_endian
Call graph
penf_init calls check_endian
volatile_doctest calls check_endian, penf_init, penf_print, b64_init
b64_init calls penf_init
initialize calls penf_init, b64_init
penf_print calls penf_init
write_check calls initialize
write_pvts calls initialize
write_slave calls initialize
write_vts calls initialize
vtk_fortran_write_vtm calls initialize
vtk_fortran_write_vtr calls initialize
vtk_fortran_write_vts calls initialize
vtk_fortran_write_vtu calls initialize
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_volatile calls write_check, write_slave