colorize_default – Lib_VTK_IO
colorize_default Function
21 statements
Source File
private pure function colorize_default(string, color_fg, color_bg, style) result(colorized)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=*), intent(in), optional :: color_fg
character(len=*), intent(in), optional :: color_bg
character(len=*), intent(in), optional :: style
Return Value character(len=:),allocatable
Calls
Called by
Contents
Source Code
colorize_default
Source Code
   pure function colorize_default(string, color_fg, color_bg, style) result(colorized)
   !< Colorize and stylize strings, DEFAULT kind.
   character(len=*), intent(in)           :: string    !< Input string.
   character(len=*), intent(in), optional :: color_fg  !< Foreground color definition.
   character(len=*), intent(in), optional :: color_bg  !< Background color definition.
   character(len=*), intent(in), optional :: style     !< Style definition.
   character(len=:), allocatable          :: colorized !< Colorized string.
   integer(int32)                         :: i         !< Counter.
   colorized = string
   if (present(color_fg)) then
      i = color_index(upper(color_fg))
      if (i>0) colorized = CODE_START//trim(COLORS_FG(2, i))//CODE_END//colorized//CODE_CLEAR
   endif
   if (present(color_bg)) then
      i = color_index(upper(color_bg))
      if (i>0) colorized = CODE_START//trim(COLORS_BG(2, i))//CODE_END//colorized//CODE_CLEAR
   endif
   if (present(style)) then
      i = style_index(upper(style))
      if (i>0) colorized = CODE_START//trim(STYLES(2, i))//CODE_END//colorized//CODE_CLEAR
   endif
   endfunction colorize_default
Call graph
colorize_default calls color_index, style_index, upper
colorize calls colorize_default
colors_samples calls colorize
face_test_colors calls colorize
colorize_str calls colorize
face_test_styles calls colorize
styles_samples calls colorize
face_test_basic calls colors_samples, styles_samples