create_tag_nested – Lib_VTK_IO
create_tag_nested Function
18 statements
Source File
private pure function create_tag_nested(name, content, attribute, attributes, attributes_stream, sanitize_attributes_value, pos, indent, is_content_indented, id, level, parent_id, attributes_stream_alloc, content_alloc) result(tag)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
type(xml_tag), intent(in) :: content
character(len=*), intent(in), optional :: attribute(1:)
character(len=*), intent(in), optional :: attributes(1:,1:)
character(len=*), intent(in), optional :: attributes_stream
logical, intent(in), optional :: sanitize_attributes_value
integer(kind=I4P), intent(in), optional :: pos(1:)
integer(kind=I4P), intent(in), optional :: indent
logical, intent(in), optional :: is_content_indented
integer(kind=I4P), intent(in), optional :: id
integer(kind=I4P), intent(in), optional :: level
integer(kind=I4P), intent(in), optional :: parent_id
character(len=:), intent(in), optional, allocatable :: attributes_stream_alloc
character(len=:), intent(in), optional, allocatable :: content_alloc
Return Value type(xml_tag)
Calls
Called by
Source Code
   pure function create_tag_nested(name, content, attribute, attributes, attributes_stream, sanitize_attributes_value, pos, indent,&
                                   is_content_indented, id, level, parent_id, attributes_stream_alloc, content_alloc) result(tag)
   !< Return an instance of xml tag with value being a nested tag.
   character(*),              intent(in)           :: name                      !< Tag name.
   type(xml_tag),             intent(in)           :: content                   !< Tag value as nested tag..
   character(*),              intent(in), optional :: attribute(1:)             !< Attribute name/value pair [1:2].
   character(*),              intent(in), optional :: attributes(1:,1:)         !< Attributes list of name/value pairs [1:2,1:].
   character(*),              intent(in), optional :: attributes_stream         !< Attributes list as single stream.
   logical,                   intent(in), optional :: sanitize_attributes_value !< Sanitize attributes value.
   integer(I4P),              intent(in), optional :: pos(1:)                   !< Characters position (in source) indexes.
   integer(I4P),              intent(in), optional :: indent                    !< Number of indent-white-spaces.
   logical,                   intent(in), optional :: is_content_indented       !< Activate value indentation.
   integer(I4P),              intent(in), optional :: id                        !< Uniq ID.
   integer(I4P),              intent(in), optional :: level                     !< Tag hierarchy level.
   integer(I4P),              intent(in), optional :: parent_id                 !< Parent uniq ID.
   character(:), allocatable, intent(in), optional :: attributes_stream_alloc   !< Attributes list stream, allocatable input.
   character(:), allocatable, intent(in), optional :: content_alloc             !< Tag value, allocatable input.
   type(xml_tag)                                   :: tag                       !< XML tag.
   call tag%set(name=name,                                           &
                attribute=attribute,                                 &
                attributes=attributes,                               &
                content=content%stringify(),                         &
                sanitize_attributes_value=sanitize_attributes_value, &
                attributes_stream=attributes_stream,                 &
                pos=pos,                                             &
                indent=indent,                                       &
                is_content_indented=is_content_indented,             &
                id=id,                                               &
                level=level,                                         &
                parent_id=parent_id,                                 &
                attributes_stream_alloc=attributes_stream_alloc,     &
                content_alloc=content_alloc)
   endfunction create_tag_nested
Call graph
create_tag_nested calls set, stringify
set calls add_multiple_attributes, add_single_attribute, add_stream_attributes
stringify calls str, attributes, chars, end_tag, is_allocated, self_closing_tag, start_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
add_multiple_attributes calls add_single_attribute
add_single_attribute calls alloc_attributes
add_stream_attributes calls add_single_attribute, fill, partition, slice
self_closing_tag calls attributes
start_tag calls attributes
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
xml_tag calls create_tag_nested