ctoi_I4P – Lib_VTK_IO
ctoi_I4P Function
16 statements
Source File
private function ctoi_I4P(str, knd, pref, error) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer(kind=I4P), intent(in) :: knd
character(len=*), intent(in), optional :: pref
integer(kind=I4P), intent(out), optional :: error
Return Value integer(kind=I4P)
Called by
Source Code
   function ctoi_I4P(str, knd, pref, error) result(n)
   !< Convert string to integer.
   !<
   !<```fortran
   !< use penf
   !< print FI4P, cton(str='-1', knd=1_I4P)
   !<```
   !=> -1 <<<
   character(*),           intent(in)  :: str   !< String containing input number.
   integer(I4P),           intent(in)  :: knd   !< Number kind.
   character(*), optional, intent(in)  :: pref  !< Prefixing string.
   integer(I4P), optional, intent(out) :: error !< Error trapping flag: 0 no errors, >0 error occurs.
   integer(I4P)                        :: n     !< Number returned.
   integer(I4P)                        :: err   !< Error trapping flag: 0 no errors, >0 error occurs.
   character(len=:), allocatable       :: prefd !< Prefixing string.
   read(str, *, iostat=err) n ! Casting of str to n.
   if (err/=0) then
     prefd = '' ; if (present(pref)) prefd = pref
     write(stderr, '(A,I1,A)') prefd//' Error: conversion of string "'//str//'" to integer failed! integer(', kind(knd), ')'
   endif
   if (present(error)) error = err
   endfunction ctoi_I4P
Call graph
cton calls ctoi_i4p
get_memory_info calls cton
volatile_doctest calls cton, allocate_variable, assign_allocatable
alloc_var_i1p_1d calls get_memory_info
alloc_var_i1p_2d calls get_memory_info
alloc_var_i1p_3d calls get_memory_info
alloc_var_i1p_4d calls get_memory_info
alloc_var_i1p_5d calls get_memory_info
alloc_var_i1p_6d calls get_memory_info
alloc_var_i1p_7d calls get_memory_info
alloc_var_i2p_1d calls get_memory_info
alloc_var_i2p_2d calls get_memory_info
alloc_var_i2p_3d calls get_memory_info
alloc_var_i2p_4d calls get_memory_info
alloc_var_i2p_5d calls get_memory_info
alloc_var_i2p_6d calls get_memory_info
alloc_var_i2p_7d calls get_memory_info
alloc_var_i4p_1d calls get_memory_info
alloc_var_i4p_2d calls get_memory_info
alloc_var_i4p_3d calls get_memory_info
alloc_var_i4p_4d calls get_memory_info
alloc_var_i4p_5d calls get_memory_info
alloc_var_i4p_6d calls get_memory_info
alloc_var_i4p_7d calls get_memory_info
alloc_var_i8p_1d calls get_memory_info
alloc_var_i8p_2d calls get_memory_info
alloc_var_i8p_3d calls get_memory_info
alloc_var_i8p_4d calls get_memory_info
alloc_var_i8p_5d calls get_memory_info
alloc_var_i8p_6d calls get_memory_info
alloc_var_i8p_7d calls get_memory_info
alloc_var_r16p_1d calls get_memory_info
alloc_var_r16p_2d calls get_memory_info
alloc_var_r16p_3d calls get_memory_info
alloc_var_r16p_4d calls get_memory_info
alloc_var_r16p_5d calls get_memory_info
alloc_var_r16p_6d calls get_memory_info
alloc_var_r16p_7d calls get_memory_info
alloc_var_r4p_1d calls get_memory_info
alloc_var_r4p_2d calls get_memory_info
alloc_var_r4p_3d calls get_memory_info
alloc_var_r4p_4d calls get_memory_info
alloc_var_r4p_5d calls get_memory_info
alloc_var_r4p_6d calls get_memory_info
alloc_var_r4p_7d calls get_memory_info
alloc_var_r8p_1d calls get_memory_info
alloc_var_r8p_2d calls get_memory_info
alloc_var_r8p_3d calls get_memory_info
alloc_var_r8p_4d calls get_memory_info
alloc_var_r8p_5d calls get_memory_info
alloc_var_r8p_6d calls get_memory_info
alloc_var_r8p_7d calls get_memory_info
save_memory_status calls get_memory_info
allocate_variable calls alloc_var_i1p_1d, alloc_var_i1p_2d, alloc_var_i1p_3d, alloc_var_i1p_4d, alloc_var_i1p_5d, alloc_var_i1p_6d, alloc_var_i1p_7d, alloc_var_i2p_1d, alloc_var_i2p_2d, alloc_var_i2p_3d, alloc_var_i2p_4d, alloc_var_i2p_5d, alloc_var_i2p_6d, alloc_var_i2p_7d, alloc_var_i4p_1d, alloc_var_i4p_2d, alloc_var_i4p_3d, alloc_var_i4p_4d, alloc_var_i4p_5d, alloc_var_i4p_6d, alloc_var_i4p_7d, alloc_var_i8p_1d, alloc_var_i8p_2d, alloc_var_i8p_3d, alloc_var_i8p_4d, alloc_var_i8p_5d, alloc_var_i8p_6d, alloc_var_i8p_7d, alloc_var_r4p_1d, alloc_var_r4p_2d, alloc_var_r4p_3d, alloc_var_r4p_4d, alloc_var_r4p_5d, alloc_var_r4p_6d, alloc_var_r4p_7d, alloc_var_r8p_1d, alloc_var_r8p_2d, alloc_var_r8p_3d, alloc_var_r8p_4d, alloc_var_r8p_5d, alloc_var_r8p_6d, alloc_var_r8p_7d
assign_allocatable_i1p_1d calls allocate_variable
assign_allocatable_i1p_2d calls allocate_variable
assign_allocatable_i1p_3d calls allocate_variable
assign_allocatable_i1p_4d calls allocate_variable
assign_allocatable_i1p_5d calls allocate_variable
assign_allocatable_i1p_6d calls allocate_variable
assign_allocatable_i1p_7d calls allocate_variable
assign_allocatable_i2p_1d calls allocate_variable
assign_allocatable_i2p_2d calls allocate_variable
assign_allocatable_i2p_3d calls allocate_variable
assign_allocatable_i2p_4d calls allocate_variable
assign_allocatable_i2p_5d calls allocate_variable
assign_allocatable_i2p_6d calls allocate_variable
assign_allocatable_i2p_7d calls allocate_variable
assign_allocatable_i4p_1d calls allocate_variable
assign_allocatable_i4p_2d calls allocate_variable
assign_allocatable_i4p_3d calls allocate_variable
assign_allocatable_i4p_4d calls allocate_variable
assign_allocatable_i4p_5d calls allocate_variable
assign_allocatable_i4p_6d calls allocate_variable
assign_allocatable_i4p_7d calls allocate_variable
assign_allocatable_i8p_1d calls allocate_variable
assign_allocatable_i8p_2d calls allocate_variable
assign_allocatable_i8p_3d calls allocate_variable
assign_allocatable_i8p_4d calls allocate_variable
assign_allocatable_i8p_5d calls allocate_variable
assign_allocatable_i8p_6d calls allocate_variable
assign_allocatable_i8p_7d calls allocate_variable
assign_allocatable_r16p_1d calls allocate_variable
assign_allocatable_r16p_2d calls allocate_variable
assign_allocatable_r16p_3d calls allocate_variable
assign_allocatable_r16p_4d calls allocate_variable
assign_allocatable_r16p_5d calls allocate_variable
assign_allocatable_r16p_6d calls allocate_variable
assign_allocatable_r16p_7d calls allocate_variable
assign_allocatable_r4p_1d calls allocate_variable
assign_allocatable_r4p_2d calls allocate_variable
assign_allocatable_r4p_3d calls allocate_variable
assign_allocatable_r4p_4d calls allocate_variable
assign_allocatable_r4p_5d calls allocate_variable
assign_allocatable_r4p_6d calls allocate_variable
assign_allocatable_r4p_7d calls allocate_variable
assign_allocatable_r8p_1d calls allocate_variable
assign_allocatable_r8p_2d calls allocate_variable
assign_allocatable_r8p_3d calls allocate_variable
assign_allocatable_r8p_4d calls allocate_variable
assign_allocatable_r8p_5d calls allocate_variable
assign_allocatable_r8p_6d calls allocate_variable
assign_allocatable_r8p_7d calls allocate_variable
assign_allocatable calls assign_allocatable_i1p_1d, assign_allocatable_i1p_2d, assign_allocatable_i1p_3d, assign_allocatable_i1p_4d, assign_allocatable_i1p_5d, assign_allocatable_i1p_6d, assign_allocatable_i1p_7d, assign_allocatable_i2p_1d, assign_allocatable_i2p_2d, assign_allocatable_i2p_3d, assign_allocatable_i2p_4d, assign_allocatable_i2p_5d, assign_allocatable_i2p_6d, assign_allocatable_i2p_7d, assign_allocatable_i4p_1d, assign_allocatable_i4p_2d, assign_allocatable_i4p_3d, assign_allocatable_i4p_4d, assign_allocatable_i4p_5d, assign_allocatable_i4p_6d, assign_allocatable_i4p_7d, assign_allocatable_i8p_1d, assign_allocatable_i8p_2d, assign_allocatable_i8p_3d, assign_allocatable_i8p_4d, assign_allocatable_i8p_5d, assign_allocatable_i8p_6d, assign_allocatable_i8p_7d, assign_allocatable_r4p_1d, assign_allocatable_r4p_2d, assign_allocatable_r4p_3d, assign_allocatable_r4p_4d, assign_allocatable_r4p_5d, assign_allocatable_r4p_6d, assign_allocatable_r4p_7d, assign_allocatable_r8p_1d, assign_allocatable_r8p_2d, assign_allocatable_r8p_3d, assign_allocatable_r8p_4d, assign_allocatable_r8p_5d, assign_allocatable_r8p_6d, assign_allocatable_r8p_7d