encode_ascii_dataarray1_rank2_R16P – Lib_VTK_IO
encode_ascii_dataarray1_rank2_R16P Function
23 statements
Source File
private function encode_ascii_dataarray1_rank2_R16P(x) result(code)
Arguments
Type Intent Optional Attributes Name
real(kind=R16P), intent(in) :: x(1:,1:)
Return Value character(len=:),allocatable
Calls
Contents
Source Code
encode_ascii_dataarray1_rank2_R16P
Source Code
  function encode_ascii_dataarray1_rank2_R16P(x) result(code)
  !< Encode (Base64) a dataarray with 1 components of rank 2 (R16P).
  real(R16P),      intent(in)   :: x(1:,1:) !< Data variable
  character(len=:), allocatable :: code     !< Encoded base64 dataarray.
  integer(I4P)                  :: n1       !< Counter.
  integer(I4P)                  :: n2       !< Counter.
  integer(I4P)                  :: l        !< Length
  integer(I4P)                  :: sp       !< String pointer
  integer(I4P)                  :: size_n1  !< Dimension 1 size
  integer(I4P)                  :: size_n2  !< Dimension 2 size
  size_n1 = size(x, dim=1)
  size_n2 = size(x, dim=2)
  l = DR16P + 1
  sp = 0
  code = repeat(' ',l*size_n1*size_n2)
  do n2=1, size(x, dim=2)
    do n1=1, size(x, dim=1)-1
      code(sp+1:sp+l) = str(n=x(n1, n2))//' '
      sp = sp + l
    enddo
    code(sp+1:sp+l) = ' '//str(n=x(size(x, dim=1), n2))
    sp = sp + l
  enddo
  endfunction encode_ascii_dataarray1_rank2_R16P
Call graph
encode_ascii_dataarray1_rank2_r16p calls str
str calls strf_r8p, str_a_r8p, str_i4p, strf_i4p, str_a_i4p, str_bol, strf_r4p, str_r4p, str_a_r4p, strf_i2p, str_i2p, str_a_i2p, str_r8p, strf_i8p, str_i8p, str_a_i8p, strf_i1p, str_i1p, str_a_i1p
str_a_r8p calls str_r8p
str_a_i4p calls str_i4p
str_r4p calls compact_real_string
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_r8p calls compact_real_string
str_a_i8p calls str_i8p
str_a_i1p calls str_i1p