encode_binary_dataarray6_rank1_I2P – Lib_VTK_IO
encode_binary_dataarray6_rank1_I2P Function
15 statements
Source File
private function encode_binary_dataarray6_rank1_I2P(u, v, w, x, y, z) result(code)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: u(1:)
integer(kind=I2P), intent(in) :: v(1:)
integer(kind=I2P), intent(in) :: w(1:)
integer(kind=I2P), intent(in) :: x(1:)
integer(kind=I2P), intent(in) :: y(1:)
integer(kind=I2P), intent(in) :: z(1:)
Return Value character(len=:),allocatable
Calls
Called by
Contents
Source Code
encode_binary_dataarray6_rank1_I2P
Source Code
  function encode_binary_dataarray6_rank1_I2P(u, v, w, x, y, z) result(code)
  !< Encode (Base64) a dataarray with 6 components of rank 1 (I2P).
  integer(I2P), intent(in)      :: u(1:)  !< U component.
  integer(I2P), intent(in)      :: v(1:)  !< V component.
  integer(I2P), intent(in)      :: w(1:)  !< W component.
  integer(I2P), intent(in)      :: x(1:)  !< X component.
  integer(I2P), intent(in)      :: y(1:)  !< Y component.
  integer(I2P), intent(in)      :: z(1:)  !< Z component.
  character(len=:), allocatable :: code   !< Encoded base64 dataarray.
  integer(I1P),     allocatable :: xyz(:) !< Packed data.
  integer(I4P)                  :: nn     !< Number of elements.
  integer(I4P)                  :: n      !< Counter.
  nn = size(x, dim=1)
  call pack_data(a1=[int(6*nn*BYI2P, I4P)], a2=[(u(n), v(n), w(n), x(n), y(n), z(n), n=1, nn)], packed=xyz)
  call b64_encode(n=xyz, code=code)
  endfunction encode_binary_dataarray6_rank1_I2P
Call graph
encode_binary_dataarray6_rank1_i2p calls pack_data, b64_encode
pack_data calls pack_data_r4_r8, pack_data_i8_i2, pack_data_i1_i2, pack_data_i2_r4, pack_data_r8_r4, pack_data_r4_i2, pack_data_i4_r4, pack_data_i2_i1, pack_data_r8_i2, pack_data_i8_r4, pack_data_i4_i1, pack_data_i1_i8, pack_data_r4_i8, pack_data_i8_i1, pack_data_i2_i8, pack_data_r8_i8, pack_data_r4_i1, pack_data_i1_r8, pack_data_i4_i8, pack_data_r8_i1, pack_data_i8_i4, pack_data_i2_r8, pack_data_i1_i4, pack_data_r4_i4, pack_data_i4_r8, pack_data_i2_i4, pack_data_r8_i4, pack_data_i8_r8, pack_data_i4_i2, pack_data_i1_r4
b64_encode calls b64_encode_i8_a, b64_encode_string_a, b64_encode_r8_a, b64_encode_i2, b64_encode_r4_a, b64_encode_i1_a, b64_encode_i4, b64_encode_i2_a, b64_encode_i8, b64_encode_string, b64_encode_r8, b64_encode_i4_a, b64_encode_r4, b64_encode_i1
b64_encode_i8_a calls encode_bits
b64_encode_string_a calls encode_bits, byte_size
b64_encode_r8_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_string calls encode_bits, byte_size
b64_encode_r8 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_i1 calls encode_bits
byte_size calls byte_size_i1p, byte_size_r4p, byte_size_i4p, byte_size_i8p, byte_size_r8p, byte_size_i2p, byte_size_chr
encode_binary_dataarray calls encode_binary_dataarray6_rank1_i2p
write_dataarray1_rank1_r4p calls encode_binary_dataarray
write_dataarray1_rank3_i1p calls encode_binary_dataarray
write_dataarray1_rank2_i4p calls encode_binary_dataarray
write_dataarray3_rank1_r4p calls encode_binary_dataarray
write_dataarray6_rank1_r4p calls encode_binary_dataarray
write_dataarray6_rank3_i4p calls encode_binary_dataarray
write_dataarray1_rank1_i2p calls encode_binary_dataarray
write_dataarray1_rank3_r8p calls encode_binary_dataarray
write_dataarray1_rank4_i8p calls encode_binary_dataarray
write_dataarray3_rank1_i2p calls encode_binary_dataarray
write_dataarray6_rank1_i2p calls encode_binary_dataarray
write_dataarray1_rank2_r4p calls encode_binary_dataarray
write_dataarray1_rank3_i4p calls encode_binary_dataarray
write_dataarray1_rank4_i1p calls encode_binary_dataarray
write_dataarray3_rank3_r4p calls encode_binary_dataarray
write_dataarray3_rank3_i1p calls encode_binary_dataarray
write_dataarray6_rank3_r4p calls encode_binary_dataarray
write_dataarray1_rank1_i8p calls encode_binary_dataarray
write_dataarray1_rank2_i2p calls encode_binary_dataarray
write_dataarray1_rank4_r8p calls encode_binary_dataarray
write_dataarray3_rank1_i8p calls encode_binary_dataarray
write_dataarray6_rank1_i8p calls encode_binary_dataarray
write_dataarray6_rank3_i2p calls encode_binary_dataarray
write_dataarray1_rank1_i1p calls encode_binary_dataarray
write_dataarray1_rank3_r4p calls encode_binary_dataarray
write_dataarray1_rank4_i4p calls encode_binary_dataarray
write_dataarray3_rank1_i1p calls encode_binary_dataarray
write_dataarray3_rank3_i4p calls encode_binary_dataarray
write_dataarray6_rank1_i1p calls encode_binary_dataarray
write_dataarray1_rank1_r8p calls encode_binary_dataarray
write_dataarray1_rank2_i8p calls encode_binary_dataarray
write_dataarray1_rank3_i2p calls encode_binary_dataarray
write_dataarray3_rank1_r8p calls encode_binary_dataarray
write_dataarray3_rank3_i8p calls encode_binary_dataarray
write_dataarray6_rank1_r8p calls encode_binary_dataarray
write_dataarray6_rank3_i8p calls encode_binary_dataarray
write_dataarray1_rank1_i4p calls encode_binary_dataarray
write_dataarray1_rank2_i1p calls encode_binary_dataarray
write_dataarray1_rank4_r4p calls encode_binary_dataarray
write_dataarray3_rank1_i4p calls encode_binary_dataarray
write_dataarray6_rank1_i4p calls encode_binary_dataarray
write_dataarray6_rank3_i1p calls encode_binary_dataarray
write_dataarray1_rank2_r8p calls encode_binary_dataarray
write_dataarray1_rank3_i8p calls encode_binary_dataarray
write_dataarray1_rank4_i2p calls encode_binary_dataarray
write_dataarray3_rank3_r8p calls encode_binary_dataarray
write_dataarray3_rank3_i2p calls encode_binary_dataarray
write_dataarray6_rank3_r8p calls encode_binary_dataarray