finalize – Lib_VTK_IO
finalize Function
8 statements
Source File
private function finalize(self) result(error)
Type Bound
xml_writer_binary_local
Arguments
Type Intent Optional Attributes Name
class(xml_writer_binary_local), intent(inout) :: self
Return Value integer(kind=I4P)
Calls
Source Code
   function finalize(self) result(error)
   !< Finalize writer.
   class(xml_writer_binary_local), intent(inout) :: self  !< Writer.
   integer(I4P)                                  :: error !< Error status.
   call self%write_end_tag(name=self%topology%chars())
   call self%write_end_tag(name='VTKFile')
   call self%close_xml_file
   error = self%error
   endfunction finalize
Call graph
finalize calls chars, close_xml_file, write_end_tag
write_end_tag calls stringify
stringify calls chars, str, attributes, end_tag, is_allocated, self_closing_tag, start_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
self_closing_tag calls attributes
start_tag calls attributes
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string