finalize – Lib_VTK_IO
finalize Function
8 statements
Source File
private function finalize(self) result(error)
Type Bound
xml_writer_binary_local
Arguments
Type Intent Optional Attributes Name
class(xml_writer_binary_local), intent(inout) :: self
Return Value integer(kind=I4P)
Calls
Source Code
   function finalize(self) result(error)
   !< Finalize writer.
   class(xml_writer_binary_local), intent(inout) :: self  !< Writer.
   integer(I4P)                                  :: error !< Error status.
   call self%write_end_tag(name=self%topology%chars())
   call self%write_end_tag(name='VTKFile')
   call self%close_xml_file
   error = self%error
   endfunction finalize
Call graph
finalize calls chars, close_xml_file, write_end_tag
write_end_tag calls stringify
stringify calls chars, end_tag, is_allocated, self_closing_tag, start_tag
self_closing_tag calls attributes
start_tag calls attributes