get – Lib_VTK_IO
get Subroutine
6 statements
Source File
private elemental subroutine get(self, source)
Type Bound
xml_tag
Arguments
Type Intent Optional Attributes Name
class(xml_tag), intent(inout) :: self
character(len=*), intent(in) :: source
Calls
Called by
Source Code
   elemental subroutine get(self, source)
   !< Get the tag content and attributes from source after tag_name and attributes names have been set.
   class(xml_tag), intent(inout) :: self   !< XML tag.
   character(*),   intent(in)    :: source !< String containing data.
   call self%get_value(source=source)
   call self%get_attributes(source=source)
   ! call self%get_nested()
   endsubroutine get
Call graph
get calls get_attributes, get_value
parse calls get
search calls parse
foxy_test_create_tag calls parse
get_content calls search
content calls get_content