ioffset_update – Lib_VTK_IO
ioffset_update Subroutine
9 statements
Source File
private elemental subroutine ioffset_update(self, n_byte)
Type Bound
xml_writer_appended
Arguments
Type Intent Optional Attributes Name
class(xml_writer_appended), intent(inout) :: self
integer(kind=I4P), intent(in) :: n_byte
Called by
Source Code
  elemental subroutine ioffset_update(self, n_byte)
  !< Update ioffset count.
  class(xml_writer_appended), intent(inout) :: self  !< Writer.
  integer(I4P),               intent(in)    :: n_byte !< Number of bytes saved.
  if (self%encoding=='raw') then
    self%ioffset = self%ioffset + BYI4P + n_byte
  else
    self%ioffset = self%ioffset + ((n_byte + BYI4P + 2_I4P)/3_I4P)*4_I4P
  endif
  endsubroutine ioffset_update
Call graph
write_dataarray1_rank1_i1p calls ioffset_update
write_dataarray1_rank1_i2p calls ioffset_update
write_dataarray1_rank1_i4p calls ioffset_update
write_dataarray1_rank1_i8p calls ioffset_update
write_dataarray1_rank1_r4p calls ioffset_update
write_dataarray1_rank1_r8p calls ioffset_update
write_dataarray1_rank2_i1p calls ioffset_update
write_dataarray1_rank2_i2p calls ioffset_update
write_dataarray1_rank2_i4p calls ioffset_update
write_dataarray1_rank2_i8p calls ioffset_update
write_dataarray1_rank2_r4p calls ioffset_update
write_dataarray1_rank2_r8p calls ioffset_update
write_dataarray1_rank3_i1p calls ioffset_update
write_dataarray1_rank3_i2p calls ioffset_update
write_dataarray1_rank3_i4p calls ioffset_update
write_dataarray1_rank3_i8p calls ioffset_update
write_dataarray1_rank3_r4p calls ioffset_update
write_dataarray1_rank3_r8p calls ioffset_update
write_dataarray1_rank4_i1p calls ioffset_update
write_dataarray1_rank4_i2p calls ioffset_update
write_dataarray1_rank4_i4p calls ioffset_update
write_dataarray1_rank4_i8p calls ioffset_update
write_dataarray1_rank4_r4p calls ioffset_update
write_dataarray1_rank4_r8p calls ioffset_update
write_dataarray3_rank1_i1p calls ioffset_update
write_dataarray3_rank1_i2p calls ioffset_update
write_dataarray3_rank1_i4p calls ioffset_update
write_dataarray3_rank1_i8p calls ioffset_update
write_dataarray3_rank1_r4p calls ioffset_update
write_dataarray3_rank1_r8p calls ioffset_update
write_dataarray3_rank3_i1p calls ioffset_update
write_dataarray3_rank3_i2p calls ioffset_update
write_dataarray3_rank3_i4p calls ioffset_update
write_dataarray3_rank3_i8p calls ioffset_update
write_dataarray3_rank3_r4p calls ioffset_update
write_dataarray3_rank3_r8p calls ioffset_update
write_dataarray6_rank1_i1p calls ioffset_update
write_dataarray6_rank1_i2p calls ioffset_update
write_dataarray6_rank1_i4p calls ioffset_update
write_dataarray6_rank1_i8p calls ioffset_update
write_dataarray6_rank1_r4p calls ioffset_update
write_dataarray6_rank1_r8p calls ioffset_update
write_dataarray6_rank3_i1p calls ioffset_update
write_dataarray6_rank3_i2p calls ioffset_update
write_dataarray6_rank3_i4p calls ioffset_update
write_dataarray6_rank3_i8p calls ioffset_update
write_dataarray6_rank3_r4p calls ioffset_update
write_dataarray6_rank3_r8p calls ioffset_update