pack_data_I8_I4 – Lib_VTK_IO
pack_data_I8_I4 Subroutine
10 statements
Source File
private pure subroutine pack_data_I8_I4(a1, a2, packed)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: a1(1:)
integer(kind=I4P), intent(in) :: a2(1:)
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Called by
Source Code
   pure subroutine pack_data_I8_I4(a1, a2, packed)
   !< Pack different kinds of data into single I1P array.
   !<
   !<```fortran
   !< use befor64
   !< use penf
   !< integer(I8P)              :: a1(1)
   !< integer(I4P)              :: a2(1)
   !< integer(I1P), allocatable :: pack(:)
   !< a1(1) = 0
   !< a2(1) = 1
   !< call pack_data(a1=a1, a2=a2, packed=pack)
   !< print *, pack(9)
   !<```
   !=> 1 <<<
   integer(I8P),              intent(in)    :: a1(1:)    !< First data stream.
   integer(I4P),              intent(in)    :: a2(1:)    !< Second data stream.
   integer(I1P), allocatable, intent(inout) :: packed(:) !< Packed data into I1P array.
   integer(I1P), allocatable                :: p1(:)     !< Temporary packed data of first stream.
   integer(I1P), allocatable                :: p2(:)     !< Temporary packed data of second stream.
   p1 = transfer(a1,p1)
   p2 = transfer(a2,p2)
   packed = [p1,p2]
   endsubroutine pack_data_I8_I4
Call graph
pack_data calls pack_data_i8_i4
encode_binary_dataarray1_rank1_i1p calls pack_data
encode_binary_dataarray1_rank1_i2p calls pack_data
encode_binary_dataarray1_rank1_i8p calls pack_data
encode_binary_dataarray1_rank1_r4p calls pack_data
encode_binary_dataarray1_rank1_r8p calls pack_data
encode_binary_dataarray1_rank2_i1p calls pack_data
encode_binary_dataarray1_rank2_i2p calls pack_data
encode_binary_dataarray1_rank2_i8p calls pack_data
encode_binary_dataarray1_rank2_r4p calls pack_data
encode_binary_dataarray1_rank2_r8p calls pack_data
encode_binary_dataarray1_rank3_i1p calls pack_data
encode_binary_dataarray1_rank3_i2p calls pack_data
encode_binary_dataarray1_rank3_i8p calls pack_data
encode_binary_dataarray1_rank3_r4p calls pack_data
encode_binary_dataarray1_rank3_r8p calls pack_data
encode_binary_dataarray1_rank4_i1p calls pack_data
encode_binary_dataarray1_rank4_i2p calls pack_data
encode_binary_dataarray1_rank4_i8p calls pack_data
encode_binary_dataarray1_rank4_r4p calls pack_data
encode_binary_dataarray1_rank4_r8p calls pack_data
encode_binary_dataarray3_rank1_i1p calls pack_data
encode_binary_dataarray3_rank1_i2p calls pack_data
encode_binary_dataarray3_rank1_i8p calls pack_data
encode_binary_dataarray3_rank1_r4p calls pack_data
encode_binary_dataarray3_rank1_r8p calls pack_data
encode_binary_dataarray3_rank3_i1p calls pack_data
encode_binary_dataarray3_rank3_i2p calls pack_data
encode_binary_dataarray3_rank3_i8p calls pack_data
encode_binary_dataarray3_rank3_r4p calls pack_data
encode_binary_dataarray3_rank3_r8p calls pack_data
encode_binary_dataarray6_rank1_i1p calls pack_data
encode_binary_dataarray6_rank1_i2p calls pack_data
encode_binary_dataarray6_rank1_i8p calls pack_data
encode_binary_dataarray6_rank1_r4p calls pack_data
encode_binary_dataarray6_rank1_r8p calls pack_data
encode_binary_dataarray6_rank3_i1p calls pack_data
encode_binary_dataarray6_rank3_i2p calls pack_data
encode_binary_dataarray6_rank3_i8p calls pack_data
encode_binary_dataarray6_rank3_r4p calls pack_data
encode_binary_dataarray6_rank3_r8p calls pack_data
volatile_doctest calls pack_data
encode_binary_dataarray calls encode_binary_dataarray1_rank1_i1p, encode_binary_dataarray1_rank1_i2p, encode_binary_dataarray1_rank1_i8p, encode_binary_dataarray1_rank1_r4p, encode_binary_dataarray1_rank1_r8p, encode_binary_dataarray1_rank2_i1p, encode_binary_dataarray1_rank2_i2p, encode_binary_dataarray1_rank2_i8p, encode_binary_dataarray1_rank2_r4p, encode_binary_dataarray1_rank2_r8p, encode_binary_dataarray1_rank3_i1p, encode_binary_dataarray1_rank3_i2p, encode_binary_dataarray1_rank3_i8p, encode_binary_dataarray1_rank3_r4p, encode_binary_dataarray1_rank3_r8p, encode_binary_dataarray1_rank4_i1p, encode_binary_dataarray1_rank4_i2p, encode_binary_dataarray1_rank4_i8p, encode_binary_dataarray1_rank4_r4p, encode_binary_dataarray1_rank4_r8p, encode_binary_dataarray3_rank1_i1p, encode_binary_dataarray3_rank1_i2p, encode_binary_dataarray3_rank1_i8p, encode_binary_dataarray3_rank1_r4p, encode_binary_dataarray3_rank1_r8p, encode_binary_dataarray3_rank3_i1p, encode_binary_dataarray3_rank3_i2p, encode_binary_dataarray3_rank3_i8p, encode_binary_dataarray3_rank3_r4p, encode_binary_dataarray3_rank3_r8p, encode_binary_dataarray6_rank1_i1p, encode_binary_dataarray6_rank1_i2p, encode_binary_dataarray6_rank1_i8p, encode_binary_dataarray6_rank1_r4p, encode_binary_dataarray6_rank1_r8p, encode_binary_dataarray6_rank3_i1p, encode_binary_dataarray6_rank3_i2p, encode_binary_dataarray6_rank3_i8p, encode_binary_dataarray6_rank3_r4p, encode_binary_dataarray6_rank3_r8p
write_dataarray1_rank1_i1p calls encode_binary_dataarray
write_dataarray1_rank1_i2p calls encode_binary_dataarray
write_dataarray1_rank1_i4p calls encode_binary_dataarray
write_dataarray1_rank1_i8p calls encode_binary_dataarray
write_dataarray1_rank1_r4p calls encode_binary_dataarray
write_dataarray1_rank1_r8p calls encode_binary_dataarray
write_dataarray1_rank2_i1p calls encode_binary_dataarray
write_dataarray1_rank2_i2p calls encode_binary_dataarray
write_dataarray1_rank2_i4p calls encode_binary_dataarray
write_dataarray1_rank2_i8p calls encode_binary_dataarray
write_dataarray1_rank2_r4p calls encode_binary_dataarray
write_dataarray1_rank2_r8p calls encode_binary_dataarray
write_dataarray1_rank3_i1p calls encode_binary_dataarray
write_dataarray1_rank3_i2p calls encode_binary_dataarray
write_dataarray1_rank3_i4p calls encode_binary_dataarray
write_dataarray1_rank3_i8p calls encode_binary_dataarray
write_dataarray1_rank3_r4p calls encode_binary_dataarray
write_dataarray1_rank3_r8p calls encode_binary_dataarray
write_dataarray1_rank4_i1p calls encode_binary_dataarray
write_dataarray1_rank4_i2p calls encode_binary_dataarray
write_dataarray1_rank4_i4p calls encode_binary_dataarray
write_dataarray1_rank4_i8p calls encode_binary_dataarray
write_dataarray1_rank4_r4p calls encode_binary_dataarray
write_dataarray1_rank4_r8p calls encode_binary_dataarray
write_dataarray3_rank1_i1p calls encode_binary_dataarray
write_dataarray3_rank1_i2p calls encode_binary_dataarray
write_dataarray3_rank1_i4p calls encode_binary_dataarray
write_dataarray3_rank1_i8p calls encode_binary_dataarray
write_dataarray3_rank1_r4p calls encode_binary_dataarray
write_dataarray3_rank1_r8p calls encode_binary_dataarray
write_dataarray3_rank3_i1p calls encode_binary_dataarray
write_dataarray3_rank3_i2p calls encode_binary_dataarray
write_dataarray3_rank3_i4p calls encode_binary_dataarray
write_dataarray3_rank3_i8p calls encode_binary_dataarray
write_dataarray3_rank3_r4p calls encode_binary_dataarray
write_dataarray3_rank3_r8p calls encode_binary_dataarray
write_dataarray6_rank1_i1p calls encode_binary_dataarray
write_dataarray6_rank1_i2p calls encode_binary_dataarray
write_dataarray6_rank1_i4p calls encode_binary_dataarray
write_dataarray6_rank1_i8p calls encode_binary_dataarray
write_dataarray6_rank1_r4p calls encode_binary_dataarray
write_dataarray6_rank1_r8p calls encode_binary_dataarray
write_dataarray6_rank3_i1p calls encode_binary_dataarray
write_dataarray6_rank3_i2p calls encode_binary_dataarray
write_dataarray6_rank3_i4p calls encode_binary_dataarray
write_dataarray6_rank3_i8p calls encode_binary_dataarray
write_dataarray6_rank3_r4p calls encode_binary_dataarray
write_dataarray6_rank3_r8p calls encode_binary_dataarray
write_dataarray_appended calls encode_binary_dataarray
finalize calls write_dataarray_appended
write_check calls write_dataarray, write_fielddata, write_geo
write_connectivity calls write_dataarray
write_data calls write_dataarray, write_connectivity, write_geo
write_fielddata1_rank0 calls write_dataarray
write_geo_rect_data3_rank1_r4p calls write_dataarray
write_geo_rect_data3_rank1_r8p calls write_dataarray
write_geo_strg_data1_rank2_r4p calls write_dataarray
write_geo_strg_data1_rank2_r8p calls write_dataarray
write_geo_strg_data1_rank4_r4p calls write_dataarray
write_geo_strg_data1_rank4_r8p calls write_dataarray
write_geo_strg_data3_rank1_r4p calls write_dataarray
write_geo_strg_data3_rank1_r8p calls write_dataarray
write_geo_strg_data3_rank3_r4p calls write_dataarray
write_geo_strg_data3_rank3_r8p calls write_dataarray
write_geo_unst_data1_rank2_r4p calls write_dataarray
write_geo_unst_data1_rank2_r8p calls write_dataarray
write_geo_unst_data3_rank1_r4p calls write_dataarray
write_geo_unst_data3_rank1_r8p calls write_dataarray
write_pvts calls write_dataarray
write_slave calls write_dataarray, write_fielddata, write_geo
write_vts calls write_dataarray, write_geo
vtk_fortran_write_vtr calls write_dataarray, write_fielddata, write_geo
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_volatile calls write_check, write_slave
vtk_fortran_write_vtm calls write_data
vtk_fortran_write_vts calls write_data
vtk_fortran_write_vtu calls write_data