parse_scratch_files – Lib_VTK_IO
parse_scratch_files Function
23 statements
Source File
private function parse_scratch_files(self) result(error)
Type Bound
vtm_file
Arguments
Type Intent Optional Attributes Name
class(vtm_file), intent(inout) :: self
Return Value integer(kind=I4P)
Calls
Called by
Source Code
   function parse_scratch_files(self) result(error)
   !< Parse scratch files.
   class(vtm_file), intent(inout) :: self     !< VTM file.
   integer(I4P)                   :: error    !< Error status.
   character(9999)                :: filename !< File name of VTK file grouped into current block.
   character(9999)                :: name     !< Block name
   integer(I4P)                   :: s, f     !< Counter.
   if (allocated(self%scratch_unit)) then
      do s=1, size(self%scratch_unit, dim=1)
         ! rewind scratch file
         rewind(self%scratch_unit(s))
         ! write group name
         f = 0_I4P
         read(self%scratch_unit(s), iostat=error, fmt=*) name
         error = self%write_block(action='open', name=trim(adjustl(name)))
         ! write group filenames
         parse_file_loop : do
            read(self%scratch_unit(s), iostat=error, fmt=*) filename
            if (is_iostat_end(error)) exit parse_file_loop
            error = self%xml_writer%write_parallel_block_files(file_index=f,                     &
                                                               filename=trim(adjustl(filename)), &
                                                               name=trim(adjustl(filename)))
            f = f + 1_I4P
         enddo parse_file_loop
         ! close group
         error = self%write_block(action='close')
         ! close scratch file
         close(self%scratch_unit(s))
      enddo
   endif
   endfunction parse_scratch_files
Call graph
parse_scratch_files calls write_block, write_parallel_block_files
write_block_array calls write_parallel_block_files, write_parallel_close_block, write_parallel_open_block
write_block_scratch calls chars, upper
write_block_string calls write_parallel_block_files, chars, upper, write_parallel_close_block, write_parallel_open_block
write_parallel_block_file calls str, write_self_closing_tag
write_parallel_block_files_array calls str, write_self_closing_tag
write_parallel_block_files_string calls str, chars, split, write_self_closing_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
split calls partition, unique
write_parallel_close_block calls write_end_tag
write_parallel_open_block calls str, chars, write_start_tag
write_self_closing_tag calls stringify
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls str, chars, attributes, end_tag, is_allocated, self_closing_tag, start_tag
unique calls replace
write_end_tag calls stringify
write_start_tag calls stringify
replace calls replace_one_occurrence
self_closing_tag calls attributes
start_tag calls attributes
finalize calls parse_scratch_files
initialize calls finalize