parse – Lib_VTK_IO
parse Subroutine
13 statements
Source File
private subroutine parse(self, string, filename)
Type Bound
xml_file
Arguments
Type Intent Optional Attributes Name
class(xml_file), intent(inout) :: self
character(len=*), intent(in), optional :: string
character(len=*), intent(in), optional :: filename
Calls
Called by
Source Code
   subroutine parse(self, string, filename)
   !< Parse xml data from string or file.
   !< XML data is linearized, a DOM structured is used.
   !<
   !< @note Self data are free before trying to parse new xml data: all previously parsed data are lost.
   class(xml_file),        intent(inout) :: self     !< XML file.
   character(*), optional, intent(in)    :: string   !< String containing xml data.
   character(*), optional, intent(in)    :: filename !< File name containing xml data.
   character(len=:), allocatable         :: source   !< String containing xml data.
   call self%free
   if (present(string)) then
      call self%parse_from_string(source_string=string)
   elseif (present(filename)) then
      source = load_file_as_stream(filename=filename, fast_read=.true.)
      call self%parse_from_string(source_string=source)
   endif
   endsubroutine parse
Call graph
parse calls load_file_as_stream, parse_from_string
parse_from_string calls add_child, add_tag, get_tag_content, parse_tag_name, set
add_child calls add_child_id
get_tag_content calls find_matching_end_tag
set calls add_multiple_attributes, add_single_attribute, add_stream_attributes
add_multiple_attributes calls add_single_attribute
add_single_attribute calls alloc_attributes
add_stream_attributes calls add_single_attribute, fill, partition, slice
foxy_test_delete_tag calls parse
foxy_test_parse_file_simple calls parse
foxy_test_parse_string_nested_tags calls parse
foxy_test_parse_string_simple calls parse
foxy_test_write_tag calls parse