slice – Lib_VTK_IO
slice Function
11 statements
Source File
private pure function slice(self, istart, iend) result(raw)
Type Bound
string
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
integer, intent(in) :: istart
integer, intent(in) :: iend
Return Value character(kind=CK, len=:), allocatable
Called by
Source Code
   pure function slice(self, istart, iend) result(raw)
   !< Return the raw characters data sliced.
   !<
   !<```fortran
   !< type(string) :: astring
   !< astring = 'the Quick Brown fox Jumps over the Lazy Dog.'
   !< print "(A)", astring%slice(11,25)
   !<```
   !=> Brown fox Jumps <<<
   class(string), intent(in)              :: self   !< The string.
   integer,       intent(in)              :: istart !< Slice start index.
   integer,       intent(in)              :: iend   !< Slice end   index.
   character(kind=CK, len=:), allocatable :: raw    !< Raw characters data.
   if (allocated(self%raw)) then
      raw = self%raw(istart:iend)
   else
      raw = ''
   endif
   endfunction slice
Call graph
add_stream_attributes calls slice
volatile_doctest calls slice
set calls add_stream_attributes
create_tag_flat calls set
create_tag_nested calls set
add_attributes calls add_attributes
create_tag calls set
xml_tag calls create_tag_flat, create_tag_nested