str_a_R4P – Lib_VTK_IO
str_a_R4P Function
20 statements
Source File
private pure function str_a_R4P(n, no_sign, separator, delimiters, compact) result(str)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n(:)
logical, intent(in), optional :: no_sign
character(len=1), intent(in), optional :: separator
character(len=*), intent(in), optional :: delimiters(1:2)
logical, intent(in), optional :: compact
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   pure function str_a_R4P(n, no_sign, separator, delimiters, compact) result(str)
   !< Convert real array to string.
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1._R4P, -2._R4P])
   !<```
   !=> +0.100000E+01,-0.200000E+01 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1._R4P, 2._R4P], no_sign=.true.)
   !<```
   !=> 0.100000E+01,0.200000E+01 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1._R4P, -2._R4P], separator='|')
   !<```
   !=> +0.100000E+01|-0.200000E+01 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1._R4P, -2._R4P], delimiters=['(', ')'])
   !<```
   !=> (+0.100000E+01,-0.200000E+01) <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1._R4P, -2._R4P], compact=.true.)
   !<```
   !=> +0.1E+1,-0.2E+1 <<<
   real(R4P),    intent(in)           :: n(:)            !< Real array to be converted.
   logical,      intent(in), optional :: no_sign         !< Flag for leaving out the sign.
   character(1), intent(in), optional :: separator       !< Eventual separator of array values.
   character(*), intent(in), optional :: delimiters(1:2) !< Eventual delimiters of array values.
   logical,      intent(in), optional :: compact         !< Flag for *compacting* string encoding.
   character(len=:), allocatable      :: str             !< Returned string containing input number.
   character(DR4P)                    :: strn            !< String containing of element of input array number.
   character(len=1)                   :: sep             !< Array values separator
   integer                            :: i               !< Counter.
   str = ''
   sep = ','
   if(present(separator)) sep = separator
   do i=1,size(n)
     strn = str_R4P(no_sign=no_sign, compact=compact, n=n(i))
     str = str//sep//trim(strn)
   enddo
   str = trim(str(2:))
   if (present(delimiters)) str = delimiters(1)//str//delimiters(2)
   endfunction str_a_R4P
Call graph
str_a_r4p calls str_r4p
str_r4p calls compact_real_string
str calls str_a_r4p
bctoi_i1p calls str
bctoi_i2p calls str
bctoi_i4p calls str
bctoi_i8p calls str
encode_ascii_dataarray1_rank1_i1p calls str
encode_ascii_dataarray1_rank1_i2p calls str
encode_ascii_dataarray1_rank1_i4p calls str
encode_ascii_dataarray1_rank1_i8p calls str
encode_ascii_dataarray1_rank1_r16p calls str
encode_ascii_dataarray1_rank1_r4p calls str
encode_ascii_dataarray1_rank1_r8p calls str
encode_ascii_dataarray1_rank2_i1p calls str
encode_ascii_dataarray1_rank2_i2p calls str
encode_ascii_dataarray1_rank2_i4p calls str
encode_ascii_dataarray1_rank2_i8p calls str
encode_ascii_dataarray1_rank2_r16p calls str
encode_ascii_dataarray1_rank2_r4p calls str
encode_ascii_dataarray1_rank2_r8p calls str
encode_ascii_dataarray1_rank3_i1p calls str
encode_ascii_dataarray1_rank3_i2p calls str
encode_ascii_dataarray1_rank3_i4p calls str
encode_ascii_dataarray1_rank3_i8p calls str
encode_ascii_dataarray1_rank3_r16p calls str
encode_ascii_dataarray1_rank3_r4p calls str
encode_ascii_dataarray1_rank3_r8p calls str
encode_ascii_dataarray1_rank4_i1p calls str
encode_ascii_dataarray1_rank4_i2p calls str
encode_ascii_dataarray1_rank4_i4p calls str
encode_ascii_dataarray1_rank4_i8p calls str
encode_ascii_dataarray1_rank4_r16p calls str
encode_ascii_dataarray1_rank4_r4p calls str
encode_ascii_dataarray1_rank4_r8p calls str
encode_ascii_dataarray3_rank1_i1p calls str
encode_ascii_dataarray3_rank1_i2p calls str
encode_ascii_dataarray3_rank1_i4p calls str
encode_ascii_dataarray3_rank1_i8p calls str
encode_ascii_dataarray3_rank1_r16p calls str
encode_ascii_dataarray3_rank1_r4p calls str
encode_ascii_dataarray3_rank1_r8p calls str
encode_ascii_dataarray3_rank3_i1p calls str
encode_ascii_dataarray3_rank3_i2p calls str
encode_ascii_dataarray3_rank3_i4p calls str
encode_ascii_dataarray3_rank3_i8p calls str
encode_ascii_dataarray3_rank3_r16p calls str
encode_ascii_dataarray3_rank3_r4p calls str
encode_ascii_dataarray3_rank3_r8p calls str
encode_ascii_dataarray6_rank1_i1p calls str
encode_ascii_dataarray6_rank1_i2p calls str
encode_ascii_dataarray6_rank1_i4p calls str
encode_ascii_dataarray6_rank1_i8p calls str
encode_ascii_dataarray6_rank1_r16p calls str
encode_ascii_dataarray6_rank1_r4p calls str
encode_ascii_dataarray6_rank1_r8p calls str
encode_ascii_dataarray6_rank3_i1p calls str
encode_ascii_dataarray6_rank3_i2p calls str
encode_ascii_dataarray6_rank3_i4p calls str
encode_ascii_dataarray6_rank3_i8p calls str
encode_ascii_dataarray6_rank3_r16p calls str
encode_ascii_dataarray6_rank3_r4p calls str
encode_ascii_dataarray6_rank3_r8p calls str
string_assign_integer_i1p calls str
string_assign_integer_i2p calls str
string_assign_integer_i4p calls str
string_assign_integer_i8p calls str
string_assign_real_r16p calls str
string_assign_real_r4p calls str
string_assign_real_r8p calls str
write_dataarray_appended calls str
write_dataarray_tag calls str
write_dataarray_tag_appended calls str
write_parallel_block_file calls str
write_parallel_block_files_array calls str
write_parallel_block_files_string calls str
write_parallel_dataarray calls str
write_parallel_geo calls str
write_parallel_open_block calls str
write_piece_start_tag calls str
write_piece_start_tag_unst calls str
write_topology_tag calls str
volatile_doctest calls str, bcton
bcton calls bctoi_i1p, bctoi_i2p, bctoi_i4p, bctoi_i8p
encode_ascii_dataarray calls encode_ascii_dataarray1_rank1_i1p, encode_ascii_dataarray1_rank1_i2p, encode_ascii_dataarray1_rank1_i4p, encode_ascii_dataarray1_rank1_i8p, encode_ascii_dataarray1_rank1_r4p, encode_ascii_dataarray1_rank1_r8p, encode_ascii_dataarray1_rank2_i1p, encode_ascii_dataarray1_rank2_i2p, encode_ascii_dataarray1_rank2_i4p, encode_ascii_dataarray1_rank2_i8p, encode_ascii_dataarray1_rank2_r4p, encode_ascii_dataarray1_rank2_r8p, encode_ascii_dataarray1_rank3_i1p, encode_ascii_dataarray1_rank3_i2p, encode_ascii_dataarray1_rank3_i4p, encode_ascii_dataarray1_rank3_i8p, encode_ascii_dataarray1_rank3_r4p, encode_ascii_dataarray1_rank3_r8p, encode_ascii_dataarray1_rank4_i1p, encode_ascii_dataarray1_rank4_i2p, encode_ascii_dataarray1_rank4_i4p, encode_ascii_dataarray1_rank4_i8p, encode_ascii_dataarray1_rank4_r4p, encode_ascii_dataarray1_rank4_r8p, encode_ascii_dataarray3_rank1_i1p, encode_ascii_dataarray3_rank1_i2p, encode_ascii_dataarray3_rank1_i4p, encode_ascii_dataarray3_rank1_i8p, encode_ascii_dataarray3_rank1_r4p, encode_ascii_dataarray3_rank1_r8p, encode_ascii_dataarray3_rank3_i1p, encode_ascii_dataarray3_rank3_i2p, encode_ascii_dataarray3_rank3_i4p, encode_ascii_dataarray3_rank3_i8p, encode_ascii_dataarray3_rank3_r4p, encode_ascii_dataarray3_rank3_r8p, encode_ascii_dataarray6_rank1_i1p, encode_ascii_dataarray6_rank1_i2p, encode_ascii_dataarray6_rank1_i4p, encode_ascii_dataarray6_rank1_i8p, encode_ascii_dataarray6_rank1_r4p, encode_ascii_dataarray6_rank1_r8p, encode_ascii_dataarray6_rank3_i1p, encode_ascii_dataarray6_rank3_i2p, encode_ascii_dataarray6_rank3_i4p, encode_ascii_dataarray6_rank3_i8p, encode_ascii_dataarray6_rank3_r4p, encode_ascii_dataarray6_rank3_r8p
finalize calls write_dataarray_appended, parse_scratch_files
initialize calls write_topology_tag, finalize
write_block_array calls write_parallel_open_block, write_parallel_block_files
write_block_string calls write_parallel_open_block, write_parallel_block_files
write_dataarray1_rank1_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank1_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank1_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank1_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank1_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank1_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank2_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank2_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank2_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank2_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank2_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank2_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank3_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank3_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank3_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank3_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank3_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank3_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank4_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank4_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank4_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank4_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank4_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank4_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank1_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank1_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank1_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank1_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank1_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank1_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank3_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank3_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank3_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank3_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank3_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank3_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank1_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank1_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank1_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank1_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank1_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank1_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank3_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank3_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank3_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank3_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank3_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank3_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_pvts calls write_parallel_dataarray, write_parallel_geo, write_dataarray
parse_scratch_files calls write_parallel_block_files, write_block
write_check calls write_piece, write_dataarray, write_fielddata, write_geo
write_data calls write_piece, write_dataarray, write_connectivity, write_geo
write_slave calls write_piece, write_dataarray, write_fielddata, write_geo
write_vts calls write_piece, write_dataarray, write_geo
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_vtr calls write_piece, write_dataarray, write_fielddata, write_geo
write_connectivity calls write_dataarray
write_fielddata1_rank0 calls write_dataarray
write_geo_rect_data3_rank1_r4p calls write_dataarray
write_geo_rect_data3_rank1_r8p calls write_dataarray
write_geo_strg_data1_rank2_r4p calls write_dataarray
write_geo_strg_data1_rank2_r8p calls write_dataarray
write_geo_strg_data1_rank4_r4p calls write_dataarray
write_geo_strg_data1_rank4_r8p calls write_dataarray
write_geo_strg_data3_rank1_r4p calls write_dataarray
write_geo_strg_data3_rank1_r8p calls write_dataarray
write_geo_strg_data3_rank3_r4p calls write_dataarray
write_geo_strg_data3_rank3_r8p calls write_dataarray
write_geo_unst_data1_rank2_r4p calls write_dataarray
write_geo_unst_data1_rank2_r8p calls write_dataarray
write_geo_unst_data3_rank1_r4p calls write_dataarray
write_geo_unst_data3_rank1_r8p calls write_dataarray
vtk_fortran_write_volatile calls write_check, write_slave
vtk_fortran_write_vtm calls write_block, write_data
vtk_fortran_write_vts calls write_data
vtk_fortran_write_vtu calls write_data