strf_R4P – Lib_VTK_IO
strf_R4P Function
6 statements
Source File
private elemental function strf_R4P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
real(kind=R4P), intent(in) :: n
Return Value character(len=DR4P)
Called by
Source Code
   elemental function strf_R4P(fm, n) result(str)
   !< Convert real to string.
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(fm=FR4P, n=1._R4P)
   !<```
   !=> 0.100000E+01 <<<
   character(*), intent(in) :: fm  !< Format different from the standard for the kind.
   real(R4P),    intent(in) :: n   !< Real to be converted.
   character(DR4P)          :: str !< Returned string containing input number.
   write(str, trim(fm)) n
   endfunction strf_R4P
Call graph
str calls strf_r4p
alloc_var_i1p_1d calls str
alloc_var_i1p_2d calls str
alloc_var_i1p_3d calls str
alloc_var_i1p_4d calls str
alloc_var_i1p_5d calls str
alloc_var_i1p_6d calls str
alloc_var_i1p_7d calls str
alloc_var_i2p_1d calls str
alloc_var_i2p_2d calls str
alloc_var_i2p_3d calls str
alloc_var_i2p_4d calls str
alloc_var_i2p_5d calls str
alloc_var_i2p_6d calls str
alloc_var_i2p_7d calls str
alloc_var_i4p_1d calls str
alloc_var_i4p_2d calls str
alloc_var_i4p_3d calls str
alloc_var_i4p_4d calls str
alloc_var_i4p_5d calls str
alloc_var_i4p_6d calls str
alloc_var_i4p_7d calls str
alloc_var_i8p_1d calls str
alloc_var_i8p_2d calls str
alloc_var_i8p_3d calls str
alloc_var_i8p_4d calls str
alloc_var_i8p_5d calls str
alloc_var_i8p_6d calls str
alloc_var_i8p_7d calls str
alloc_var_r16p_1d calls str
alloc_var_r16p_2d calls str
alloc_var_r16p_3d calls str
alloc_var_r16p_4d calls str
alloc_var_r16p_5d calls str
alloc_var_r16p_6d calls str
alloc_var_r16p_7d calls str
alloc_var_r4p_1d calls str
alloc_var_r4p_2d calls str
alloc_var_r4p_3d calls str
alloc_var_r4p_4d calls str
alloc_var_r4p_5d calls str
alloc_var_r4p_6d calls str
alloc_var_r4p_7d calls str
alloc_var_r8p_1d calls str
alloc_var_r8p_2d calls str
alloc_var_r8p_3d calls str
alloc_var_r8p_4d calls str
alloc_var_r8p_5d calls str
alloc_var_r8p_6d calls str
alloc_var_r8p_7d calls str
bctoi_i1p calls str
bctoi_i2p calls str
bctoi_i4p calls str
bctoi_i8p calls str
encode_ascii_dataarray1_rank1_i1p calls str
encode_ascii_dataarray1_rank1_i2p calls str
encode_ascii_dataarray1_rank1_i4p calls str
encode_ascii_dataarray1_rank1_i8p calls str
encode_ascii_dataarray1_rank1_r16p calls str
encode_ascii_dataarray1_rank1_r4p calls str
encode_ascii_dataarray1_rank1_r8p calls str
encode_ascii_dataarray1_rank2_i1p calls str
encode_ascii_dataarray1_rank2_i2p calls str
encode_ascii_dataarray1_rank2_i4p calls str
encode_ascii_dataarray1_rank2_i8p calls str
encode_ascii_dataarray1_rank2_r16p calls str
encode_ascii_dataarray1_rank2_r4p calls str
encode_ascii_dataarray1_rank2_r8p calls str
encode_ascii_dataarray1_rank3_i1p calls str
encode_ascii_dataarray1_rank3_i2p calls str
encode_ascii_dataarray1_rank3_i4p calls str
encode_ascii_dataarray1_rank3_i8p calls str
encode_ascii_dataarray1_rank3_r16p calls str
encode_ascii_dataarray1_rank3_r4p calls str
encode_ascii_dataarray1_rank3_r8p calls str
encode_ascii_dataarray1_rank4_i1p calls str
encode_ascii_dataarray1_rank4_i2p calls str
encode_ascii_dataarray1_rank4_i4p calls str
encode_ascii_dataarray1_rank4_i8p calls str
encode_ascii_dataarray1_rank4_r16p calls str
encode_ascii_dataarray1_rank4_r4p calls str
encode_ascii_dataarray1_rank4_r8p calls str
encode_ascii_dataarray3_rank1_i1p calls str
encode_ascii_dataarray3_rank1_i2p calls str
encode_ascii_dataarray3_rank1_i4p calls str
encode_ascii_dataarray3_rank1_i8p calls str
encode_ascii_dataarray3_rank1_r16p calls str
encode_ascii_dataarray3_rank1_r4p calls str
encode_ascii_dataarray3_rank1_r8p calls str
encode_ascii_dataarray3_rank3_i1p calls str
encode_ascii_dataarray3_rank3_i2p calls str
encode_ascii_dataarray3_rank3_i4p calls str
encode_ascii_dataarray3_rank3_i8p calls str
encode_ascii_dataarray3_rank3_r16p calls str
encode_ascii_dataarray3_rank3_r4p calls str
encode_ascii_dataarray3_rank3_r8p calls str
encode_ascii_dataarray6_rank1_i1p calls str
encode_ascii_dataarray6_rank1_i2p calls str
encode_ascii_dataarray6_rank1_i4p calls str
encode_ascii_dataarray6_rank1_i8p calls str
encode_ascii_dataarray6_rank1_r16p calls str
encode_ascii_dataarray6_rank1_r4p calls str
encode_ascii_dataarray6_rank1_r8p calls str
encode_ascii_dataarray6_rank3_i1p calls str
encode_ascii_dataarray6_rank3_i2p calls str
encode_ascii_dataarray6_rank3_i4p calls str
encode_ascii_dataarray6_rank3_i8p calls str
encode_ascii_dataarray6_rank3_r16p calls str
encode_ascii_dataarray6_rank3_r4p calls str
encode_ascii_dataarray6_rank3_r8p calls str
string_assign_integer_i1p calls str
string_assign_integer_i2p calls str
string_assign_integer_i4p calls str
string_assign_integer_i8p calls str
string_assign_real_r16p calls str
string_assign_real_r4p calls str
string_assign_real_r8p calls str
stringify calls str, stringify, stringify_recursive
write_dataarray_appended calls str, write_end_tag, write_start_tag
write_dataarray_tag calls str, write_tag
write_dataarray_tag_appended calls str, write_self_closing_tag
write_parallel_block_file calls str, write_self_closing_tag
write_parallel_block_files_array calls str, write_self_closing_tag
write_parallel_block_files_string calls str, write_self_closing_tag
write_parallel_dataarray calls str, write_self_closing_tag
write_parallel_geo calls str, write_self_closing_tag
write_parallel_open_block calls str, write_start_tag
write_piece_start_tag calls str, write_start_tag
write_piece_start_tag_unst calls str, write_start_tag
write_topology_tag calls str, write_end_tag, write_self_closing_tag, write_start_tag
volatile_doctest calls str, allocate_variable, bcton, assign_allocatable
allocate_variable calls alloc_var_i1p_1d, alloc_var_i1p_2d, alloc_var_i1p_3d, alloc_var_i1p_4d, alloc_var_i1p_5d, alloc_var_i1p_6d, alloc_var_i1p_7d, alloc_var_i2p_1d, alloc_var_i2p_2d, alloc_var_i2p_3d, alloc_var_i2p_4d, alloc_var_i2p_5d, alloc_var_i2p_6d, alloc_var_i2p_7d, alloc_var_i4p_1d, alloc_var_i4p_2d, alloc_var_i4p_3d, alloc_var_i4p_4d, alloc_var_i4p_5d, alloc_var_i4p_6d, alloc_var_i4p_7d, alloc_var_i8p_1d, alloc_var_i8p_2d, alloc_var_i8p_3d, alloc_var_i8p_4d, alloc_var_i8p_5d, alloc_var_i8p_6d, alloc_var_i8p_7d, alloc_var_r4p_1d, alloc_var_r4p_2d, alloc_var_r4p_3d, alloc_var_r4p_4d, alloc_var_r4p_5d, alloc_var_r4p_6d, alloc_var_r4p_7d, alloc_var_r8p_1d, alloc_var_r8p_2d, alloc_var_r8p_3d, alloc_var_r8p_4d, alloc_var_r8p_5d, alloc_var_r8p_6d, alloc_var_r8p_7d
bcton calls bctoi_i1p, bctoi_i2p, bctoi_i4p, bctoi_i8p
encode_ascii_dataarray calls encode_ascii_dataarray1_rank1_i1p, encode_ascii_dataarray1_rank1_i2p, encode_ascii_dataarray1_rank1_i4p, encode_ascii_dataarray1_rank1_i8p, encode_ascii_dataarray1_rank1_r4p, encode_ascii_dataarray1_rank1_r8p, encode_ascii_dataarray1_rank2_i1p, encode_ascii_dataarray1_rank2_i2p, encode_ascii_dataarray1_rank2_i4p, encode_ascii_dataarray1_rank2_i8p, encode_ascii_dataarray1_rank2_r4p, encode_ascii_dataarray1_rank2_r8p, encode_ascii_dataarray1_rank3_i1p, encode_ascii_dataarray1_rank3_i2p, encode_ascii_dataarray1_rank3_i4p, encode_ascii_dataarray1_rank3_i8p, encode_ascii_dataarray1_rank3_r4p, encode_ascii_dataarray1_rank3_r8p, encode_ascii_dataarray1_rank4_i1p, encode_ascii_dataarray1_rank4_i2p, encode_ascii_dataarray1_rank4_i4p, encode_ascii_dataarray1_rank4_i8p, encode_ascii_dataarray1_rank4_r4p, encode_ascii_dataarray1_rank4_r8p, encode_ascii_dataarray3_rank1_i1p, encode_ascii_dataarray3_rank1_i2p, encode_ascii_dataarray3_rank1_i4p, encode_ascii_dataarray3_rank1_i8p, encode_ascii_dataarray3_rank1_r4p, encode_ascii_dataarray3_rank1_r8p, encode_ascii_dataarray3_rank3_i1p, encode_ascii_dataarray3_rank3_i2p, encode_ascii_dataarray3_rank3_i4p, encode_ascii_dataarray3_rank3_i8p, encode_ascii_dataarray3_rank3_r4p, encode_ascii_dataarray3_rank3_r8p, encode_ascii_dataarray6_rank1_i1p, encode_ascii_dataarray6_rank1_i2p, encode_ascii_dataarray6_rank1_i4p, encode_ascii_dataarray6_rank1_i8p, encode_ascii_dataarray6_rank1_r4p, encode_ascii_dataarray6_rank1_r8p, encode_ascii_dataarray6_rank3_i1p, encode_ascii_dataarray6_rank3_i2p, encode_ascii_dataarray6_rank3_i4p, encode_ascii_dataarray6_rank3_i8p, encode_ascii_dataarray6_rank3_r4p, encode_ascii_dataarray6_rank3_r8p
create_tag_nested calls stringify
finalize calls write_dataarray_appended, write_end_tag, parse_scratch_files
initialize calls write_topology_tag, finalize
stringify_recursive calls stringify, stringify_recursive
write_block_array calls write_parallel_open_block, write_parallel_block_files, write_parallel_close_block
write_block_string calls write_parallel_open_block, write_parallel_block_files, write_parallel_close_block
write_dataarray1_rank1_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank1_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank1_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank1_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank1_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank1_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank2_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank2_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank2_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank2_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank2_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank2_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank3_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank3_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank3_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank3_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank3_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank3_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank4_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank4_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank4_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank4_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank4_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray1_rank4_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank1_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank1_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank1_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank1_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank1_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank1_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank3_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank3_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank3_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank3_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank3_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray3_rank3_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank1_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank1_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank1_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank1_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank1_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank1_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank3_i1p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank3_i2p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank3_i4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank3_i8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank3_r4p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_dataarray6_rank3_r8p calls write_dataarray_tag_appended, write_dataarray_tag, encode_ascii_dataarray
write_end_tag calls stringify
write_pvts calls write_parallel_dataarray, write_parallel_geo, write_dataarray
write_self_closing_tag calls stringify
write_start_tag calls stringify
write_tag calls stringify
foxy_test_add_attributes calls stringify
foxy_test_create_tag calls stringify
foxy_test_delete_attributes calls stringify
foxy_test_delete_content calls stringify
foxy_test_indent_tag calls stringify
xml_tag calls create_tag_nested
assign_allocatable_i1p_1d calls allocate_variable
assign_allocatable_i1p_2d calls allocate_variable
assign_allocatable_i1p_3d calls allocate_variable
assign_allocatable_i1p_4d calls allocate_variable
assign_allocatable_i1p_5d calls allocate_variable
assign_allocatable_i1p_6d calls allocate_variable
assign_allocatable_i1p_7d calls allocate_variable
assign_allocatable_i2p_1d calls allocate_variable
assign_allocatable_i2p_2d calls allocate_variable
assign_allocatable_i2p_3d calls allocate_variable
assign_allocatable_i2p_4d calls allocate_variable
assign_allocatable_i2p_5d calls allocate_variable
assign_allocatable_i2p_6d calls allocate_variable
assign_allocatable_i2p_7d calls allocate_variable
assign_allocatable_i4p_1d calls allocate_variable
assign_allocatable_i4p_2d calls allocate_variable
assign_allocatable_i4p_3d calls allocate_variable
assign_allocatable_i4p_4d calls allocate_variable
assign_allocatable_i4p_5d calls allocate_variable
assign_allocatable_i4p_6d calls allocate_variable
assign_allocatable_i4p_7d calls allocate_variable
assign_allocatable_i8p_1d calls allocate_variable
assign_allocatable_i8p_2d calls allocate_variable
assign_allocatable_i8p_3d calls allocate_variable
assign_allocatable_i8p_4d calls allocate_variable
assign_allocatable_i8p_5d calls allocate_variable
assign_allocatable_i8p_6d calls allocate_variable
assign_allocatable_i8p_7d calls allocate_variable
assign_allocatable_r16p_1d calls allocate_variable
assign_allocatable_r16p_2d calls allocate_variable
assign_allocatable_r16p_3d calls allocate_variable
assign_allocatable_r16p_4d calls allocate_variable
assign_allocatable_r16p_5d calls allocate_variable
assign_allocatable_r16p_6d calls allocate_variable
assign_allocatable_r16p_7d calls allocate_variable
assign_allocatable_r4p_1d calls allocate_variable
assign_allocatable_r4p_2d calls allocate_variable
assign_allocatable_r4p_3d calls allocate_variable
assign_allocatable_r4p_4d calls allocate_variable
assign_allocatable_r4p_5d calls allocate_variable
assign_allocatable_r4p_6d calls allocate_variable
assign_allocatable_r4p_7d calls allocate_variable
assign_allocatable_r8p_1d calls allocate_variable
assign_allocatable_r8p_2d calls allocate_variable
assign_allocatable_r8p_3d calls allocate_variable
assign_allocatable_r8p_4d calls allocate_variable
assign_allocatable_r8p_5d calls allocate_variable
assign_allocatable_r8p_6d calls allocate_variable
assign_allocatable_r8p_7d calls allocate_variable
parse_scratch_files calls write_parallel_block_files, write_block
write_check calls write_piece, write_dataarray, write_fielddata, write_geo
write_connectivity calls write_end_tag, write_start_tag, write_dataarray
write_data calls write_piece, write_dataarray, write_geo, write_connectivity
write_dataarray_location_tag calls write_end_tag, write_start_tag
write_fielddata_tag calls write_end_tag, write_start_tag
write_geo_rect_data3_rank1_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_rect_data3_rank1_r8p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data1_rank2_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data1_rank2_r8p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data1_rank4_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data1_rank4_r8p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data3_rank1_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data3_rank1_r8p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data3_rank3_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data3_rank3_r8p calls write_end_tag, write_start_tag, write_dataarray
write_geo_unst_data1_rank2_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_unst_data1_rank2_r8p calls write_end_tag, write_start_tag, write_dataarray
write_geo_unst_data3_rank1_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_unst_data3_rank1_r8p calls write_end_tag, write_start_tag, write_dataarray
write_parallel_close_block calls write_end_tag
write_piece_end_tag calls write_end_tag
write_slave calls write_piece, write_dataarray, write_fielddata, write_geo
write_vts calls write_piece, write_dataarray, write_geo
foxy_test_add_tag calls stringify
foxy_test_delete_tag calls stringify
foxy_test_parse_file_simple calls stringify
foxy_test_parse_string_nested_tags calls stringify
foxy_test_parse_string_simple calls stringify
foxy_test_write_tag calls stringify
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_vtr calls write_piece, write_dataarray, write_fielddata, write_geo
assign_allocatable calls assign_allocatable_i1p_1d, assign_allocatable_i1p_2d, assign_allocatable_i1p_3d, assign_allocatable_i1p_4d, assign_allocatable_i1p_5d, assign_allocatable_i1p_6d, assign_allocatable_i1p_7d, assign_allocatable_i2p_1d, assign_allocatable_i2p_2d, assign_allocatable_i2p_3d, assign_allocatable_i2p_4d, assign_allocatable_i2p_5d, assign_allocatable_i2p_6d, assign_allocatable_i2p_7d, assign_allocatable_i4p_1d, assign_allocatable_i4p_2d, assign_allocatable_i4p_3d, assign_allocatable_i4p_4d, assign_allocatable_i4p_5d, assign_allocatable_i4p_6d, assign_allocatable_i4p_7d, assign_allocatable_i8p_1d, assign_allocatable_i8p_2d, assign_allocatable_i8p_3d, assign_allocatable_i8p_4d, assign_allocatable_i8p_5d, assign_allocatable_i8p_6d, assign_allocatable_i8p_7d, assign_allocatable_r4p_1d, assign_allocatable_r4p_2d, assign_allocatable_r4p_3d, assign_allocatable_r4p_4d, assign_allocatable_r4p_5d, assign_allocatable_r4p_6d, assign_allocatable_r4p_7d, assign_allocatable_r8p_1d, assign_allocatable_r8p_2d, assign_allocatable_r8p_3d, assign_allocatable_r8p_4d, assign_allocatable_r8p_5d, assign_allocatable_r8p_6d, assign_allocatable_r8p_7d
write_fielddata1_rank0 calls write_dataarray
vtk_fortran_write_volatile calls write_check, write_slave
vtk_fortran_write_vtm calls write_block, write_data
vtk_fortran_write_vts calls write_data
vtk_fortran_write_vtu calls write_data