strf_R8P – Lib_VTK_IO
strf_R8P Function
6 statements
Source File
private elemental function strf_R8P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: fm
real(kind=R8P), intent(in) :: n
Return Value character
Called by
Contents
Source Code
strf_R8P
Source Code
   elemental function strf_R8P(fm, n) result(str)
   !< Convert real to string.
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(fm=FR8P, n=1._R8P)
   !<```
   !=> 0.100000000000000E+001 <<<
   character(*), intent(in) :: fm  !< Format different from the standard for the kind.
   real(R8P),    intent(in) :: n   !< Real to be converted.
   character(DR8P)          :: str !< Returned string containing input number.
   write(str, trim(fm)) n
   endfunction strf_R8P
Call graph
str calls strf_r8p
bctoi_i8p calls str
bctoi_i4p calls str
bctoi_i2p calls str
bctoi_i1p calls str
bcton calls bctoi_i8p, bctoi_i4p, bctoi_i2p, bctoi_i1p