string_assign_real_R16P – Lib_VTK_IO
string_assign_real_R16P Subroutine
5 statements
Source File
private pure subroutine string_assign_real_R16P(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
class(string), intent(inout) :: lhs
real(kind=R16P), intent(in) :: rhs
Calls
Contents
Source Code
string_assign_real_R16P
Source Code
   pure subroutine string_assign_real_R16P(lhs, rhs)
   !< Assignment operator from real input.
   !<
   !<```fortran
   !< use penf
   !< type(string) :: astring
   !< logical      :: test_passed(1)
   !< astring = 3.021e6_R8P
   !< test_passed(1) = astring%to_number(kind=1._R8P)==3.021e6_R8P
   !< print '(L1)', all(test_passed)
   !<```
   !=> T <<<
   class(string), intent(inout) :: lhs !< Left hand side.
   real(R16P),    intent(in)    :: rhs !< Right hand side.
   lhs%raw = trim(str(rhs))
   endsubroutine string_assign_real_R16P
Call graph
string_assign_real_r16p calls str
str calls str_i8p, str_a_r8p, str_r8p, str_a_i4p, strf_i2p, str_r4p, str_i1p, strf_i4p, str_a_r4p, strf_r4p, str_i2p, str_a_i2p, strf_i8p, str_bol, strf_r8p, str_i4p, str_a_i8p, strf_i1p, str_a_i1p
str_a_r8p calls str_r8p
str_r8p calls compact_real_string
str_a_i4p calls str_i4p
str_r4p calls compact_real_string
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_a_i1p calls str_i1p