write_geo_strg_data3_rank3_R8P – Lib_VTK_IO
write_geo_strg_data3_rank3_R8P Function
16 statements
Source File
private function write_geo_strg_data3_rank3_R8P(self, n, x, y, z) result(error)
Type Bound
xml_writer_abstract
Arguments
Type Intent Optional Attributes Name
class(xml_writer_abstract), intent(inout) :: self
integer(kind=I4P), intent(in) :: n
real(kind=R8P), intent(in) :: x(1:,1:,1:)
real(kind=R8P), intent(in) :: y(1:,1:,1:)
real(kind=R8P), intent(in) :: z(1:,1:,1:)
Return Value integer(kind=I4P)
Calls
Called by
Source Code
   function write_geo_strg_data3_rank3_R8P(self, n, x, y, z) result(error)
   !< Write mesh with **StructuredGrid** topology (data 3, rank 3, R8P).
   class(xml_writer_abstract), intent(inout) :: self        !< Writer.
   integer(I4P),               intent(in)    :: n           !< Number of nodes.
   real(R8P),                  intent(in)    :: x(1:,1:,1:) !< X coordinates.
   real(R8P),                  intent(in)    :: y(1:,1:,1:) !< Y coordinates.
   real(R8P),                  intent(in)    :: z(1:,1:,1:) !< Z coordinates.
   integer(I4P)                              :: error       !< Error status.
   if ((n/=size(x, dim=1)*size(x, dim=2)*size(x, dim=3)).or.&
       (n/=size(y, dim=1)*size(y, dim=2)*size(y, dim=3)).or.&
       (n/=size(z, dim=1)*size(z, dim=2)*size(z, dim=3))) then
      self%error = 1
      return
   endif
   call self%write_start_tag(name='Points')
   error = self%write_dataarray(data_name='Points', x=x, y=y, z=z)
   call self%write_end_tag(name='Points')
   error = self%error
   endfunction write_geo_strg_data3_rank3_R8P
Call graph
write_geo_strg_data3_rank3_r8p calls write_dataarray, write_end_tag, write_start_tag
write_end_tag calls stringify
write_start_tag calls stringify
stringify calls chars, end_tag, is_allocated, self_closing_tag, start_tag
write_dataarray1_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank2_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray1_rank4_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray3_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank1_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i1p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i2p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_i8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_r4p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray6_rank3_r8p calls encode_binary_dataarray, write_dataarray_tag
write_dataarray_location_tag calls write_end_tag, write_start_tag, chars, upper
encode_binary_dataarray calls encode_binary_dataarray1_rank1_i1p, encode_binary_dataarray1_rank1_i2p, encode_binary_dataarray1_rank1_i4p, encode_binary_dataarray1_rank1_i8p, encode_binary_dataarray1_rank1_r4p, encode_binary_dataarray1_rank1_r8p, encode_binary_dataarray1_rank2_i1p, encode_binary_dataarray1_rank2_i2p, encode_binary_dataarray1_rank2_i4p, encode_binary_dataarray1_rank2_i8p, encode_binary_dataarray1_rank2_r4p, encode_binary_dataarray1_rank2_r8p, encode_binary_dataarray1_rank3_i1p, encode_binary_dataarray1_rank3_i2p, encode_binary_dataarray1_rank3_i4p, encode_binary_dataarray1_rank3_i8p, encode_binary_dataarray1_rank3_r4p, encode_binary_dataarray1_rank3_r8p, encode_binary_dataarray1_rank4_i1p, encode_binary_dataarray1_rank4_i2p, encode_binary_dataarray1_rank4_i4p, encode_binary_dataarray1_rank4_i8p, encode_binary_dataarray1_rank4_r4p, encode_binary_dataarray1_rank4_r8p, encode_binary_dataarray3_rank1_i1p, encode_binary_dataarray3_rank1_i2p, encode_binary_dataarray3_rank1_i4p, encode_binary_dataarray3_rank1_i8p, encode_binary_dataarray3_rank1_r4p, encode_binary_dataarray3_rank1_r8p, encode_binary_dataarray3_rank3_i1p, encode_binary_dataarray3_rank3_i2p, encode_binary_dataarray3_rank3_i4p, encode_binary_dataarray3_rank3_i8p, encode_binary_dataarray3_rank3_r4p, encode_binary_dataarray3_rank3_r8p, encode_binary_dataarray6_rank1_i1p, encode_binary_dataarray6_rank1_i2p, encode_binary_dataarray6_rank1_i4p, encode_binary_dataarray6_rank1_i8p, encode_binary_dataarray6_rank1_r4p, encode_binary_dataarray6_rank1_r8p, encode_binary_dataarray6_rank3_i1p, encode_binary_dataarray6_rank3_i2p, encode_binary_dataarray6_rank3_i4p, encode_binary_dataarray6_rank3_i8p, encode_binary_dataarray6_rank3_r4p, encode_binary_dataarray6_rank3_r8p
self_closing_tag calls attributes
start_tag calls attributes
write_dataarray_tag calls chars, str, write_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
encode_binary_dataarray1_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_i4p calls b64_encode
encode_binary_dataarray1_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i4p calls b64_encode
encode_binary_dataarray1_rank2_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i4p calls b64_encode
encode_binary_dataarray1_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i4p calls b64_encode
encode_binary_dataarray1_rank4_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_r8p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i4p calls b64_encode
encode_binary_dataarray3_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i4p calls b64_encode
encode_binary_dataarray3_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_r8p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i4p calls b64_encode
encode_binary_dataarray6_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i4p calls b64_encode
encode_binary_dataarray6_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_r8p calls b64_encode, pack_data
write_tag calls stringify
b64_encode calls b64_encode_i1, b64_encode_i1_a, b64_encode_i2, b64_encode_i2_a, b64_encode_i4, b64_encode_i4_a, b64_encode_i8, b64_encode_i8_a, b64_encode_r4, b64_encode_r4_a, b64_encode_r8, b64_encode_r8_a, b64_encode_string, b64_encode_string_a
pack_data calls pack_data_i1_i2, pack_data_i1_i4, pack_data_i1_i8, pack_data_i1_r4, pack_data_i1_r8, pack_data_i2_i1, pack_data_i2_i4, pack_data_i2_i8, pack_data_i2_r4, pack_data_i2_r8, pack_data_i4_i1, pack_data_i4_i2, pack_data_i4_i8, pack_data_i4_r4, pack_data_i4_r8, pack_data_i8_i1, pack_data_i8_i2, pack_data_i8_i4, pack_data_i8_r4, pack_data_i8_r8, pack_data_r4_i1, pack_data_r4_i2, pack_data_r4_i4, pack_data_r4_i8, pack_data_r4_r8, pack_data_r8_i1, pack_data_r8_i2, pack_data_r8_i4, pack_data_r8_i8, pack_data_r8_r4
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
b64_encode_i1 calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_string calls byte_size, encode_bits
b64_encode_string_a calls byte_size, encode_bits
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p
write_check calls write_geo
write_data calls write_geo
write_slave calls write_geo
write_vts calls write_geo
vtk_fortran_write_vtr calls write_geo
vtk_fortran_write_pvts calls write_vts
vtk_fortran_write_volatile calls write_check, write_slave
vtk_fortran_write_vtm calls write_data
vtk_fortran_write_vts calls write_data
vtk_fortran_write_vtu calls write_data