write_parallel_geo – Lib_VTK_IO
write_parallel_geo Function
20 statements
Source File
private function write_parallel_geo(self, source, nx1, nx2, ny1, ny2, nz1, nz2) result(error)
Type Bound
xml_writer_abstract
Arguments
Type Intent Optional Attributes Name
class(xml_writer_abstract), intent(inout) :: self
character(len=*), intent(in) :: source
integer(kind=I4P), intent(in), optional :: nx1
integer(kind=I4P), intent(in), optional :: nx2
integer(kind=I4P), intent(in), optional :: ny1
integer(kind=I4P), intent(in), optional :: ny2
integer(kind=I4P), intent(in), optional :: nz1
integer(kind=I4P), intent(in), optional :: nz2
Return Value integer(kind=I4P)
Calls
Called by
Source Code
   function write_parallel_geo(self, source, nx1, nx2, ny1, ny2, nz1, nz2) result(error)
   !< Write parallel (partitioned) VTK-XML geo source file.
   class(xml_writer_abstract), intent(inout)        :: self   !< Writer.
   character(*),               intent(in)           :: source !< Source file name containing the piece data.
   integer(I4P),               intent(in), optional :: nx1    !< Initial node of x axis.
   integer(I4P),               intent(in), optional :: nx2    !< Final node of x axis.
   integer(I4P),               intent(in), optional :: ny1    !< Initial node of y axis.
   integer(I4P),               intent(in), optional :: ny2    !< Final node of y axis.
   integer(I4P),               intent(in), optional :: nz1    !< Initial node of z axis.
   integer(I4P),               intent(in), optional :: nz2    !< Final node of z axis.
   integer(I4P)                                     :: error  !< Error status.
   type(string)                                     :: buffer !< Buffer string.
   select case (self%topology%chars())
   case('PRectilinearGrid', 'PStructuredGrid')
      buffer = 'Extent="'// &
               trim(str(n=nx1))//' '//trim(str(n=nx2))//' '// &
               trim(str(n=ny1))//' '//trim(str(n=ny2))//' '// &
               trim(str(n=nz1))//' '//trim(str(n=nz2))//'" Source="'//trim(adjustl(source))//'"'
   case('PUnstructuredGrid')
      buffer = 'Source="'//trim(adjustl(source))//'"'
   endselect
   call self%write_self_closing_tag(name='Piece', attributes=buffer%chars())
   error = self%error
   endfunction write_parallel_geo
Call graph
write_parallel_geo calls str, chars, write_self_closing_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
write_self_closing_tag calls stringify
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls str, chars, attributes, end_tag, is_allocated, self_closing_tag, start_tag
self_closing_tag calls attributes
start_tag calls attributes
write_pvts calls write_parallel_geo
vtk_fortran_write_pvts calls write_pvts