write_block_string – Lib_VTK_IO
write_block_string Function
25 statements
Source File
private function write_block_string(self, action, filenames, names, name) result(error)
Type Bound
vtm_file
Arguments
Type Intent Optional Attributes Name
class(vtm_file), intent(inout) :: self
character(len=*), intent(in), optional :: action
character(len=*), intent(in), optional :: filenames
character(len=*), intent(in), optional :: names
character(len=*), intent(in), optional :: name
Return Value integer(kind=I4P)
Calls
Called by
Source Code
   function write_block_string(self, action, filenames, names, name) result(error)
   !< Write one block dataset (string input).
   !<
   !<#### Example of usage: 3 files blocks
   !<```fortran
   !< error = vtm%write_block(filenames='file_1.vts file_2.vts file_3.vtu', name='my_block')
   !<```
   !<
   !<#### Example of usage: 3 files blocks with custom name
   !<```fortran
   !< error = vtm%write_block(filenames='file_1.vts file_2.vts file_3.vtu', names='block-bar block-foo block-baz', name='my_block')
   !<```
   class(vtm_file), intent(inout)        :: self      !< VTM file.
   character(*),    intent(in), optional :: action    !< Action: [open, close, write].
   character(*),    intent(in), optional :: filenames !< File names of VTK files grouped into current block.
   character(*),    intent(in), optional :: names     !< Auxiliary names attributed to each files.
   character(*),    intent(in), optional :: name      !< Block name
   integer(I4P)                          :: error     !< Error status.
   type(string)                          :: action_   !< Action string.
   if (present(action)) then
      action_ = trim(adjustl(action)) ; action_ = action_%upper()
      select case(action_%chars())
      case('OPEN')
         error = self%xml_writer%write_parallel_open_block(name=name)
      case('CLOSE')
         error = self%xml_writer%write_parallel_close_block()
      case('WRITE')
         if (present(filenames)) error = self%xml_writer%write_parallel_block_files(filenames=filenames, names=names)
      endselect
   else
      error = self%xml_writer%write_parallel_open_block(name=name)
      error = self%xml_writer%write_parallel_block_files(filenames=filenames, names=names)
      error = self%xml_writer%write_parallel_close_block()
   endif
   endfunction write_block_string
Call graph
write_block_string calls write_parallel_block_files, chars, upper, write_parallel_close_block, write_parallel_open_block
write_parallel_close_block calls write_end_tag
write_parallel_open_block calls chars, str, write_start_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
write_end_tag calls stringify
write_parallel_block_file calls str, write_self_closing_tag
write_parallel_block_files_array calls str, write_self_closing_tag
write_parallel_block_files_string calls chars, str, split, write_self_closing_tag
write_start_tag calls stringify
split calls partition, unique
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls chars, str, attributes, end_tag, is_allocated, self_closing_tag, start_tag
write_self_closing_tag calls stringify
self_closing_tag calls attributes
start_tag calls attributes
unique calls replace
replace calls replace_one_occurrence
parse_scratch_files calls write_block
vtk_fortran_write_vtm calls write_block
finalize calls parse_scratch_files
initialize calls finalize