write_piece_start_tag – Lib_VTK_IO
write_piece_start_tag Function
14 statements
Source File
private function write_piece_start_tag(self, nx1, nx2, ny1, ny2, nz1, nz2) result(error)
Type Bound
xml_writer_abstract
Arguments
Type Intent Optional Attributes Name
class(xml_writer_abstract), intent(inout) :: self
integer(kind=I4P), intent(in) :: nx1
integer(kind=I4P), intent(in) :: nx2
integer(kind=I4P), intent(in) :: ny1
integer(kind=I4P), intent(in) :: ny2
integer(kind=I4P), intent(in) :: nz1
integer(kind=I4P), intent(in) :: nz2
Return Value integer(kind=I4P)
Calls
Called by
Source Code
   function write_piece_start_tag(self, nx1, nx2, ny1, ny2, nz1, nz2) result(error)
   !< Write `<Piece ...>` start tag.
   class(xml_writer_abstract), intent(inout) :: self           !< Writer.
   integer(I4P),               intent(in)    :: nx1            !< Initial node of x axis.
   integer(I4P),               intent(in)    :: nx2            !< Final node of x axis.
   integer(I4P),               intent(in)    :: ny1            !< Initial node of y axis.
   integer(I4P),               intent(in)    :: ny2            !< Final node of y axis.
   integer(I4P),               intent(in)    :: nz1            !< Initial node of z axis.
   integer(I4P),               intent(in)    :: nz2            !< Final node of z axis.
   integer(I4P)                              :: error          !< Error status.
   type(string)                              :: tag_attributes !< Tag attributes.
   tag_attributes = 'Extent="'//trim(str(n=nx1))//' '//trim(str(n=nx2))//' '// &
                                trim(str(n=ny1))//' '//trim(str(n=ny2))//' '// &
                                trim(str(n=nz1))//' '//trim(str(n=nz2))//'"'
   call self%write_start_tag(name='Piece', attributes=tag_attributes%chars())
   error = self%error
   endfunction write_piece_start_tag
Call graph
write_piece_start_tag calls str, chars, write_start_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
write_start_tag calls stringify
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls str, chars, attributes, end_tag, is_allocated, self_closing_tag, start_tag
self_closing_tag calls attributes
start_tag calls attributes
write_check calls write_piece
write_data calls write_piece
write_slave calls write_piece
write_vts calls write_piece
vtk_fortran_write_vtr calls write_piece
vtk_fortran_write_pvts calls write_vts
vtk_fortran_write_volatile calls write_check, write_slave
vtk_fortran_write_vtm calls write_data
vtk_fortran_write_vts calls write_data
vtk_fortran_write_vtu calls write_data