write_parallel_dataarray – Lib_VTK_IO
write_parallel_dataarray Function
15 statements
Source File
private function write_parallel_dataarray(self, data_name, data_type, number_of_components) result(error)
Type Bound
xml_writer_abstract
Arguments
Type Intent Optional Attributes Name
class(xml_writer_abstract), intent(inout) :: self
character(len=*), intent(in) :: data_name
character(len=*), intent(in) :: data_type
integer(kind=I4P), intent(in), optional :: number_of_components
Return Value integer(kind=I4P)
Calls
Called by
Source Code
   function write_parallel_dataarray(self, data_name, data_type, number_of_components) result(error)
   !< Write parallel (partitioned) VTK-XML dataarray info.
   class(xml_writer_abstract), intent(inout)        :: self                 !< Writer.
   character(*),               intent(in)           :: data_name            !< Data name.
   character(*),               intent(in)           :: data_type            !< Type of dataarray.
   integer(I4P),               intent(in), optional :: number_of_components !< Number of dataarray components.
   integer(I4P)                                     :: error                !< Error status.
   type(string)                                     :: buffer               !< Buffer string.
   if (present(number_of_components)) then
      buffer = 'type="'//trim(adjustl(data_type))//'" Name="'//trim(adjustl(data_name))//&
               '" NumberOfComponents="'//trim(str(number_of_components, .true.))//'"'
   else
      buffer = 'type="'//trim(adjustl(data_type))//'" Name="'//trim(adjustl(data_name))//'"'
   endif
   call self%write_self_closing_tag(name='PDataArray', attributes=buffer%chars())
   error = self%error
   endfunction write_parallel_dataarray
Call graph
write_parallel_dataarray calls str, chars, write_self_closing_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
write_self_closing_tag calls stringify
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls str, chars, attributes, end_tag, is_allocated, self_closing_tag, start_tag
self_closing_tag calls attributes
start_tag calls attributes
write_pvts calls write_parallel_dataarray
vtk_fortran_write_pvts calls write_pvts