write_dataarray_appended – Lib_VTK_IO
write_dataarray_appended Subroutine
107 statements
Source File
private subroutine write_dataarray_appended(self)
Type Bound
xml_writer_appended
Arguments
Type Intent Optional Attributes Name
class(xml_writer_appended), intent(inout) :: self
Calls
Called by
Source Code
  subroutine write_dataarray_appended(self)
  !< Do nothing, ascii data cannot be appended.
  class(xml_writer_appended), intent(inout) :: self              !< Writer.
  type(string)                              :: tag_attributes    !< Tag attributes.
  integer(I4P)                              :: n_byte            !< Bytes count.
  character(len=2)                          :: dataarray_type    !< Dataarray type = R8,R4,I8,I4,I2,I1.
  integer(I4P)                              :: dataarray_dim     !< Dataarray dimension.
  real(R8P),    allocatable                 :: dataarray_R8P(:)  !< Dataarray buffer of R8P.
  real(R4P),    allocatable                 :: dataarray_R4P(:)  !< Dataarray buffer of R4P.
  integer(I8P), allocatable                 :: dataarray_I8P(:)  !< Dataarray buffer of I8P.
  integer(I4P), allocatable                 :: dataarray_I4P(:)  !< Dataarray buffer of I4P.
  integer(I2P), allocatable                 :: dataarray_I2P(:)  !< Dataarray buffer of I2P.
  integer(I1P), allocatable                 :: dataarray_I1P(:)  !< Dataarray buffer of I1P.
  call self%write_start_tag(name='AppendedData', attributes='encoding="'//self%encoding%chars()//'"')
  write(unit=self%xml, iostat=self%error)'_'
  endfile(unit=self%scratch, iostat=self%error)
  rewind(unit=self%scratch, iostat=self%error)
  do
    call read_dataarray_from_scratch
    if (self%error==0) call write_dataarray_on_xml
    if (is_iostat_end(self%error)) exit
  enddo
  close(unit=self%scratch, iostat=self%error)
  write(unit=self%xml, iostat=self%error)end_rec
  call self%write_end_tag(name='AppendedData')
  contains
    subroutine read_dataarray_from_scratch
    !< Read the current dataaray from scratch file.
    read(unit=self%scratch, iostat=self%error, end=10)n_byte, dataarray_type, dataarray_dim
    select case(dataarray_type)
    case('R8')
      if (allocated(dataarray_R8P)) deallocate(dataarray_R8P) ; allocate(dataarray_R8P(1:dataarray_dim))
      read(unit=self%scratch, iostat=self%error)dataarray_R8P
    case('R4')
      if (allocated(dataarray_R4P)) deallocate(dataarray_R4P) ; allocate(dataarray_R4P(1:dataarray_dim))
      read(unit=self%scratch, iostat=self%error)dataarray_R4P
    case('I8')
      if (allocated(dataarray_I8P)) deallocate(dataarray_I8P) ; allocate(dataarray_I8P(1:dataarray_dim))
      read(unit=self%scratch, iostat=self%error)dataarray_I8P
    case('I4')
      if (allocated(dataarray_I4P)) deallocate(dataarray_I4P) ; allocate(dataarray_I4P(1:dataarray_dim))
      read(unit=self%scratch, iostat=self%error)dataarray_I4P
    case('I2')
      if (allocated(dataarray_I2P)) deallocate(dataarray_I2P) ; allocate(dataarray_I2P(1:dataarray_dim))
      read(unit=self%scratch, iostat=self%error)dataarray_I2P
    case('I1')
      if (allocated(dataarray_I1P)) deallocate(dataarray_I1P) ; allocate(dataarray_I1P(1:dataarray_dim))
      read(unit=self%scratch, iostat=self%error)dataarray_I1P
    case default
      self%error = 1
      write (stderr,'(A)')' error: bad dataarray_type = '//dataarray_type
      write (stderr,'(A)')' bytes = '//trim(str(n=n_byte))
      write (stderr,'(A)')' dataarray dimension = '//trim(str(n=dataarray_dim))
    endselect
    10 return
    endsubroutine read_dataarray_from_scratch
    subroutine write_dataarray_on_xml
    !< Write the current dataaray on xml file.
    character(len=:), allocatable  :: code !< Dataarray encoded with Base64 codec.
    if (self%encoding=='raw') then
      select case(dataarray_type)
      case('R8')
        write(unit=self%xml, iostat=self%error)n_byte, dataarray_R8P
        deallocate(dataarray_R8P)
      case('R4')
        write(unit=self%xml, iostat=self%error)n_byte, dataarray_R4P
        deallocate(dataarray_R4P)
      case('I8')
        write(unit=self%xml, iostat=self%error)n_byte, dataarray_I8P
        deallocate(dataarray_I8P)
      case('I4')
        write(unit=self%xml, iostat=self%error)n_byte, dataarray_I4P
        deallocate(dataarray_I4P)
      case('I2')
        write(unit=self%xml, iostat=self%error)n_byte, dataarray_I2P
        deallocate(dataarray_I2P)
      case('I1')
        write(unit=self%xml, iostat=self%error)n_byte, dataarray_I1P
        deallocate(dataarray_I1P)
      endselect
    else
      select case(dataarray_type)
      case('R8')
        code = encode_binary_dataarray(x=dataarray_R8P)
        write(unit=self%xml, iostat=self%error)code
      case('R4')
        code = encode_binary_dataarray(x=dataarray_R4P)
        write(unit=self%xml, iostat=self%error)code
      case('I8')
        code = encode_binary_dataarray(x=dataarray_I8P)
        write(unit=self%xml, iostat=self%error)code
      case('I4')
        code = encode_binary_dataarray(x=dataarray_I4P)
        write(unit=self%xml, iostat=self%error)code
      case('I2')
        code = encode_binary_dataarray(x=dataarray_I2P)
        write(unit=self%xml, iostat=self%error)code
      case('I1')
        code = encode_binary_dataarray(x=dataarray_I1P)
        write(unit=self%xml, iostat=self%error)code
      endselect
    endif
    endsubroutine write_dataarray_on_xml
  endsubroutine write_dataarray_appended
Call graph
write_dataarray_appended calls encode_binary_dataarray, str, chars, write_end_tag, write_start_tag
encode_binary_dataarray calls encode_binary_dataarray1_rank1_i1p, encode_binary_dataarray1_rank1_i2p, encode_binary_dataarray1_rank1_i4p, encode_binary_dataarray1_rank1_i8p, encode_binary_dataarray1_rank1_r4p, encode_binary_dataarray1_rank1_r8p, encode_binary_dataarray1_rank2_i1p, encode_binary_dataarray1_rank2_i2p, encode_binary_dataarray1_rank2_i4p, encode_binary_dataarray1_rank2_i8p, encode_binary_dataarray1_rank2_r4p, encode_binary_dataarray1_rank2_r8p, encode_binary_dataarray1_rank3_i1p, encode_binary_dataarray1_rank3_i2p, encode_binary_dataarray1_rank3_i4p, encode_binary_dataarray1_rank3_i8p, encode_binary_dataarray1_rank3_r4p, encode_binary_dataarray1_rank3_r8p, encode_binary_dataarray1_rank4_i1p, encode_binary_dataarray1_rank4_i2p, encode_binary_dataarray1_rank4_i4p, encode_binary_dataarray1_rank4_i8p, encode_binary_dataarray1_rank4_r4p, encode_binary_dataarray1_rank4_r8p, encode_binary_dataarray3_rank1_i1p, encode_binary_dataarray3_rank1_i2p, encode_binary_dataarray3_rank1_i4p, encode_binary_dataarray3_rank1_i8p, encode_binary_dataarray3_rank1_r4p, encode_binary_dataarray3_rank1_r8p, encode_binary_dataarray3_rank3_i1p, encode_binary_dataarray3_rank3_i2p, encode_binary_dataarray3_rank3_i4p, encode_binary_dataarray3_rank3_i8p, encode_binary_dataarray3_rank3_r4p, encode_binary_dataarray3_rank3_r8p, encode_binary_dataarray6_rank1_i1p, encode_binary_dataarray6_rank1_i2p, encode_binary_dataarray6_rank1_i4p, encode_binary_dataarray6_rank1_i8p, encode_binary_dataarray6_rank1_r4p, encode_binary_dataarray6_rank1_r8p, encode_binary_dataarray6_rank3_i1p, encode_binary_dataarray6_rank3_i2p, encode_binary_dataarray6_rank3_i4p, encode_binary_dataarray6_rank3_i8p, encode_binary_dataarray6_rank3_r4p, encode_binary_dataarray6_rank3_r8p
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
write_end_tag calls stringify
write_start_tag calls stringify
encode_binary_dataarray1_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_i4p calls b64_encode
encode_binary_dataarray1_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_i4p calls b64_encode
encode_binary_dataarray1_rank2_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank2_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_i4p calls b64_encode
encode_binary_dataarray1_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank3_r8p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i1p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i2p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_i4p calls b64_encode
encode_binary_dataarray1_rank4_i8p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_r4p calls b64_encode, pack_data
encode_binary_dataarray1_rank4_r8p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_i4p calls b64_encode
encode_binary_dataarray3_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray3_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_i4p calls b64_encode
encode_binary_dataarray3_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray3_rank3_r8p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i1p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i2p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_i4p calls b64_encode
encode_binary_dataarray6_rank1_i8p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_r4p calls b64_encode, pack_data
encode_binary_dataarray6_rank1_r8p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i1p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i2p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_i4p calls b64_encode
encode_binary_dataarray6_rank3_i8p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_r4p calls b64_encode, pack_data
encode_binary_dataarray6_rank3_r8p calls b64_encode, pack_data
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls str, chars, attributes, end_tag, is_allocated, self_closing_tag, start_tag
b64_encode calls b64_encode_i1, b64_encode_i1_a, b64_encode_i2, b64_encode_i2_a, b64_encode_i4, b64_encode_i4_a, b64_encode_i8, b64_encode_i8_a, b64_encode_r4, b64_encode_r4_a, b64_encode_r8, b64_encode_r8_a, b64_encode_string, b64_encode_string_a
pack_data calls pack_data_i1_i2, pack_data_i1_i4, pack_data_i1_i8, pack_data_i1_r4, pack_data_i1_r8, pack_data_i2_i1, pack_data_i2_i4, pack_data_i2_i8, pack_data_i2_r4, pack_data_i2_r8, pack_data_i4_i1, pack_data_i4_i2, pack_data_i4_i8, pack_data_i4_r4, pack_data_i4_r8, pack_data_i8_i1, pack_data_i8_i2, pack_data_i8_i4, pack_data_i8_r4, pack_data_i8_r8, pack_data_r4_i1, pack_data_r4_i2, pack_data_r4_i4, pack_data_r4_i8, pack_data_r4_r8, pack_data_r8_i1, pack_data_r8_i2, pack_data_r8_i4, pack_data_r8_i8, pack_data_r8_r4
self_closing_tag calls attributes
start_tag calls attributes
b64_encode_i1 calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_string calls byte_size, encode_bits
b64_encode_string_a calls byte_size, encode_bits
byte_size calls byte_size_chr, byte_size_i1p, byte_size_i2p, byte_size_i4p, byte_size_i8p, byte_size_r4p, byte_size_r8p
finalize calls write_dataarray_appended