write_parallel_block_file – Lib_VTK_IO
write_parallel_block_file Function
13 statements
Source File
private function write_parallel_block_file(self, file_index, filename, name) result(error)
Type Bound
xml_writer_abstract
Arguments
Type Intent Optional Attributes Name
class(xml_writer_abstract), intent(inout) :: self
integer(kind=I4P), intent(in) :: file_index
character(len=*), intent(in) :: filename
character(len=*), intent(in), optional :: name
Return Value integer(kind=I4P)
Calls
Called by
Source Code
   function write_parallel_block_file(self, file_index, filename, name) result(error)
   !< Write single file that belong to the current block.
   class(xml_writer_abstract), intent(inout)        :: self       !< Writer.
   integer(I4P),               intent(in)           :: file_index !< Index of file in the list.
   character(*),               intent(in)           :: filename   !< Wrapped file names.
   character(*),               intent(in), optional :: name       !< Names attributed to wrapped file.
   integer(I4P)                                     :: error      !< Error status.
   if (present(name)) then
      call self%write_self_closing_tag(name='DataSet',                                      &
                                       attributes='index="'//trim(str(file_index, .true.))//&
                                                 '" file="'//trim(adjustl(filename))//      &
                                                 '" name="'//trim(adjustl(name))//'"')
   else
      call self%write_self_closing_tag(name='DataSet',                                       &
                                       attributes='index="'//trim(str(file_index, .true.))// &
                                                 '" file="'//trim(adjustl(filename))//'"')
   endif
   error = self%error
   endfunction write_parallel_block_file
Call graph
write_parallel_block_file calls str, write_self_closing_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
write_self_closing_tag calls stringify
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls str, attributes, chars, end_tag, is_allocated, self_closing_tag, start_tag
self_closing_tag calls attributes
start_tag calls attributes
parse_scratch_files calls write_parallel_block_files, write_block
write_block_array calls write_parallel_block_files
write_block_string calls write_parallel_block_files
finalize calls parse_scratch_files
initialize calls finalize
vtk_fortran_write_vtm calls write_block