write_fielddata_tag – Lib_VTK_IO
write_fielddata_tag Function
15 statements
Source File
private function write_fielddata_tag(self, action) result(error)
Type Bound
xml_writer_abstract
Arguments
Type Intent Optional Attributes Name
class(xml_writer_abstract), intent(inout) :: self
character(len=*), intent(in) :: action
Return Value integer(kind=I4P)
Calls
Called by
Source Code
   function write_fielddata_tag(self, action) result(error)
   !< Write `<FieldData>`/`</FieldData>` start/end tag.
   class(xml_writer_abstract), intent(inout) :: self      !< Writer.
   character(*),               intent(in)    :: action    !< Action: **open** or **close** tag.
   integer(I4P)                              :: error     !< Error status.
   type(string)                              :: action_   !< Action string.
   action_ = trim(adjustl(action)) ; action_ = action_%upper()
   select case(action_%chars())
   case('OPEN')
      call self%write_start_tag(name='FieldData')
   case('CLOSE')
      call self%write_end_tag(name='FieldData')
   endselect
   error = self%error
   endfunction write_fielddata_tag
Call graph
write_fielddata_tag calls chars, upper, write_end_tag, write_start_tag
write_end_tag calls stringify
write_start_tag calls stringify
stringify calls chars, str, attributes, end_tag, is_allocated, self_closing_tag, start_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
self_closing_tag calls attributes
start_tag calls attributes
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
write_check calls write_fielddata
write_slave calls write_fielddata
vtk_fortran_write_vtr calls write_fielddata
vtk_fortran_write_volatile calls write_check, write_slave