write_dataarray3_rank3_R4P – Lib_VTK_IO
write_dataarray3_rank3_R4P Function
17 statements
Source File
private function write_dataarray3_rank3_R4P(self, data_name, x, y, z, is_tuples) result(error)
Type Bound
xml_writer_ascii_local
Arguments
Type Intent Optional Attributes Name
class(xml_writer_ascii_local), intent(inout) :: self
character(len=*), intent(in) :: data_name
real(kind=R4P), intent(in) :: x(1:,1:,1:)
real(kind=R4P), intent(in) :: y(1:,1:,1:)
real(kind=R4P), intent(in) :: z(1:,1:,1:)
logical, intent(in), optional :: is_tuples
Return Value integer(kind=I4P)
Calls
Source Code
  function write_dataarray3_rank3_R4P(self, data_name, x, y, z, is_tuples) result(error)
  !< Write `<DataArray... NumberOfComponents="3"...>...</DataArray>` tag (R4P).
  class(xml_writer_ascii_local), intent(inout)        :: self         !< Writer.
  character(*),                  intent(in)           :: data_name    !< Data name.
  real(R4P),                     intent(in)           :: x(1:,1:,1:)  !< X component of data variable.
  real(R4P),                     intent(in)           :: y(1:,1:,1:)  !< Y component of data variable.
  real(R4P),                     intent(in)           :: z(1:,1:,1:)  !< Z component of data variable.
  logical,                       intent(in), optional :: is_tuples    !< Use "NumberOfTuples" instead of "NumberOfComponents".
  integer(I4P)                                        :: error        !< Error status.
  character(len=:), allocatable                       :: data_type    !< Data type.
  integer(I4P)                                        :: n_components !< Number of components.
  character(len=:), allocatable                       :: code         !< Data variable encoded, ascii or Base64 codec.
  data_type = 'Float32'
  n_components = 3
  code = encode_ascii_dataarray(x=x, y=y, z=z)
  call self%write_dataarray_tag(data_type=data_type, number_of_components=n_components, data_name=data_name, data_content=code, &
                                is_tuples=is_tuples)
  error = self%error
  endfunction write_dataarray3_rank3_R4P
Call graph
write_dataarray3_rank3_r4p calls encode_ascii_dataarray, write_dataarray_tag
encode_ascii_dataarray calls encode_ascii_dataarray1_rank1_i1p, encode_ascii_dataarray1_rank1_i2p, encode_ascii_dataarray1_rank1_i4p, encode_ascii_dataarray1_rank1_i8p, encode_ascii_dataarray1_rank1_r4p, encode_ascii_dataarray1_rank1_r8p, encode_ascii_dataarray1_rank2_i1p, encode_ascii_dataarray1_rank2_i2p, encode_ascii_dataarray1_rank2_i4p, encode_ascii_dataarray1_rank2_i8p, encode_ascii_dataarray1_rank2_r4p, encode_ascii_dataarray1_rank2_r8p, encode_ascii_dataarray1_rank3_i1p, encode_ascii_dataarray1_rank3_i2p, encode_ascii_dataarray1_rank3_i4p, encode_ascii_dataarray1_rank3_i8p, encode_ascii_dataarray1_rank3_r4p, encode_ascii_dataarray1_rank3_r8p, encode_ascii_dataarray1_rank4_i1p, encode_ascii_dataarray1_rank4_i2p, encode_ascii_dataarray1_rank4_i4p, encode_ascii_dataarray1_rank4_i8p, encode_ascii_dataarray1_rank4_r4p, encode_ascii_dataarray1_rank4_r8p, encode_ascii_dataarray3_rank1_i1p, encode_ascii_dataarray3_rank1_i2p, encode_ascii_dataarray3_rank1_i4p, encode_ascii_dataarray3_rank1_i8p, encode_ascii_dataarray3_rank1_r4p, encode_ascii_dataarray3_rank1_r8p, encode_ascii_dataarray3_rank3_i1p, encode_ascii_dataarray3_rank3_i2p, encode_ascii_dataarray3_rank3_i4p, encode_ascii_dataarray3_rank3_i8p, encode_ascii_dataarray3_rank3_r4p, encode_ascii_dataarray3_rank3_r8p, encode_ascii_dataarray6_rank1_i1p, encode_ascii_dataarray6_rank1_i2p, encode_ascii_dataarray6_rank1_i4p, encode_ascii_dataarray6_rank1_i8p, encode_ascii_dataarray6_rank1_r4p, encode_ascii_dataarray6_rank1_r8p, encode_ascii_dataarray6_rank3_i1p, encode_ascii_dataarray6_rank3_i2p, encode_ascii_dataarray6_rank3_i4p, encode_ascii_dataarray6_rank3_i8p, encode_ascii_dataarray6_rank3_r4p, encode_ascii_dataarray6_rank3_r8p
write_dataarray_tag calls str, chars, write_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
encode_ascii_dataarray1_rank1_i1p calls str
encode_ascii_dataarray1_rank1_i2p calls str
encode_ascii_dataarray1_rank1_i4p calls str
encode_ascii_dataarray1_rank1_i8p calls str
encode_ascii_dataarray1_rank1_r4p calls str
encode_ascii_dataarray1_rank1_r8p calls str
encode_ascii_dataarray1_rank2_i1p calls str
encode_ascii_dataarray1_rank2_i2p calls str
encode_ascii_dataarray1_rank2_i4p calls str
encode_ascii_dataarray1_rank2_i8p calls str
encode_ascii_dataarray1_rank2_r4p calls str
encode_ascii_dataarray1_rank2_r8p calls str
encode_ascii_dataarray1_rank3_i1p calls str
encode_ascii_dataarray1_rank3_i2p calls str
encode_ascii_dataarray1_rank3_i4p calls str
encode_ascii_dataarray1_rank3_i8p calls str
encode_ascii_dataarray1_rank3_r4p calls str
encode_ascii_dataarray1_rank3_r8p calls str
encode_ascii_dataarray1_rank4_i1p calls str
encode_ascii_dataarray1_rank4_i2p calls str
encode_ascii_dataarray1_rank4_i4p calls str
encode_ascii_dataarray1_rank4_i8p calls str
encode_ascii_dataarray1_rank4_r4p calls str
encode_ascii_dataarray1_rank4_r8p calls str
encode_ascii_dataarray3_rank1_i1p calls str
encode_ascii_dataarray3_rank1_i2p calls str
encode_ascii_dataarray3_rank1_i4p calls str
encode_ascii_dataarray3_rank1_i8p calls str
encode_ascii_dataarray3_rank1_r4p calls str
encode_ascii_dataarray3_rank1_r8p calls str
encode_ascii_dataarray3_rank3_i1p calls str
encode_ascii_dataarray3_rank3_i2p calls str
encode_ascii_dataarray3_rank3_i4p calls str
encode_ascii_dataarray3_rank3_i8p calls str
encode_ascii_dataarray3_rank3_r4p calls str
encode_ascii_dataarray3_rank3_r8p calls str
encode_ascii_dataarray6_rank1_i1p calls str
encode_ascii_dataarray6_rank1_i2p calls str
encode_ascii_dataarray6_rank1_i4p calls str
encode_ascii_dataarray6_rank1_i8p calls str
encode_ascii_dataarray6_rank1_r4p calls str
encode_ascii_dataarray6_rank1_r8p calls str
encode_ascii_dataarray6_rank3_i1p calls str
encode_ascii_dataarray6_rank3_i2p calls str
encode_ascii_dataarray6_rank3_i4p calls str
encode_ascii_dataarray6_rank3_i8p calls str
encode_ascii_dataarray6_rank3_r4p calls str
encode_ascii_dataarray6_rank3_r8p calls str
write_tag calls stringify
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls str, chars, attributes, end_tag, is_allocated, self_closing_tag, start_tag
self_closing_tag calls attributes
start_tag calls attributes