write_parallel_close_block – Lib_VTK_IO
write_parallel_close_block Function
7 statements
Source File
private function write_parallel_close_block(self) result(error)
Type Bound
xml_writer_abstract
Arguments
Type Intent Optional Attributes Name
class(xml_writer_abstract), intent(inout) :: self
Return Value integer(kind=I4P)
Calls
Called by
Source Code
   function write_parallel_close_block(self) result(error)
   !< Close a block container.
   class(xml_writer_abstract), intent(inout) :: self  !< Writer.
   integer(I4P)                              :: error !< Error status.
   self%vtm_block(2) = -1
   call self%write_end_tag(name='Block')
   error = self%error
   endfunction write_parallel_close_block
Call graph
write_parallel_close_block calls write_end_tag
write_end_tag calls stringify
stringify calls str, attributes, chars, end_tag, is_allocated, self_closing_tag, start_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
self_closing_tag calls attributes
start_tag calls attributes
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
write_block_array calls write_parallel_close_block
write_block_string calls write_parallel_close_block
parse_scratch_files calls write_block
vtk_fortran_write_vtm calls write_block
finalize calls parse_scratch_files
initialize calls finalize