write_dataarray3_rank1_I2P – Lib_VTK_IO
write_dataarray3_rank1_I2P Function
17 statements
Source File
private function write_dataarray3_rank1_I2P(self, data_name, x, y, z, is_tuples) result(error)
Arguments
Type Intent Optional Attributes Name
class(xml_writer_binary_local), intent(inout) :: self
character, intent(in) :: data_name
integer(kind=I2P), intent(in) :: x(1:)
integer(kind=I2P), intent(in) :: y(1:)
integer(kind=I2P), intent(in) :: z(1:)
logical, intent(in), optional :: is_tuples
Return Value integer(kind=I4P)
Calls
Contents
Source Code
write_dataarray3_rank1_I2P
Source Code
   function write_dataarray3_rank1_I2P(self, data_name, x, y, z, is_tuples) result(error)
   !< Write `<DataArray... NumberOfComponents="3"...>...</DataArray>` tag (I2P).
   class(xml_writer_binary_local), intent(inout)        :: self         !< Writer.
   character(*),                   intent(in)           :: data_name    !< Data name.
   integer(I2P),                   intent(in)           :: x(1:)        !< X component of data variable.
   integer(I2P),                   intent(in)           :: y(1:)        !< Y component of data variable.
   integer(I2P),                   intent(in)           :: z(1:)        !< Z component of data variable.
   logical,                        intent(in), optional :: is_tuples    !< Use "NumberOfTuples" instead of "NumberOfComponents".
   integer(I4P)                                         :: error        !< Error status.
   character(len=:), allocatable                        :: data_type    !< Data type.
   integer(I4P)                                         :: n_components !< Number of components.
   character(len=:), allocatable                        :: code         !< Data variable encoded, binary or Base64 codec.
   data_type = 'Int16'
   n_components = 3
   code = encode_binary_dataarray(x=x, y=y, z=z)
   call self%write_dataarray_tag(data_type=data_type, number_of_components=n_components, data_name=data_name, data_content=code, &
                                 is_tuples=is_tuples)
   error = self%error
   endfunction write_dataarray3_rank1_I2P
Call graph
write_dataarray3_rank1_i2p calls encode_binary_dataarray
encode_binary_dataarray calls encode_binary_dataarray1_rank1_i8p, encode_binary_dataarray1_rank3_i8p, encode_binary_dataarray6_rank1_i8p, encode_binary_dataarray1_rank4_i2p, encode_binary_dataarray3_rank3_r8p, encode_binary_dataarray6_rank3_i2p, encode_binary_dataarray1_rank1_i1p, encode_binary_dataarray1_rank3_i1p, encode_binary_dataarray3_rank1_r4p, encode_binary_dataarray3_rank3_i4p, encode_binary_dataarray6_rank1_i1p, encode_binary_dataarray1_rank1_r8p, encode_binary_dataarray1_rank2_i8p, encode_binary_dataarray1_rank3_r8p, encode_binary_dataarray1_rank4_i8p, encode_binary_dataarray6_rank1_r8p, encode_binary_dataarray6_rank3_i8p, encode_binary_dataarray3_rank1_i2p, encode_binary_dataarray1_rank1_i4p, encode_binary_dataarray1_rank3_i4p, encode_binary_dataarray1_rank4_i1p, encode_binary_dataarray3_rank3_r4p, encode_binary_dataarray6_rank1_i4p, encode_binary_dataarray6_rank3_i1p, encode_binary_dataarray1_rank2_r8p, encode_binary_dataarray1_rank2_i2p, encode_binary_dataarray1_rank4_r8p, encode_binary_dataarray3_rank1_i8p, encode_binary_dataarray3_rank3_i2p, encode_binary_dataarray6_rank3_r8p, encode_binary_dataarray1_rank1_r4p, encode_binary_dataarray1_rank2_i4p, encode_binary_dataarray1_rank3_r4p, encode_binary_dataarray1_rank4_i4p, encode_binary_dataarray3_rank1_i1p, encode_binary_dataarray6_rank1_r4p, encode_binary_dataarray6_rank3_i4p, encode_binary_dataarray1_rank1_i2p, encode_binary_dataarray1_rank3_i2p, encode_binary_dataarray3_rank1_r8p, encode_binary_dataarray3_rank3_i8p, encode_binary_dataarray6_rank1_i2p, encode_binary_dataarray1_rank2_r4p, encode_binary_dataarray1_rank2_i1p, encode_binary_dataarray1_rank4_r4p, encode_binary_dataarray3_rank1_i4p, encode_binary_dataarray3_rank3_i1p, encode_binary_dataarray6_rank3_r4p
encode_binary_dataarray1_rank1_i8p calls pack_data, b64_encode
encode_binary_dataarray1_rank3_i8p calls pack_data, b64_encode
encode_binary_dataarray6_rank1_i8p calls pack_data, b64_encode
encode_binary_dataarray1_rank4_i2p calls pack_data, b64_encode
encode_binary_dataarray3_rank3_r8p calls pack_data, b64_encode
encode_binary_dataarray6_rank3_i2p calls pack_data, b64_encode
encode_binary_dataarray1_rank1_i1p calls pack_data, b64_encode
encode_binary_dataarray1_rank3_i1p calls pack_data, b64_encode
encode_binary_dataarray3_rank1_r4p calls pack_data, b64_encode
encode_binary_dataarray3_rank3_i4p calls b64_encode
encode_binary_dataarray6_rank1_i1p calls pack_data, b64_encode
encode_binary_dataarray1_rank1_r8p calls pack_data, b64_encode
encode_binary_dataarray1_rank2_i8p calls pack_data, b64_encode
encode_binary_dataarray1_rank3_r8p calls pack_data, b64_encode
encode_binary_dataarray1_rank4_i8p calls pack_data, b64_encode
encode_binary_dataarray6_rank1_r8p calls pack_data, b64_encode
encode_binary_dataarray6_rank3_i8p calls pack_data, b64_encode
encode_binary_dataarray3_rank1_i2p calls pack_data, b64_encode
encode_binary_dataarray1_rank1_i4p calls b64_encode
encode_binary_dataarray1_rank3_i4p calls b64_encode
encode_binary_dataarray1_rank4_i1p calls pack_data, b64_encode
encode_binary_dataarray3_rank3_r4p calls pack_data, b64_encode
encode_binary_dataarray6_rank1_i4p calls b64_encode
encode_binary_dataarray6_rank3_i1p calls pack_data, b64_encode
encode_binary_dataarray1_rank2_r8p calls pack_data, b64_encode
encode_binary_dataarray1_rank2_i2p calls pack_data, b64_encode
encode_binary_dataarray1_rank4_r8p calls pack_data, b64_encode
encode_binary_dataarray3_rank1_i8p calls pack_data, b64_encode
encode_binary_dataarray3_rank3_i2p calls pack_data, b64_encode
encode_binary_dataarray6_rank3_r8p calls pack_data, b64_encode
encode_binary_dataarray1_rank1_r4p calls pack_data, b64_encode
encode_binary_dataarray1_rank2_i4p calls b64_encode
encode_binary_dataarray1_rank3_r4p calls pack_data, b64_encode
encode_binary_dataarray1_rank4_i4p calls b64_encode
encode_binary_dataarray3_rank1_i1p calls pack_data, b64_encode
encode_binary_dataarray6_rank1_r4p calls pack_data, b64_encode
encode_binary_dataarray6_rank3_i4p calls b64_encode
encode_binary_dataarray1_rank1_i2p calls pack_data, b64_encode
encode_binary_dataarray1_rank3_i2p calls pack_data, b64_encode
encode_binary_dataarray3_rank1_r8p calls pack_data, b64_encode
encode_binary_dataarray3_rank3_i8p calls pack_data, b64_encode
encode_binary_dataarray6_rank1_i2p calls pack_data, b64_encode
encode_binary_dataarray1_rank2_r4p calls pack_data, b64_encode
encode_binary_dataarray1_rank2_i1p calls pack_data, b64_encode
encode_binary_dataarray1_rank4_r4p calls pack_data, b64_encode
encode_binary_dataarray3_rank1_i4p calls b64_encode
encode_binary_dataarray3_rank3_i1p calls pack_data, b64_encode
encode_binary_dataarray6_rank3_r4p calls pack_data, b64_encode
pack_data calls pack_data_r4_r8, pack_data_i2_r4, pack_data_i1_i2, pack_data_i8_i2, pack_data_r8_r4, pack_data_r4_i2, pack_data_i4_r4, pack_data_i2_i1, pack_data_r8_i2, pack_data_i8_r4, pack_data_i4_i1, pack_data_i1_i8, pack_data_r4_i8, pack_data_i8_i1, pack_data_i2_i8, pack_data_r8_i8, pack_data_r4_i1, pack_data_i4_i8, pack_data_i1_r8, pack_data_r8_i1, pack_data_i8_i4, pack_data_i2_r8, pack_data_i1_i4, pack_data_r4_i4, pack_data_i4_r8, pack_data_i2_i4, pack_data_r8_i4, pack_data_i8_r8, pack_data_i4_i2, pack_data_i1_r4
b64_encode calls b64_encode_r4, b64_encode_r4_a, b64_encode_i2, b64_encode_i2_a, b64_encode_i8, b64_encode_i8_a, b64_encode_i1, b64_encode_i1_a, b64_encode_r8, b64_encode_r8_a, b64_encode_i4, b64_encode_i4_a, b64_encode_string, b64_encode_string_a
b64_encode_r4 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_i1 calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_string calls encode_bits, byte_size
b64_encode_string_a calls encode_bits, byte_size
byte_size calls byte_size_r8p, byte_size_i1p, byte_size_chr, byte_size_i4p, byte_size_i8p, byte_size_i2p, byte_size_r4p