write_dataarray_tag_appended – Lib_VTK_IO
write_dataarray_tag_appended Subroutine
17 statements
Source File
private subroutine write_dataarray_tag_appended(self, data_type, number_of_components, data_name, is_tuples)
Type Bound
xml_writer_abstract
Arguments
Type Intent Optional Attributes Name
class(xml_writer_abstract), intent(inout) :: self
character(len=*), intent(in) :: data_type
integer(kind=I4P), intent(in) :: number_of_components
character(len=*), intent(in) :: data_name
logical, intent(in), optional :: is_tuples
Calls
Called by
Source Code
   subroutine write_dataarray_tag_appended(self, data_type, number_of_components, data_name, is_tuples)
   !< Write `<DataArray.../>` tag.
   class(xml_writer_abstract), intent(inout)        :: self                 !< Writer.
   character(*),               intent(in)           :: data_type            !< Type of dataarray.
   integer(I4P),               intent(in)           :: number_of_components !< Number of dataarray components.
   character(*),               intent(in)           :: data_name            !< Data name.
   logical,                    intent(in), optional :: is_tuples            !< Use "NumberOfTuples".
   type(string)                                     :: tag_attributes       !< Tag attributes.
   logical                                          :: is_tuples_           !< Use "NumberOfTuples".
   is_tuples_ = .false.
   if (present(is_tuples)) is_tuples_ = is_tuples
   if (is_tuples_) then
      tag_attributes =  'type="'//trim(adjustl(data_type))//            &
        '" NumberOfTuples="'//trim(str(number_of_components, .true.))// &
        '" Name="'//trim(adjustl(data_name))//                          &
        '" format="'//self%format_ch//                                  &
        '" offset="'//trim(str(self%ioffset, .true.))//'"'
   else
      tag_attributes = 'type="'//trim(adjustl(data_type))//                 &
        '" NumberOfComponents="'//trim(str(number_of_components, .true.))// &
        '" Name="'//trim(adjustl(data_name))//                              &
        '" format="'//self%format_ch//                                      &
        '" offset="'//trim(str(self%ioffset, .true.))//'"'
   endif
   call self%write_self_closing_tag(name='DataArray', attributes=tag_attributes%chars())
   endsubroutine write_dataarray_tag_appended
Call graph
write_dataarray_tag_appended calls str, chars, write_self_closing_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
write_self_closing_tag calls stringify
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
stringify calls str, chars, attributes, end_tag, is_allocated, self_closing_tag, start_tag
self_closing_tag calls attributes
start_tag calls attributes
write_dataarray1_rank1_i1p calls write_dataarray_tag_appended
write_dataarray1_rank1_i2p calls write_dataarray_tag_appended
write_dataarray1_rank1_i4p calls write_dataarray_tag_appended
write_dataarray1_rank1_i8p calls write_dataarray_tag_appended
write_dataarray1_rank1_r4p calls write_dataarray_tag_appended
write_dataarray1_rank1_r8p calls write_dataarray_tag_appended
write_dataarray1_rank2_i1p calls write_dataarray_tag_appended
write_dataarray1_rank2_i2p calls write_dataarray_tag_appended
write_dataarray1_rank2_i4p calls write_dataarray_tag_appended
write_dataarray1_rank2_i8p calls write_dataarray_tag_appended
write_dataarray1_rank2_r4p calls write_dataarray_tag_appended
write_dataarray1_rank2_r8p calls write_dataarray_tag_appended
write_dataarray1_rank3_i1p calls write_dataarray_tag_appended
write_dataarray1_rank3_i2p calls write_dataarray_tag_appended
write_dataarray1_rank3_i4p calls write_dataarray_tag_appended
write_dataarray1_rank3_i8p calls write_dataarray_tag_appended
write_dataarray1_rank3_r4p calls write_dataarray_tag_appended
write_dataarray1_rank3_r8p calls write_dataarray_tag_appended
write_dataarray1_rank4_i1p calls write_dataarray_tag_appended
write_dataarray1_rank4_i2p calls write_dataarray_tag_appended
write_dataarray1_rank4_i4p calls write_dataarray_tag_appended
write_dataarray1_rank4_i8p calls write_dataarray_tag_appended
write_dataarray1_rank4_r4p calls write_dataarray_tag_appended
write_dataarray1_rank4_r8p calls write_dataarray_tag_appended
write_dataarray3_rank1_i1p calls write_dataarray_tag_appended
write_dataarray3_rank1_i2p calls write_dataarray_tag_appended
write_dataarray3_rank1_i4p calls write_dataarray_tag_appended
write_dataarray3_rank1_i8p calls write_dataarray_tag_appended
write_dataarray3_rank1_r4p calls write_dataarray_tag_appended
write_dataarray3_rank1_r8p calls write_dataarray_tag_appended
write_dataarray3_rank3_i1p calls write_dataarray_tag_appended
write_dataarray3_rank3_i2p calls write_dataarray_tag_appended
write_dataarray3_rank3_i4p calls write_dataarray_tag_appended
write_dataarray3_rank3_i8p calls write_dataarray_tag_appended
write_dataarray3_rank3_r4p calls write_dataarray_tag_appended
write_dataarray3_rank3_r8p calls write_dataarray_tag_appended
write_dataarray6_rank1_i1p calls write_dataarray_tag_appended
write_dataarray6_rank1_i2p calls write_dataarray_tag_appended
write_dataarray6_rank1_i4p calls write_dataarray_tag_appended
write_dataarray6_rank1_i8p calls write_dataarray_tag_appended
write_dataarray6_rank1_r4p calls write_dataarray_tag_appended
write_dataarray6_rank1_r8p calls write_dataarray_tag_appended
write_dataarray6_rank3_i1p calls write_dataarray_tag_appended
write_dataarray6_rank3_i2p calls write_dataarray_tag_appended
write_dataarray6_rank3_i4p calls write_dataarray_tag_appended
write_dataarray6_rank3_i8p calls write_dataarray_tag_appended
write_dataarray6_rank3_r4p calls write_dataarray_tag_appended
write_dataarray6_rank3_r8p calls write_dataarray_tag_appended